#ifndef ELFSPECVERIFIER_H                                                                                                                                                                                // Colorize: green
#define ELFSPECVERIFIER_H                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/specs_verifier/specs/specverifier.h>                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QHash>                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class ElfSpecVerifier: public SpecVerifier                                                                                                                                                               // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    ElfSpecVerifier(); // TEST: NO                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    void verify(SpecVerifyThread *thread) override; // TEST: NO                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private:                                                                                                                                                                                                 // Colorize: green
    void checkWithSpecification(SpecVerifyThread *thread, const QString &specContent); // TEST: NO                                                                                                       // Colorize: green
    void checkElfHeader(SpecVerifyThread *thread, const QString &specContent); // TEST: NO                                                                                                               // Colorize: green
    void checkElfHeaderIdentification(SpecVerifyThread *thread, const QString &specContent); // TEST: NO                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QHash<QString, QString> mElfTypeToNgosTypeMap; // ELF type => NGOS type                                                                                                                              // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // ELFSPECVERIFIER_H                                                                                                                                                                              // Colorize: green
