#include "intelcpuidspecverifier.h"                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QDebug>                                                                                                                                                                                        // Colorize: green
#include <QEventLoop>                                                                                                                                                                                    // Colorize: green
#include <QFile>                                                                                                                                                                                         // Colorize: green
#include <QNetworkAccessManager>                                                                                                                                                                         // Colorize: green
#include <QNetworkReply>                                                                                                                                                                                 // Colorize: green
#include <QNetworkRequest>                                                                                                                                                                               // Colorize: green
#include <QProcess>                                                                                                                                                                                      // Colorize: green
#include <QTemporaryDir>                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define INTEL_SPECIFICATION_URL "https://cdrdv2.intel.com/v1/dl/getContent/671199" // Version: April 2022                                                                                                           // Colorize: green
#define INTEL_PDF               "intelcpuid.pdf"                                                                                                                                                             // Colorize: green
#define INTEL_TXT               "intelcpuid.txt"                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define INTEL_CPUID00000000EAX_H "src/os/shared/common/src/com/ngos/shared/common/cpu/lib/cpuid/cpuid00000000eax.h"                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
IntelCpuidSpecVerifier::IntelCpuidSpecVerifier()                                                                                                                                                             // Colorize: green
    : SpecVerifier()                                                                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void IntelCpuidSpecVerifier::verify(SpecVerifyThread *thread)                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Q_ASSERT(thread != nullptr);                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QTemporaryDir tempDir;                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Create temporary directory                                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (!tempDir.isValid())                                                                                                                                                                          // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            thread->addError("Failed to create temporary directory for INTEL CPUID specification");                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return;                                                                                                                                                                                      // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Download specification                                                                                                                                                                            // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QNetworkAccessManager  manager;                                                                                                                                                                  // Colorize: green
        QNetworkReply         *reply;                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Send network request                                                                                                                                                                          // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QNetworkRequest request;                                                                                                                                                                     // Colorize: green
            request.setUrl(QUrl(INTEL_SPECIFICATION_URL));                                                                                                                                                 // Colorize: green
            reply = manager.get(request);                                                                                                                                                                // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Wait for finish                                                                                                                                                                               // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QEventLoop waitLoop;                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            QObject::connect(reply, SIGNAL(finished()),                                 &waitLoop, SLOT(quit()));                                                                                        // Colorize: green
            QObject::connect(reply, SIGNAL(errorOccurred(QNetworkReply::NetworkError)), &waitLoop, SLOT(quit()));                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            waitLoop.exec();                                                                                                                                                                             // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Check status code                                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QVariant statusCode = reply->attribute(QNetworkRequest::HttpStatusCodeAttribute);                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (statusCode.toInt() != 200)                                                                                                                                                               // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                thread->addError(QString("Failed to get INTEL CPUID specification from: %1")                                                                                                               // Colorize: green
                                            .arg(INTEL_SPECIFICATION_URL)                                                                                                                                  // Colorize: green
                );                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                delete reply;                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return;                                                                                                                                                                                  // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        QByteArray content = reply->readAll();                                                                                                                                                           // Colorize: green
        delete reply;                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Write documentation to file                                                                                                                                                                   // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QFile file(tempDir.path() + "/" + INTEL_PDF);                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (!file.open(QIODevice::WriteOnly))                                                                                                                                                        // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                thread->addError("Failed to create temporary file for INTEL CPUID specification");                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return;                                                                                                                                                                                  // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            file.write(content);                                                                                                                                                                         // Colorize: green
            file.close();                                                                                                                                                                                // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Convert PDF to text                                                                                                                                                                               // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QProcess process;                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        process.setWorkingDirectory(tempDir.path());                                                                                                                                                     // Colorize: green
        process.start("pdftotext", QStringList() << INTEL_PDF << INTEL_TXT);                                                                                                                                 // Colorize: green
        process.waitForFinished(-1);                                                                                                                                                                     // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString specContent;                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Read specification text                                                                                                                                                                           // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QFile file(tempDir.path() + "/" + INTEL_TXT);                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (!file.open(QIODevice::ReadOnly))                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            thread->addError("Failed to open INTEL CPUID specification");                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return;                                                                                                                                                                                      // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        specContent = QString::fromUtf8(file.readAll());                                                                                                                                                 // Colorize: green
        file.close();                                                                                                                                                                                    // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Replace some special characters                                                                                                                                                           // Colorize: green
    {                                                                                                                                                                                            // Colorize: green
        specContent.replace(QChar(0x00AE), "(R)");  // Replace registered sign character    // https://www.compart.com/en/unicode/U+00AE                                                       // Colorize: green
    }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    checkWithSpecification(thread, specContent);                                                                                                                                                         // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void IntelCpuidSpecVerifier::checkWithSpecification(SpecVerifyThread *thread, const QString &specContent)                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Q_ASSERT(thread      != nullptr);                                                                                                                                                                    // Colorize: green
    Q_ASSERT(specContent != "");                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    qint64 errorsBefore = thread->getErrors().size();                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Check code with specification                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        checkIntelSpecification(thread, specContent);                                                                                                                                                      // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    if (thread->getErrors().size() == errorsBefore)                                                                                                                                                      // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        thread->addMessage("Code verified with INTEL CPUID specification");                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    else                                                                                                                                                                                                 // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        thread->addMessage("Found error in code with INTEL CPUID specification");                                                                                                                          // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void IntelCpuidSpecVerifier::checkIntelSpecification(SpecVerifyThread *thread, const QString &specContent)                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Q_ASSERT(thread      != nullptr);                                                                                                                                                                    // Colorize: green
    Q_ASSERT(specContent != "");                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString versionText;                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Init versionText                                                                                                                                                                                  // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        versionText =                                                                                                                                                                                    // Colorize: green
            "Intel(R) 64 and IA-32 Architectures\n"                                                                                                                                                        // Colorize: green
            "Software Developer’s Manual\n"                                                                                                                                                              // Colorize: green
            "Volume 2A:\n"                                                                                                                                                                               // Colorize: green
            "Instruction Set Reference, A-L\n"                                                                                                                                                           // Colorize: green
            "\n"                                                                                                                                                                                         // Colorize: green
            "NOTE: The Intel(R) 64 and IA-32 Architectures Software Developer's Manual consists of ten volumes:\n"                                                                                         // Colorize: green
            "Basic Architecture, Order Number 253665; Instruction Set Reference A-L, Order Number 253666;\n"                                                                                             // Colorize: green
            "Instruction Set Reference M-U, Order Number 253667; Instruction Set Reference V-Z, Order Number\n"                                                                                          // Colorize: green
            "326018; Instruction Set Reference, Order Number 334569; System Programming Guide, Part 1, Order\n"                                                                                          // Colorize: green
            "Number 253668; System Programming Guide, Part 2, Order Number 253669; System Programming\n"                                                                                                 // Colorize: green
            "Guide, Part 3, Order Number 326019; System Programming Guide, Part 4, Order Number 332831;\n"                                                                                               // Colorize: green
            "Model-Specific Registers, Order Number 335592. Refer to all ten volumes when evaluating your design\n"                                                                                      // Colorize: green
            "needs.\n"                                                                                                                                                                                   // Colorize: green
            "\n"                                                                                                                                                                                         // Colorize: green
            "Order Number: 253666-077US\n"                                                                                                                                                               // Colorize: green
            "April 2022";                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Check that specification contains required text                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (!specContent.contains(versionText))                                                                                                                                                          // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            thread->addError("INTEL CPUID specification version didn't match with the stored one");                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return;                                                                                                                                                                                      // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
IntelCpuidSpecVerifier intelCpuidSpecVerifier;                                                                                                                                                               // Colorize: green
