#ifndef COM_NGOS_DEVTOOLS_CODE_GENERATOR_GENERATORS_ASSETS_ZZZ_GENERATORS_CONSOLEGLYPHGENERATOR_H                                                                                                        // Colorize: green
#define COM_NGOS_DEVTOOLS_CODE_GENERATOR_GENERATORS_ASSETS_ZZZ_GENERATORS_CONSOLEGLYPHGENERATOR_H                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_generator/generators/assets/assetsgenerator.h>                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class ConsoleGlyphGenerator: public AssetsGenerator                                                                                                                                                      // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    ConsoleGlyphGenerator(); // TEST: NO                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    bool generate(const QString &path) override; // TEST: NO                                                                                                                                             // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_CODE_GENERATOR_GENERATORS_ASSETS_ZZZ_GENERATORS_CONSOLEGLYPHGENERATOR_H                                                                                                      // Colorize: green
