#ifndef COM_NGOS_SHARED_COMMON_BOOTPARAMS_LIB_KERNELINFO_H                                                                                                                                             // Colorize: green
#define COM_NGOS_SHARED_COMMON_BOOTPARAMS_LIB_KERNELINFO_H                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct KernelInfo                                                                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    good_Address_t location;      // Address of kernel image                                                                                                                                            // Colorize: green
    good_I64       size;          // Size of kernel image (Configure part + [De]compressed Kernel part)                                                                                            // Colorize: green
    good_I64       allocatedSize; // kernelSize aligned to page size + page table + stack ( + decompressed Kernel part if it compressed)                                                           // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_BOOTPARAMS_LIB_KERNELINFO_H                                                                                                                                           // Colorize: green
