#ifndef COM_NGOS_SHARED_COMMON_BOOTPARAMS_UEFIINFO_H                                                                                                                                                     // Colorize: green
#define COM_NGOS_SHARED_COMMON_BOOTPARAMS_UEFIINFO_H                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/bootparams/uefimemorymapinfo.h>                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/uefi/uefisystemtable.h>                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct UefiInfo                                                                                                                                                                                          // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    UefiMemoryMapInfo  memoryMap;                                                                                                                                                                        // Colorize: green
    UefiSystemTable   *systemTable;                                                                                                                                                                      // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_BOOTPARAMS_UEFIINFO_H                                                                                                                                                   // Colorize: green
