#ifndef CONFIGURE_SRC_COM_NGOS_CONFIGURE_OTHER_CONFIGUREDEFINES_H
#define CONFIGURE_SRC_COM_NGOS_CONFIGURE_OTHER_CONFIGUREDEFINES_H



#include <com/ngos/shared/common/page/macros.h>



#define BOOT_STACK_SIZE         (12 * PAGE_SIZE)
#define BOOT_PAGE_TABLE_SIZE    (12 * PAGE_SIZE)



#endif // CONFIGURE_SRC_COM_NGOS_CONFIGURE_OTHER_CONFIGUREDEFINES_H
