#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIBIOSENTRY_H                                                                                                                                                  // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIBIOSENTRY_H                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmientryheader.h>                                                                                                                                               // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmistringid.h>                                                                                                                                                  // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmibioscharacteristicsbiosreservedflags.h>                                                                                                            // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmibioscharacteristicsflags.h>                                                                                                                        // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmibioscharacteristicssystemreservedflags.h>                                                                                                          // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmibiosextendedromsize.h>                                                                                                                             // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmibiosromsize.h>                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with DmiSpecVerifier [BEGIN] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
#define DMI_BIOS_BIOS_ROM_SIZE_NEED_TO_EXTEND                             0xFF                                                                                                                           // Colorize: green
#define DMI_BIOS_SYSTEM_BIOS_MAJOR_RELEASE_NOT_AVAILABLE                  0xFF                                                                                                                           // Colorize: green
#define DMI_BIOS_SYSTEM_BIOS_MINOR_RELEASE_NOT_AVAILABLE                  0xFF                                                                                                                           // Colorize: green
#define DMI_BIOS_EMBEDDED_CONTROLLER_FIRMWARE_MAJOR_RELEASE_NOT_AVAILABLE 0xFF                                                                                                                           // Colorize: green
#define DMI_BIOS_EMBEDDED_CONTROLLER_FIRMWARE_MINOR_RELEASE_NOT_AVAILABLE 0xFF                                                                                                                           // Colorize: green
// Verified with DmiSpecVerifier [END] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with DmiSpecVerifier [BEGIN] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
struct DmiBiosEntry                                                                                                                                                                                      // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiEntryHeader              header;                                                                                                                                                                  // Colorize: green
    DmiStringId                 vendor;                     // String number of the BIOS Vendor's Name.                                                                                                  // Colorize: green
    DmiStringId                 biosVersion;                // String number of the BIOS Version. This value is a free-form string that may contain Core and OEM version information.                    // Colorize: green
    good_U16                    biosStartingAddressSegment; // Segment location of BIOS starting address (for example, 0E800h). NOTE: The size of the runtime BIOS image can be computed by subtracting the Starting Address Segment from 10000h and multiplying the result by 16. // Colorize: green
    DmiStringId                 biosReleaseDate;            // String number of the BIOS release date. The date string, if supplied, is in either mm/dd/yy or mm/dd/yyyy format. If the year portion of the string is two digits, the year is assumed to be 19yy. NOTE: The mm/dd/yyyy format is required for SMBIOS version 2.3 and later. // Colorize: green
    DmiBiosRomSize              biosRomSize;                // Size (n) where 64K * (n+1) is the size of the physical device containing the BIOS, in bytes. FFh - size is 16MB or greater, see Extended BIOS ROM Size for actual size // Colorize: green
    DmiBiosCharacteristicsFlags biosCharacteristics;        // Defines which functions the BIOS supports: PCI, PCMCIA, Flash, etc. (see 7.1.1).                                                          // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiBiosEntryV21: public DmiBiosEntry                                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiBiosCharacteristicsBiosReservedFlags biosCharacteristicsExtensionBiosReserved; // Optional space reserved for future supported functions. The number of Extension Bytes that is present is indicated by the Length in offset 1 minus 12h. See 7.1.2 for extensions defined for version 2.1 and later implementations. For version 2.4 and later implementations, two BIOS Characteristics Extension Bytes are defined (12-13h) and bytes 14-17h are also defined. // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiBiosEntryV23: public DmiBiosEntryV21                                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiBiosCharacteristicsSystemReservedFlags biosCharacteristicsExtensionSystemReserved; // Optional space reserved for future supported functions. The number of Extension Bytes that is present is indicated by the Length in offset 1 minus 12h. See 7.1.2 for extensions defined for version 2.1 and later implementations. For version 2.4 and later implementations, two BIOS Characteristics Extension Bytes are defined (12-13h) and bytes 14-17h are also defined. // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiBiosEntryV24: public DmiBiosEntryV23                                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    good_U8 systemBiosMajorRelease;                 // Identifies the major release of the System BIOS; for example, the value is 0Ah for revision 10.22 and 02h for revision 2.1. This field or the System BIOS Minor Release field or both are updated each time a System BIOS update for a given system is released. If the system does not support the use of this field, the value is 0FFh for both this field and the System BIOS Minor Release field. // Colorize: green
    good_U8 systemBiosMinorRelease;                 // Identifies the minor release of the System BIOS; for example, the value is 16h for revision 10.22 and 01h for revision 2.1.                       // Colorize: green
    good_U8 embeddedControllerFirmwareMajorRelease; // Identifies the major release of the embedded controller firmware; for example, the value would be 0Ah for revision 10.22 and 02h for revision 2.1. This field or the Embedded Controller Firmware Minor Release field or both are updated each time an embedded controller firmware update for a given system is released. If the system does not have field upgradeable embedded controller firmware, the value is 0FFh. // Colorize: green
    good_U8 embeddedControllerFirmwareMinorRelease; // Identifies the minor release of the embedded controller firmware; for example, the value is 16h for revision 10.22 and 01h for revision 2.1. If the system does not have field upgradeable embedded controller firmware, the value is 0FFh. // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiBiosEntryV31: public DmiBiosEntryV24                                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiBiosExtendedRomSize extendedBiosRomSize; // Extended size of the physical device(s) containing the BIOS, rounded up if needed. Bits 15:14  Unit 00b - megabytes 01b - gigabytes 10b - reserved 11b - reserved  Bits 13:0  Size  Examples: a 16 MB device would be represented as 0010h. A 48 GB device set would be represented as 0100_0000_0011_0000b or 4030h. // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
// Verified with DmiSpecVerifier [END] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIBIOSENTRY_H                                                                                                                                                // Colorize: green
