#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIMEMORYDEVICEMAPPEDADDRESSENTRY_H                                                                                                                             // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIMEMORYDEVICEMAPPEDADDRESSENTRY_H                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmientryheader.h>                                                                                                                                               // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydevicemappedaddressrange.h>                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_STARTING_ADDRESS_NEED_TO_EXTEND        0xFFFFFFFF                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_ENDING_ADDRESS_NEED_TO_EXTEND          0xFFFFFFFF                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_PARTITION_ROW_POSITION_UNKNOWN         0xFF                                                                                                                     // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_INTERLEAVE_POSITION_NON_INTERLEAVED    0x00                                                                                                                     // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_INTERLEAVE_POSITION_UNKNOWN            0xFF                                                                                                                     // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_INTERLEAVED_DATA_DEPTH_NON_INTERLEAVED 0x00                                                                                                                     // Colorize: green
#define DMI_MEMORY_DEVICE_MAPPED_ADDRESS_INTERLEAVED_DATA_DEPTH_UNKNOWN         0xFF                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceMappedAddressEntry                                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiEntryHeader                    header;                                                                                                                                                            // Colorize: green
    DmiMemoryDeviceMappedAddressRange startingAddress;                                                                                                                                                   // Colorize: green
    DmiMemoryDeviceMappedAddressRange endingAddress;                                                                                                                                                     // Colorize: green
    u16                               memoryDeviceHandle;                                                                                                                                                // Colorize: green
    u16                               memoryArrayMappedAddressHandle;                                                                                                                                    // Colorize: green
    u8                                partitionRowPosition;                                                                                                                                              // Colorize: green
    u8                                interleavePosition;                                                                                                                                                // Colorize: green
    u8                                interleavedDataDepth;                                                                                                                                              // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceMappedAddressEntryV27: public DmiMemoryDeviceMappedAddressEntry                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    u64 extendedStartingAddress;                                                                                                                                                                         // Colorize: green
    u64 extendedEndingAddress;                                                                                                                                                                           // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIMEMORYDEVICEMAPPEDADDRESSENTRY_H                                                                                                                           // Colorize: green
