#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIMEMORYDEVICEENTRY_H                                                                                                                                          // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIMEMORYDEVICEENTRY_H                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmientryheader.h>                                                                                                                                               // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmistringid.h>                                                                                                                                                  // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydeviceattributes.h>                                                                                                                          // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydeviceextendedsize.h>                                                                                                                        // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydeviceformfactor.h>                                                                                                                          // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydeviceoperatingmodecapabilityflags.h>                                                                                                        // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydevicesize.h>                                                                                                                                // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydevicetechnology.h>                                                                                                                          // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydevicetype.h>                                                                                                                                // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydevicetypedetailflags.h>                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define DMI_MEMORY_DEVICE_MEMORY_ERROR_INFORMATION_HANDLE_NOT_AVAILABLE 0xFFFE                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_MEMORY_ERROR_INFORMATION_HANDLE_NO_ERROR      0xFFFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_TOTAL_WIDTH_UNKNOWN                           0xFFFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_DATA_WIDTH_UNKNOWN                            0xFFFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_SIZE_NOT_INSTALLED                            0x0000                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_SIZE_UNKNOWN                                  0xFFFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_SIZE_NEED_TO_EXTEND                           0x7FFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_DEVICE_SET_NO_SET                             0x00                                                                                                                             // Colorize: green
#define DMI_MEMORY_DEVICE_DEVICE_SET_UNKNOWN                            0xFF                                                                                                                             // Colorize: green
#define DMI_MEMORY_DEVICE_SPEED_UNKNOWN                                 0x0000                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_SPEED_NEED_TO_EXTEND                          0xFFFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_RANK_UNKNOWN                                  0                                                                                                                                // Colorize: green
#define DMI_MEMORY_DEVICE_CONFIGURED_MEMORY_SPEED_UNKNOWN               0x0000                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_CONFIGURED_MEMORY_SPEED_NEED_TO_EXTEND        0xFFFF                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_MINIMUM_VOLTAGE_UNKNOWN                       0x0000                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_MAXIMUM_VOLTAGE_UNKNOWN                       0x0000                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_CONFIGURED_VOLTAGE_UNKNOWN                    0x0000                                                                                                                           // Colorize: green
#define DMI_MEMORY_DEVICE_NON_VOLATILE_SIZE_NOT_AVAILABLE               0x0000000000000000                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_NON_VOLATILE_SIZE_UNKNOWN                     0xFFFFFFFFFFFFFFFF                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_VOLATILE_SIZE_NOT_AVAILABLE                   0x0000000000000000                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_VOLATILE_SIZE_UNKNOWN                         0xFFFFFFFFFFFFFFFF                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_CACHE_SIZE_NOT_AVAILABLE                      0x0000000000000000                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_CACHE_SIZE_UNKNOWN                            0xFFFFFFFFFFFFFFFF                                                                                                               // Colorize: green
#define DMI_MEMORY_DEVICE_LOGICAL_SIZE_UNKNOWN                          0xFFFFFFFFFFFFFFFF                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntry                                                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiEntryHeader                 header;                                                                                                                                                               // Colorize: green
    u16                            memoryArrayHandle;                                                                                                                                                    // Colorize: green
    u16                            memoryErrorInformationHandle;                                                                                                                                         // Colorize: green
    u16                            totalWidth;                                                                                                                                                           // Colorize: green
    u16                            dataWidth;                                                                                                                                                            // Colorize: green
    DmiMemoryDeviceSize            size;                                                                                                                                                                 // Colorize: green
    DmiMemoryDeviceFormFactor      formFactor;                                                                                                                                                           // Colorize: green
    u8                             deviceSet;                                                                                                                                                            // Colorize: green
    DmiStringId                    deviceLocator;                                                                                                                                                        // Colorize: green
    DmiStringId                    bankLocator;                                                                                                                                                          // Colorize: green
    DmiMemoryDeviceType            memoryType;                                                                                                                                                           // Colorize: green
    DmiMemoryDeviceTypeDetailFlags typeDetail;                                                                                                                                                           // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntryV23: public DmiMemoryDeviceEntry                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    u16         speed;                                                                                                                                                                                   // Colorize: green
    DmiStringId manufacturer;                                                                                                                                                                            // Colorize: green
    DmiStringId serialNumber;                                                                                                                                                                            // Colorize: green
    DmiStringId assetTag;                                                                                                                                                                                // Colorize: green
    DmiStringId partNumber;                                                                                                                                                                              // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntryV26: public DmiMemoryDeviceEntryV23                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiMemoryDeviceAttributes attributes;                                                                                                                                                                // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntryV27: public DmiMemoryDeviceEntryV26                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiMemoryDeviceExtendedSize extendedSize;                                                                                                                                                            // Colorize: green
    u16                         configuredMemorySpeed;                                                                                                                                                   // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntryV28: public DmiMemoryDeviceEntryV27                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    u16 minimumVoltage;                                                                                                                                                                                  // Colorize: green
    u16 maximumVoltage;                                                                                                                                                                                  // Colorize: green
    u16 configuredVoltage;                                                                                                                                                                               // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntryV32: public DmiMemoryDeviceEntryV28                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiMemoryDeviceTechnology                   memoryTechnology;                                                                                                                                        // Colorize: green
    DmiMemoryDeviceOperatingModeCapabilityFlags memoryOperatingModeCapability;                                                                                                                           // Colorize: green
    DmiStringId                                 firmwareVersion;                                                                                                                                         // Colorize: green
    u16                                         moduleManufacturerID;                                                                                                                                    // Colorize: green
    u16                                         moduleProductID;                                                                                                                                         // Colorize: green
    u16                                         memorySubsystemControllerManufacturerID;                                                                                                                 // Colorize: green
    u16                                         memorySubsystemControllerProductID;                                                                                                                      // Colorize: green
    u64                                         nonVolatileSize;                                                                                                                                         // Colorize: green
    u64                                         volatileSize;                                                                                                                                            // Colorize: green
    u64                                         cacheSize;                                                                                                                                               // Colorize: green
    u64                                         logicalSize;                                                                                                                                             // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceEntryV33: public DmiMemoryDeviceEntryV32                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    u32 extendedSpeed;                                                                                                                                                                                   // Colorize: green
    u32 extendedConfiguredMemorySpeed;                                                                                                                                                                   // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIMEMORYDEVICEENTRY_H                                                                                                                                        // Colorize: green
