#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIONBOARDDEVICESENTRY_H                                                                                                                                        // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIONBOARDDEVICESENTRY_H                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmientryheader.h>                                                                                                                                               // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmionboarddevicesdevice.h>                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiOnboardDevicesEntry                                                                                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiEntryHeader          header;                                                                                                                                                                      // Colorize: green
    DmiOnboardDevicesDevice devices[0];                                                                                                                                                                  // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIONBOARDDEVICESENTRY_H                                                                                                                                      // Colorize: green
