#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIPROCESSORENTRY_H                                                                                                                                             // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIPROCESSORENTRY_H                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmientryheader.h>                                                                                                                                               // Colorize: green
#include <com/ngos/shared/common/dmi/lib/dmistringid.h>                                                                                                                                                  // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorcharacteristicsflags.h>                                                                                                                   // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorfamily.h>                                                                                                                                 // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorfamily2.h>                                                                                                                                // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorid.h>                                                                                                                                     // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorstatusandsocketpopulated.h>                                                                                                               // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessortype.h>                                                                                                                                   // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorupgrade.h>                                                                                                                                // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorvoltage.h>                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with DmiSpecVerifier [BEGIN] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
#define DMI_PROCESSOR_EXTERNAL_CLOCK_UNKNOWN            0x0000                                                                                                                                           // Colorize: green
#define DMI_PROCESSOR_MAX_SPEED_UNKNOWN                 0x0000                                                                                                                                           // Colorize: green
#define DMI_PROCESSOR_CURRENT_SPEED_UNKNOWN             0x0000                                                                                                                                           // Colorize: green
#define DMI_PROCESSOR_L1_CACHE_HANDLE_NOT_AVAILABLE     0xFFFF                                                                                                                                           // Colorize: green
#define DMI_PROCESSOR_L2_CACHE_HANDLE_NOT_AVAILABLE     0xFFFF                                                                                                                                           // Colorize: green
#define DMI_PROCESSOR_L3_CACHE_HANDLE_NOT_AVAILABLE     0xFFFF                                                                                                                                           // Colorize: green
#define DMI_PROCESSOR_CORE_COUNT_UNKNOWN                0x00                                                                                                                                             // Colorize: green
#define DMI_PROCESSOR_CORE_COUNT_NEED_TO_EXTEND         0xFF                                                                                                                                             // Colorize: green
#define DMI_PROCESSOR_ENABLED_CORE_COUNT_UNKNOWN        0x00                                                                                                                                             // Colorize: green
#define DMI_PROCESSOR_ENABLED_CORE_COUNT_NEED_TO_EXTEND 0xFF                                                                                                                                             // Colorize: green
#define DMI_PROCESSOR_THREAD_COUNT_UNKNOWN              0x00                                                                                                                                             // Colorize: green
#define DMI_PROCESSOR_THREAD_COUNT_NEED_TO_EXTEND       0xFF                                                                                                                                             // Colorize: green
// Verified with DmiSpecVerifier [END] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with DmiSpecVerifier [BEGIN] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
struct DmiProcessorEntry                                                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiEntryHeader                       header;                                                                                                                                                         // Colorize: green
    DmiStringId                          socketDesignation;                 // String number for Reference Designation EXAMPLE: 'J202',0                                                                 // Colorize: green
    DmiProcessorType                     processorType;                     // See 7.5.1.                                                                                                                // Colorize: green
    DmiProcessorFamily                   processorFamily;                   // See 7.5.2.                                                                                                                // Colorize: green
    DmiStringId                          processorManufacturer;             // String number of Processor Manufacturer                                                                                   // Colorize: green
    DmiProcessorId                       processorId;                       // Raw processor identification data See 7.5.3 for details.                                                                  // Colorize: green
    DmiStringId                          processorVersion;                  // String number describing the Processor                                                                                    // Colorize: green
    DmiProcessorVoltage                  voltage;                           // See 7.5.4.                                                                                                                // Colorize: green
    good_U16                             externalClock;                     // External Clock Frequency, in MHz If the value is unknown, the field is set to 0.                                          // Colorize: green
    good_U16                             maxSpeed;                          // Maximum processor speed (in MHz) supported by the system for this processor socket 0E9h is for a 233 MHz processor. If the value is unknown, the field is set to 0. NOTE: This field identifies a capability for the system, not the processor itself. // Colorize: green
    good_U16                             currentSpeed;                      // Same format as Max Speed NOTE: This field identifies the processor's speed at system boot; the processor may support more than one speed. // Colorize: green
    DmiProcessorStatusAndSocketPopulated processorStatusAndSocketPopulated; // Bit 7  Reserved, must be zero  Bit 6  CPU Socket Populated 1 - CPU Socket Populated 0 - CPU Socket Unpopulated  Bits 5:3 Reserved, must be zero Bits 2:0 CPU Status 0h - Unknown 1h - CPU Enabled 2h - CPU Disabled by User through BIOS Setup 3h - CPU Disabled By BIOS (POST Error) 4h - CPU is Idle, waiting to be enabled. 5-6h - Reserved 7h - Other // Colorize: green
    DmiProcessorUpgrade                  processorUpgrade;                  // See 7.5.5.                                                                                                                // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiProcessorEntryV21: public DmiProcessorEntry                                                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    good_U16 l1CacheHandle; // Handle of a Cache Information structure that defines the attributes of the primary (Level 1) cache for this processor For version 2.1 and version 2.2 implementations, the value is 0FFFFh if the processor has no L1 cache. For version 2.3 and later implementations, the value is 0FFFFh if the Cache Information structure is not provided. [1] // Colorize: green
    good_U16 l2CacheHandle; // Handle of a Cache Information structure that defines the attributes of the secondary (Level 2) cache for this processor For version 2.1 and version 2.2 implementations, the value is 0FFFFh if the processor has no L2 cache. For version 2.3 and later implementations, the value is 0FFFFh if the Cache Information structure is not provided. [1] // Colorize: green
    good_U16 l3CacheHandle; // Handle of a Cache Information structure that defines the attributes of the tertiary (Level 3) cache for this processor For version 2.1 and version 2.2 implementations, the value is 0FFFFh if the processor has no L3 cache. For version 2.3 and later implementations, the value is 0FFFFh if the Cache Information structure is not provided. [1] // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiProcessorEntryV23: public DmiProcessorEntryV21                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiStringId serialNumber; // String number for the serial number of this processor This value is set by the manufacturer and normally not changeable.                                                // Colorize: green
    DmiStringId assetTag;     // String number for the asset tag of this processor                                                                                                                       // Colorize: green
    DmiStringId partNumber;   // String number for the part number of this processor This value is set by the manufacturer and normally not changeable.                                                  // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiProcessorEntryV25: public DmiProcessorEntryV23                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    good_U8                          coreCount;                // Number of cores per processor socket See 7.5.6. If the value is unknown, the field is set to 0. For core counts of 256 or greater, the Core Count field is set to FFh and the Core Count 2 field is set to the number of cores. // Colorize: green
    good_U8                          enabledCoreCount;         // Number of enabled cores per processor socket See 7.5.7. If the value is unknown, the field is set 0. For core counts of 256 or greater, the Core Enabled field is set to FFh and the Core Enabled 2 field is set to the number of enabled cores. // Colorize: green
    good_U8                          threadCount;              // Number of threads per processor socket See 7.5.8. If the value is unknown, the field is set to 0. For thread counts of 256 or greater, the Thread Count field is set to FFh and the Thread Count 2 field is set to the number of threads. // Colorize: green
    DmiProcessorCharacteristicsFlags processorCharacteristics; // Defines which functions the processor supports See 7.5.9.                                                                              // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiProcessorEntryV26: public DmiProcessorEntryV25                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    DmiProcessorFamily2 processorFamily2; // See 7.5.2.                                                                                                                                                  // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiProcessorEntryV30: public DmiProcessorEntryV26                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    good_U16 coreCount2;        // Number of Cores per processor socket. Supports core counts >255. If this field is present, it holds the core count for the processor socket. Core Count will also hold the core count, except for core counts that are 256 or greater. In that case, Core Count shall be set to FFh and Core Count 2 will hold the count.. See 7.5.6. Legal values: 0000h = unknown 0001h-00FFh = core counts 1 to 255. Matches Core Count value. 0100h-FFFEh = Core counts 256 to 65534, respectively. FFFFh = reserved. // Colorize: green
    good_U16 enabledCoreCount2; // Number of enabled cores per processor socket. Supports core enabled counts >255. If this field is present, it holds the core enabled count for the processor socket. Core Enabled will also hold the core enabled count, except for core counts that are 256 or greater. In that case, Core Enabled shall be set to FFh and Core Enabled 2 will hold the count. See 7.5.7. Legal values: 0000h = unknown 0001h-00FFh = core enabled counts 1 to 255. Matches Core Enabled value. 0100h-FFFEh = core enabled counts 256 to 65534, respectively. FFFFh = reserved. // Colorize: green
    good_U16 threadCount2;      // Number of threads per processor socket. Supports thread counts >255. If this field is present, it holds the thread count for the processor socket. Thread Count will also hold the thread count, except for thread counts that are 256 or greater. In that case, Thread Count shall be set to FFh and Thread Count 2 will hold the count. See 7.5.8. Legal values:0000h = unknown 0001h-00FFh = thread counts 1 to 255. Matches Thread Count value. 0100h-FFFEh = thread counts 256 to 65534, respectively. FFFFh = reserved.  [1]  Beginning with version 2.3 implementations, if the Cache Handle is 0FFFFh, management software must make no assumptions about the cache's attributes and should report all cache-related attributes as unknown. The definitive absence of a specific cache is identified by referencing a Cache Information structure and setting that structure's Installed Size field to 0. // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
// Verified with DmiSpecVerifier [END] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMIPROCESSORENTRY_H                                                                                                                                           // Colorize: green
