#ifndef COM_NGOS_DEVTOOLS_IMAGE_BUILDER_PE_PEHEADER_H                                                                                                                                                    // Colorize: green
#define COM_NGOS_DEVTOOLS_IMAGE_BUILDER_PE_PEHEADER_H                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <Qt>                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/image_builder/other/section.h>                                                                                                                                               // Colorize: green
#include <com/ngos/devtools/image_builder/pe/coffheader.h>                                                                                                                                               // Colorize: green
#include <com/ngos/devtools/image_builder/pe/sectionheader.h>                                                                                                                                       // Colorize: green
#include <com/ngos/devtools/image_builder/pe/peoptionalheader.h>                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define PE_HEADER_SIGNATURE 0x00004550 // PE\0\0                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct PEHeader                                                                                                                                                                                          // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    void print(); // TEST: NO                                                                                                                                                                            // Colorize: green
    bool verify(); // TEST: NO                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    quint32          signature;                                                                                                                                                                        // Colorize: green
    COFFHeader       coffHeader;                                                                                                                                                                       // Colorize: green
    PeOptionalHeader optionalHeader;                                                                                                                                                                        // Colorize: green
    SectionHeader    sections[(quint64)Section::MAXIMUM];                                                                                                                                              // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_IMAGE_BUILDER_PE_PEHEADER_H                                                                                                                                                  // Colorize: green
