#ifndef COM_NGOS_DEVTOOLS_IMAGE_BUILDER_PE_SECTIONHEADER_H                                                                                                                                          // Colorize: green
#define COM_NGOS_DEVTOOLS_IMAGE_BUILDER_PE_SECTIONHEADER_H                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <Qt>                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/image_builder/other/sectionheadercharacteristicsflags.h>                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with PeSpecVerifier [BEGIN] // https://docs.microsoft.com/en-us/windows/win32/debug/pe-format                                                                                                // Colorize: green
struct SectionHeader                                                                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    void print(); // TEST: NO                                                                                                                                                                            // Colorize: green
    bool verify(); // TEST: NO                                                                                                                                                                           // Colorize: green
    bool verifySection(SectionHeaderCharacteristicsFlags expectedCharacteristics); // TEST: NO                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    char                              name[8];              // An 8-byte, null-padded UTF-8 encoded string. If the string is exactly 8 characters long, there is no terminating null. For longer names, this field contains a slash (/) that is followed by an ASCII representation of a decimal number that is an offset into the string table. Executable images do not use a string table and do not support section names longer than 8 characters. Long names in object files are truncated if they are emitted to an executable file. // Colorize: green
    quint32                           virtualSize;          // The total size of the section when loaded into memory. If this value is greater than SizeOfRawData, the section is zero-padded. This field is valid only for executable images and should be set to zero for object files. // Colorize: green
    quint32                           virtualAddress;       // For executable images, the address of the first byte of the section relative to the image base when the section is loaded into memory. For object files, this field is the address of the first byte before relocation is applied; for simplicity, compilers should set this to zero. Otherwise, it is an arbitrary value that is subtracted from offsets during relocation. // Colorize: green
    quint32                           sizeOfRawData;        // The size of the section (for object files) or the size of the initialized data on disk (for image files). For executable images, this must be a multiple of FileAlignment from the optional header. If this is less than VirtualSize, the remainder of the section is zero-filled. Because the SizeOfRawData field is rounded but the VirtualSize field is not, it is possible for SizeOfRawData to be greater than VirtualSize as well. When a section contains only uninitialized data, this field should be zero. // Colorize: green
    quint32                           pointerToRawData;     // The file pointer to the first page of the section within the COFF file. For executable images, this must be a multiple of FileAlignment from the optional header. For object files, the value should be aligned on a 4-byte boundary for best performance. When a section contains only uninitialized data, this field should be zero. // Colorize: green
    quint32                           pointerToRelocations; // The file pointer to the beginning of relocation entries for the section. This is set to zero for executable images or if there are no relocations. // Colorize: green
    quint32                           pointerToLinenumbers; // The file pointer to the beginning of line-number entries for the section. This is set to zero if there are no COFF line numbers. This value should be zero for an image because COFF debugging information is deprecated. // Colorize: green
    quint16                           numberOfRelocations;  // The number of relocation entries for the section. This is set to zero for executable images.                                              // Colorize: green
    quint16                           numberOfLineNumbers;  // The number of line-number entries for the section. This value should be zero for an image because COFF debugging information is deprecated. // Colorize: green
    SectionHeaderCharacteristicsFlags characteristics;      // The flags that describe the characteristics of the section. For more information, see <a href="#section-flags" data-linktype="self-bookmark">Section Flags</a>. // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
// Verified with PeSpecVerifier [END] // https://docs.microsoft.com/en-us/windows/win32/debug/pe-format                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_IMAGE_BUILDER_PE_SECTIONHEADER_H                                                                                                                                        // Colorize: green
