#ifndef COM_NGOS_DEVTOOLS_SHARED_UTILS_GIT_H                                                                                                                                                             // Colorize: green
#define COM_NGOS_DEVTOOLS_SHARED_UTILS_GIT_H                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QString>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class GIT                                                                                                                                                                                                // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    static bool isIgnored(const QString &workingDirectory, const QString &path); // TEST: NO                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private:                                                                                                                                                                                                 // Colorize: green
    GIT(); // TEST: NO                                                                                                                                                                                   // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_SHARED_UTILS_GIT_H                                                                                                                                                           // Colorize: green
