#include "string.h"                                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <Qt>                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
char8* strapp(char8 *str1, const char8 *str2)                                                                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Q_ASSERT(str1  != nullptr);                                                                                                                                                                          // Colorize: green
    Q_ASSERT(str2  != nullptr);                                                                                                                                                                          // Colorize: green
    Q_ASSERT(*str1 == 0);                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    char8 *cur = str1;                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    do                                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        char8 ch = *str2;                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (ch == 0)                                                                                                                                                                                     // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            break;                                                                                                                                                                                       // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        *cur = ch;                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        ++cur;                                                                                                                                                                                           // Colorize: green
        ++str2;                                                                                                                                                                                          // Colorize: green
    } while(true);                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    *cur = 0;                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return cur;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
