#ifndef COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_CPUMODEL_H                                                                                                                                               // Colorize: green
#define COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_CPUMODEL_H                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QString>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct CpuModel                                                                                                                                                                                         // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    bool operator<(const CpuModel &another) const                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        // Compare family                                                                                                                                                                                // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (family < another.family)                                                                                                                                                                 // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                return true;                                                                                                                                                                             // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (family > another.family)                                                                                                                                                                 // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                return false;                                                                                                                                                                            // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Compare model                                                                                                                                                                                 // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (model < another.model)                                                                                                                                                                   // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                return true;                                                                                                                                                                             // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (model > another.model)                                                                                                                                                                   // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                return false;                                                                                                                                                                            // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Compare name                                                                                                                                                                                  // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (name < another.name)                                                                                                                                                                     // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                return true;                                                                                                                                                                             // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (name > another.name)                                                                                                                                                                     // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                return false;                                                                                                                                                                            // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        return false;                                                                                                                                                                                    // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString name;                                                                                                                                                                                        // Colorize: green
    quint8  family;                                                                                                                                                                                      // Colorize: green
    quint8  model;                                                                                                                                                                                       // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_CPUMODEL_H                                                                                                                                              // Colorize: green
