#ifndef COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_PCIBASECLASS_H                                                                                                                                            // Colorize: green
#define COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_PCIBASECLASS_H                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QMap>                                                                                                                                                                                          // Colorize: green
#include <QString>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_generator/other/pcisubclass.h>                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct PciBaseClass                                                                                                                                                                                      // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QString       description;                                                                                                                                                               // Colorize: green
    PciSubClasses subClasses;                                                                                                                     // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
typedef QMap<quint8,         PciBaseClass> PciBaseClasses;          // PCI Base Class ID => PCI Base Class                                                                                                 // Colorize: green
typedef QMapIterator<quint8, PciBaseClass> PciBaseClassesIterator;  // PCI Base Class ID => PCI Base Class                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_PCIBASECLASS_H                                                                                                                                          // Colorize: green
