#ifndef COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_PCISUBCLASS_H                                                                                                                                             // Colorize: green
#define COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_PCISUBCLASS_H                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QMap>                                                                                                                                                                                          // Colorize: green
#include <QString>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_generator/other/pciinterface.h>                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct PciSubClass                                                                                                                                                                                       // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QString                    description;                                                                                                                                                              // Colorize: green
    QMap<quint8, PciInterface> interfaces;  // PCI Interface ID => PCI Interface                                                                                                                         // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_CODE_GENERATOR_OTHER_PCISUBCLASS_H                                                                                                                                           // Colorize: green
