#ifndef COM_NGOS_SHARED_COMMON_MEMORY_MEMORY_H                                                                                                                                                           // Colorize: green
#define COM_NGOS_SHARED_COMMON_MEMORY_MEMORY_H                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/memory/asm_memcpy.h>                                                                                                                                                    // Colorize: green
#include <com/ngos/shared/common/memory/asm_memset.h>                                                                                                                                                    // Colorize: green
#include <com/ngos/shared/common/memory/asm_memzero.h>                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
good_I8 memcmp(const void *str1, const void *str2, good_I64 length);                                                                                                                                               // Colorize: green
bool memempty(const void *src, good_I64 length);                                                                                                                                                              // Colorize: green
void* memmove(void *dest, const void *src, good_I64 length);                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_MEMORY_MEMORY_H                                                                                                                                                         // Colorize: green
