#ifndef COM_NGOS_DEVTOOLS_BUILD_CONFIG_GUI_WIDGETS_PARAMETERS_BOOLEANPARAMETERWIDGET_H                                                                                                                   // Colorize: green
#define COM_NGOS_DEVTOOLS_BUILD_CONFIG_GUI_WIDGETS_PARAMETERS_BOOLEANPARAMETERWIDGET_H                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/build_config_gui/widgets/parameters/parameterwidget.h>                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/build_config_gui/widgets/common/trackingcheckbox.h>                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class BooleanParameterWidget: public ParameterWidget                                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Q_OBJECT                                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    explicit BooleanParameterWidget(const QString &id, const QHash<QString, QString> &metaInformation, QWidget *parent = nullptr); // TEST: NO                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    void setValue(const QString &value) override; // TEST: NO                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
protected:                                                                                                                                                                                               // Colorize: green
    QString generatePrivateDetails() override; // TEST: NO                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private slots:                                                                                                                                                                                           // Colorize: green
    void checkboxToggled(bool checked); // TEST: NO                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private:                                                                                                                                                                                                 // Colorize: green
    TrackingCheckBox *mCheckBox;                                                                                                                                                                         // Colorize: green
    QString           mTrueValue;                                                                                                                                                                        // Colorize: green
    QString           mFalseValue;                                                                                                                                                                       // Colorize: green
    QString           mTrueDescription;                                                                                                                                                                  // Colorize: green
    QString           mFalseDescription;                                                                                                                                                                 // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_BUILD_CONFIG_GUI_WIDGETS_PARAMETERS_BOOLEANPARAMETERWIDGET_H                                                                                                                 // Colorize: green
