#ifndef COM_NGOS_DEVTOOLS_BUILD_CONFIG_GUI_WIDGETS_PARAMETERS_PARAMETERWIDGET_H                                                                                                                          // Colorize: green
#define COM_NGOS_DEVTOOLS_BUILD_CONFIG_GUI_WIDGETS_PARAMETERS_PARAMETERWIDGET_H                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QWidget>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QHash>                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class ParameterWidget: public QWidget                                                                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Q_OBJECT                                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    explicit ParameterWidget(const QString &id, const QHash<QString, QString> &metaInformation, QWidget *parent = nullptr); // TEST: NO                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    virtual void setValue(const QString &value); // TEST: NO                                                                                                                                             // Colorize: green
    const QString& value() const; // TEST: NO                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    void reset(); // TEST: NO                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    void handleValueChanged(const QHash<QString, ParameterWidget *> &parameters); // TEST: NO                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
protected slots:                                                                                                                                                                                         // Colorize: green
    void widgetEntered(); // TEST: NO                                                                                                                                                                    // Colorize: green
    void widgetLeaved(); // TEST: NO                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
protected:                                                                                                                                                                                               // Colorize: green
    virtual QString generatePrivateDetails() = 0; // TEST: NO                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString mId;                                                                                                                                                                                         // Colorize: green
    QString mName;                                                                                                                                                                                       // Colorize: green
    QString mDescription;                                                                                                                                                                                // Colorize: green
    QString mEnabled;                                                                                                                                                                                    // Colorize: green
    QString mDefault;                                                                                                                                                                                    // Colorize: green
    QString mValue;                                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private:                                                                                                                                                                                                 // Colorize: green
    QString generateDetails(); // TEST: NO                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static ParameterWidget *sHoveredWidget;                                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
signals:                                                                                                                                                                                                 // Colorize: green
    void valueChanged(); // TEST: NO                                                                                                                                                                     // Colorize: green
    void detailsUpdated(const QString &details); // TEST: NO                                                                                                                                             // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_BUILD_CONFIG_GUI_WIDGETS_PARAMETERS_PARAMETERWIDGET_H                                                                                                                        // Colorize: green
