#ifndef COM_NGOS_DEVTOOLS_DOCS_VERIFIER_THREADS_DOCSWORKERTHREAD_H                                                                                                                                       // Colorize: green
#define COM_NGOS_DEVTOOLS_DOCS_VERIFIER_THREADS_DOCSWORKERTHREAD_H                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QThread>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QMutex>                                                                                                                                                                                        // Colorize: green
#include <QSemaphore>                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/docs_verifier/other/docsfileinfo.h>                                                                                                                                          // Colorize: green
#include <com/ngos/devtools/docs_verifier/other/docsmessageinfo.h>                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class DocsWorkerThread: public QThread                                                                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    DocsWorkerThread(); // TEST: NO                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static qint64 getAmountOfFiles(); // TEST: NO                                                                                                                                                        // Colorize: green
    static void pushFile(const QString &path, DocsVerificationFileType verificationFileType); // TEST: NO                                                                                                // Colorize: green
    static void pushFile(DocsFileInfo *fileInfo); // TEST: NO                                                                                                                                            // Colorize: green
    static DocsFileInfo* popFile(); // TEST: NO                                                                                                                                                          // Colorize: green
    static void noMoreFiles(); // TEST: NO                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    void addWarning(const QString &path, qint64 line, const QString &warning); // TEST: NO                                                                                                               // Colorize: green
    void addError(const QString &path, qint64 line, const QString &error); // TEST: NO                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    const QList<DocsMessageInfo>& getWarnings() const; // TEST: NO                                                                                                                                       // Colorize: green
    const QList<DocsMessageInfo>& getErrors() const; // TEST: NO                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
protected:                                                                                                                                                                                               // Colorize: green
    void run() override; // TEST: NO                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private:                                                                                                                                                                                                 // Colorize: green
    void processFile(DocsFileInfo *fileInfo); // TEST: NO                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static qint64                sAmountOfFiles;                                                                                                                                                         // Colorize: green
    static QList<DocsFileInfo *> sFiles;                                                                                                                                                                 // Colorize: green
    static QMutex                sFilesMutex;                                                                                                                                                            // Colorize: green
    static QSemaphore            sFilesSemaphore;                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<DocsMessageInfo> mWarnings;                                                                                                                                                                    // Colorize: green
    QList<DocsMessageInfo> mErrors;                                                                                                                                                                      // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_DOCS_VERIFIER_THREADS_DOCSWORKERTHREAD_H                                                                                                                                     // Colorize: green
