#ifndef COM_NGOS_SHARED_COMMON_FPU_LIB_REGISTERS_FPUCWR_H                                                                                                                                                // Colorize: green
#define COM_NGOS_SHARED_COMMON_FPU_LIB_REGISTERS_FPUCWR_H                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct FpuCwr                                                                                                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    union                                                                                                                                                                                                // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        struct                                                                                                                                                                                           // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            good_U16 invalidOperationErrorMask:    1;                                                                                                                                                    // Colorize: green
            good_U16 denormalizedOperandErrorMask: 1;                                                                                                                                                    // Colorize: green
            good_U16 divideByZeroErrorMask:        1;                                                                                                                                                    // Colorize: green
            good_U16 overflowErrorMask:            1;                                                                                                                                                    // Colorize: green
            good_U16 underflowErrorMask:           1;                                                                                                                                                    // Colorize: green
            good_U16 precisionErrorMask:           1;                                                                                                                                                    // Colorize: green
            good_U16 _reserved:                    2;                                                                                                                                                    // Colorize: green
            good_U16 precisionControl:             2;                                                                                                                                                    // Colorize: green
            good_U16 roundingControl:              2;                                                                                                                                                    // Colorize: green
            good_U16 infinityControl:              1;                                                                                                                                                    // Colorize: green
            good_U16 _reserved2:                   3;                                                                                                                                                    // Colorize: green
        };                                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        good_U16 value16;                                                                                                                                                                                // Colorize: green
    };                                                                                                                                                                                                   // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_FPU_LIB_REGISTERS_FPUCWR_H                                                                                                                                              // Colorize: green
