#include "x86featuresnamesgenerator.h"                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QFile>                                                                                                                                                                                         // Colorize: green
#include <QRegularExpression>                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/shared/console/console.h>                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define ORIGINAL_FILE_PATH "/src/os/shared/common/src/com/ngos/shared/common/cpu/lib/x86feature.h"                                                                                                       // Colorize: green
#define FILE_PATH_H        "/src/os/shared/common/src/com/ngos/shared/common/cpu/lib/generated/x86featuresnames.h"                                                                                       // Colorize: green
#define FILE_PATH_CPP      "/src/os/shared/common/src/com/ngos/shared/common/cpu/lib/generated/x86featuresnames.cpp"                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
X86FeaturesNamesGenerator::X86FeaturesNamesGenerator()                                                                                                                                                   // Colorize: green
    : CommonGenerator()                                                                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
bool X86FeaturesNamesGenerator::generate(const QString &path)                                                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return generateHFile(path) && generateCppFile(path);                                                                                                                                                 // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
bool X86FeaturesNamesGenerator::generateHFile(const QString &path)                                                                                                                                       // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QStringList lines;                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Add include lines                                                                                                                                                                                 // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        lines.append("#include <com/ngos/shared/common/cpu/lib/x86featureword.h>");                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        addThreeBlankLines(lines);                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    lines.append("extern const good_Char8* x86FeaturesNames[static_cast<good_Enum_t>(x86FeatureWord::MAXIMUM) * 32]; // x86FeaturesNames declared in x86featuresnames.cpp file");                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return save(path + FILE_PATH_H, lines);                                                                                                                                                              // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
bool X86FeaturesNamesGenerator::generateCppFile(const QString &path)                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QStringList originalLines;                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Read lines from original file                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QFile file(path + ORIGINAL_FILE_PATH);                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (!file.open(QIODevice::ReadOnly))                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            Console::err(QString("Failed to open file: %1")                                                                                                                                              // Colorize: green
                                    .arg(path + ORIGINAL_FILE_PATH)                                                                                                                                      // Colorize: green
            );                                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return false;                                                                                                                                                                                // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        originalLines = QString::fromUtf8(file.readAll()).split('\n');                                                                                                                                   // Colorize: green
        file.close();                                                                                                                                                                                    // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QStringList features;                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Parse features from original file                                                                                                                                                                 // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < originalLines.size(); ++i)                                                                                                                                                // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QString originalLine = originalLines.at(i).trimmed();                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (originalLine.contains("WORD_BIT("))                                                                                                                                                      // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                features.append(originalLine);                                                                                                                                                           // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QStringList lines;                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Add include lines                                                                                                                                                                                 // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        lines.append("#include \"x86featuresnames.h\"");                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        addThreeBlankLines(lines);                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    lines.append("const good_Char8* x86FeaturesNames[static_cast<good_Enum_t>(x86FeatureWord::MAXIMUM) * 32] =");                                                                                             // Colorize: green
    lines.append("{");                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Generate x86FeaturesNames content                                                                                                                                                                 // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QRegularExpression regexp("^ *(\\w+) *= *WORD_BIT\\(([\\w:]+), *(\\d+)\\),?(?: *\\/\\/[^\"]*\"([^\"]*)\")?.*$"); // XMM = WORD_BIT(x86FeatureWord::CPUID_00000001_EDX, 25), // "sse"             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        QStringList wordBlock;                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        quint64 currentWord     = 0;                                                                                                                                                                     // Colorize: green
        QString lastFeatureWord = "";                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (qint64 i = 0; i < features.size(); ++i)                                                                                                                                                     // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QString feature = features.at(i);                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            QRegularExpressionMatch match = regexp.match(feature);                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (!match.hasMatch())                                                                                                                                                                       // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                Console::err(QString("Feature declaration is invalid: %1")                                                                                                                               // Colorize: green
                                        .arg(feature)                                                                                                                                                    // Colorize: green
                );                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return false;                                                                                                                                                                            // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            QString featureName    = match.captured(1);                                                                                                                                                  // Colorize: green
            QString featureWord    = match.captured(2);                                                                                                                                                  // Colorize: green
            QString featureBit     = match.captured(3);                                                                                                                                                  // Colorize: green
            QString featureAltName = match.captured(4);                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            QString featureHumanName = featureName.toLower();                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            // Get feature human name                                                                                                                                                                    // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (!featureAltName.isNull())                                                                                                                                                            // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    featureHumanName = featureAltName;                                                                                                                                                   // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                else                                                                                                                                                                                     // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (featureHumanName.startsWith('_'))                                                                                                                                                // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        featureHumanName.remove(0, 1);                                                                                                                                                   // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            quint64 bit;                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            // Get feature bit                                                                                                                                                                           // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                bool ok;                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                bit = featureBit.toULongLong(&ok);                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (!ok)                                                                                                                                                                                 // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err(QString("Feature declaration is invalid: %1")                                                                                                                           // Colorize: green
                                            .arg(feature)                                                                                                                                                // Colorize: green
                    );                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return false;                                                                                                                                                                        // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (bit >= 32)                                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err(QString("bit is invalid for feature: %1")                                                                                                                               // Colorize: green
                                            .arg(feature)                                                                                                                                                // Colorize: green
                    );                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return false;                                                                                                                                                                        // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (featureWord != lastFeatureWord)                                                                                                                                                          // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (lastFeatureWord != "")                                                                                                                                                               // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    // Add word block to lines                                                                                                                                                           // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        if (currentWord > 0)                                                                                                                                                             // Colorize: green
                        {                                                                                                                                                                                // Colorize: green
                            lines.append("");                                                                                                                                                            // Colorize: green
                        }                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                        lines.append(QString("    // word %1")                                                                                                                                           // Colorize: green
                                                .arg(currentWord)                                                                                                                                        // Colorize: green
                        );                                                                                                                                                                               // Colorize: green
                        lines.append("");                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                        lines.append(wordBlock);                                                                                                                                                         // Colorize: green
                        ++currentWord;                                                                                                                                                                   // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                lastFeatureWord = featureWord;                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                // Fill word block with empty strings                                                                                                                                                    // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    wordBlock.clear();                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    for (qint64 i = 0; i < 32; ++i)                                                                                                                                                      // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        wordBlock.append(QString("    \"\", %1 // WORD_BIT(%2, %3)")                                                                                                                     // Colorize: green
                                                    .arg("", 20, QChar(' '))                                                                                                                             // Colorize: green
                                                    .arg(featureWord)                                                                                                                                    // Colorize: green
                                                    .arg(i)                                                                                                                                              // Colorize: green
                        );                                                                                                                                                                               // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            // Replace line in word block for specified bit                                                                                                                                              // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                wordBlock[bit] = QString("    \"%1\", %2 // WORD_BIT(%3, %4) %5 // X86Feature::%6")                                                                                                      // Colorize: green
                                            .arg(featureHumanName)                                                                                                                                       // Colorize: green
                                            .arg("", 20 - featureHumanName.length(), QChar(' '))                                                                                                         // Colorize: green
                                            .arg(featureWord)                                                                                                                                            // Colorize: green
                                            .arg(bit)                                                                                                                                                    // Colorize: green
                                            .arg("", 41 - featureWord.length() - (bit > 9 ? 1 : 0), QChar(' '))                                                                                                              // Colorize: green
                                            .arg(featureName);                                                                                                                                           // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        // Add word block to lines                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (currentWord > 0)                                                                                                                                                                         // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                lines.append("");                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            lines.append(QString("    // word %1")                                                                                                                                                       // Colorize: green
                                    .arg(currentWord)                                                                                                                                                    // Colorize: green
            );                                                                                                                                                                                           // Colorize: green
            lines.append("");                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            lines.append(wordBlock);                                                                                                                                                                     // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    lines.append("};");                                                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return save(path + FILE_PATH_CPP, lines);                                                                                                                                                            // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
X86FeaturesNamesGenerator x86FeaturesNamesGeneratorInstance;                                                                                                                                             // Colorize: green
