#ifndef DEVICEMANAGER_SRC_COM_NGOS_BOOTLOADER_TOOLS_DEVICEMANAGER_MAIN_DEVICEMANAGER_H
#define DEVICEMANAGER_SRC_COM_NGOS_BOOTLOADER_TOOLS_DEVICEMANAGER_MAIN_DEVICEMANAGER_H



#include <ngos/status.h>



class DeviceManager
{
public:
    static NgosStatus init(); // TEST: NO
};



#endif // DEVICEMANAGER_SRC_COM_NGOS_BOOTLOADER_TOOLS_DEVICEMANAGER_MAIN_DEVICEMANAGER_H
