#ifndef COM_NGOS_DEVTOOLS_USB_BOOT_MAKER_OTHER_DEFINES_H
#define COM_NGOS_DEVTOOLS_USB_BOOT_MAKER_OTHER_DEFINES_H



#define MIN_DISK_SIZE (8* 1024 * 1024)

#define MAX_GPT_PARTITIONS   128
#define DEFAULT_CLUSTER_SIZE 4096
#define SECTOR_SIZE          512

#define MBR_RESERVED 0x01B8



#endif // COM_NGOS_DEVTOOLS_USB_BOOT_MAKER_OTHER_DEFINES_H
