#ifndef COM_NGOS_DEVTOOLS_USB_BOOT_MAKER_OTHER_USBDEVICEINFO_H                                                                                                                                           // Colorize: green
#define COM_NGOS_DEVTOOLS_USB_BOOT_MAKER_OTHER_USBDEVICEINFO_H                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QString>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct UsbDeviceInfo                                                                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QString title;                                                                                                                                                                                       // Colorize: green
    qint64  diskSize;                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#ifdef Q_OS_WIN                                                                                                                                                                                          // Colorize: green
    QString letters;                                                                                                                                                                                     // Colorize: green
    qint64  diskNumber;                                                                                                                                                                                  // Colorize: green
#else                                                                                                                                                                                                    // Colorize: green
    QString deviceName;                                                                                                                                                                                  // Colorize: green
#endif                                                                                                                                                                                                   // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
Q_DECLARE_METATYPE(UsbDeviceInfo *); // TEST: NO                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_USB_BOOT_MAKER_OTHER_USBDEVICEINFO_H                                                                                                                                         // Colorize: green
