#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
namespace __cxxabiv1                                                                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class __si_class_type_info                                                                                                                                                                               // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    virtual void dummy(); // TEST: NO // TODO: Need to check with objdump                                                                                                                                // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class __class_type_info                                                                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    virtual void dummy(); // TEST: NO // TODO: Need to check with objdump                                                                                                                                // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class __vmi_class_type_info                                                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    virtual void dummy(); // TEST: NO // TODO: Need to check with objdump                                                                                                                                // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void __si_class_type_info::dummy()                                                                                                                                                                       // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    COMMON_LT((""));                                                                                                                                                                                     // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void __class_type_info::dummy()                                                                                                                                                                          // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    COMMON_LT((""));                                                                                                                                                                                     // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void __vmi_class_type_info::dummy()                                                                                                                                                                      // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    COMMON_LT((""));                                                                                                                                                                                     // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
