#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_IOREMAP_MACROS_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_IOREMAP_MACROS_H



#include <kernelbase/src/bits64/other/ioremap/fixmap.h>
#include <ngos/utils.h>
#include <pagetable/macros.h>



#define FIX_BITMAP_SLOTS      8
#define NUMBER_OF_FIX_BITMAPS 64
#define TOTAL_FIX_BITMAPS     (FIX_BITMAP_SLOTS * NUMBER_OF_FIX_BITMAPS)

#define FIX_ADDRESS_BOTTOM 0xFFFFFFFFFF200000
#define FIX_ADDRESS_TOP    0xFFFFFFFFFF3FF000
#define FIX_BITMAP_END     ROUND_UP((u64)FixMap::END, PTRS_PER_PTE)
#define FIX_BITMAP_BEGIN   FIX_BITMAP_END + TOTAL_FIX_BITMAPS - 1



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_IOREMAP_MACROS_H
