#include "phpsinglelineforverifier.h"                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_verifier/other/codeverificationfiletype.h>                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
PhpSingleLineForVerifier::PhpSingleLineForVerifier()                                                                                                                                                     // Colorize: green
    : BaseCodeVerifier(CodeVerificationFileType::PHP)                                                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void PhpSingleLineForVerifier::verify(CodeWorkerThread *worker, const QString &path, const QString &/*content*/, const QStringList &lines)                                                               // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    for (qint64 i = 0; i < lines.size(); ++i)                                                                                                                                                            // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QString line = lines.at(i);                                                                                                                                                                      // Colorize: green
        VERIFIER_IGNORE(line, "// Ignore PhpSingleLineForVerifier");                                                                                                                                     // Colorize: green
        removeComments(line);                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        QString lineTrimmed = line.trimmed();                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (lineTrimmed.startsWith("for ("))                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (lineTrimmed == "for (")                                                                                                                                                                  // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                QString spaces = line.left(line.indexOf("for ("));                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                do                                                                                                                                                                                       // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    ++i;                                                                                                                                                                                 // Colorize: green
                } while(i < lines.size() && lines.at(i) != spaces + "    )");                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (                                                                                                                                                                                     // Colorize: green
                    i >= lines.size() - 1                                                                                                                                                                // Colorize: green
                    ||                                                                                                                                                                                   // Colorize: green
                    lines.at(i + 1) != spaces + '{'                                                                                                                                                      // Colorize: green
                   )                                                                                                                                                                                     // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    worker->addError(path, i, "Single line for statement is prohibited");                                                                                                                // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (lineTrimmed.endsWith(')'))                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    QString spaces = line.left(line.indexOf("for ("));                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    if (                                                                                                                                                                                 // Colorize: green
                        i >= lines.size() - 1                                                                                                                                                            // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        lines.at(i + 1) != spaces + '{'                                                                                                                                                  // Colorize: green
                       )                                                                                                                                                                                 // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        worker->addError(path, i, "Single line for statement is prohibited");                                                                                                            // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                else                                                                                                                                                                                     // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    worker->addError(path, i, "Single line for statement is prohibited");                                                                                                                // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
PhpSingleLineForVerifier phpSingleLineForVerifierInstance;                                                                                                                                               // Colorize: green
