#include <QCoreApplication>                                                                                                                                                                              // Colorize: green
#include <QDateTime>                                                                                                                                                                                     // Colorize: green
#include <QDir>                                                                                                                                                                                          // Colorize: green
#include <QFileInfo>                                                                                                                                                                                     // Colorize: green
#include <QList>                                                                                                                                                                                         // Colorize: green
#include <QProcess>                                                                                                                                                                                      // Colorize: green
#include <QQueue>                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/shared/console/console.h>                                                                                                                                                    // Colorize: green
#include <com/ngos/devtools/shared/utils/git.h>                                                                                                                                                          // Colorize: green
#include <com/ngos/devtools/tests_verifier/threads/testverifythread.h>                                                                                                                                    // Colorize: green
#include <com/ngos/devtools/tests_verifier/threads/testworkerthread.h>                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void usage()                                                                                                                                                                                             // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Ignore CppAlignmentVerifier [BEGIN]                                                                                                                                                               // Colorize: green
    Console::err(                                                                                                                                                                                        // Colorize: green
                "Usage: tests_verifier PATH\n"                                                                                                                                                            // Colorize: green
                "    * PATH - path to folder"                                                                                                                                                            // Colorize: green
                );                                                                                                                                                                                       // Colorize: green
    // Ignore CppAlignmentVerifier [END]                                                                                                                                                                 // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
qint32 main(qint32 argc, char *argv[])                                                                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QCoreApplication app(argc, argv);                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    const QStringList &arguments = app.arguments();                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Check arguments                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (arguments.size() != 2)                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            usage();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return 1;                                                                                                                                                                                    // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString targetPath = arguments.at(1);                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Output application info                                                                                                                                                                           // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        Console::out("Tests verifier started");                                                                                                                                                           // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out("Parameters:");                                                                                                                                                                     // Colorize: green
        Console::out(QString("PATH = %1").arg(targetPath));                                                                                                                                              // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    qint64 startTime = QDateTime::currentMSecsSinceEpoch();                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<TestWorkerThread *> workers;                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Start workers                                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < QThread::idealThreadCount(); ++i)                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            TestWorkerThread *worker = new TestWorkerThread();                                                                                                                                           // Colorize: green
            worker->start();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            workers.append(worker);                                                                                                                                                                      // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Iterate over files in targetPath and push them to workers                                                                                                                                         // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QQueue<QFileInfo> files;                                                                                                                                                                         // Colorize: green
        files.enqueue(QFileInfo(targetPath));                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        while (!files.isEmpty())                                                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QFileInfo file = files.dequeue();                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            QString path     = file.absoluteFilePath();                                                                                                                                                  // Colorize: green
            QString fileName = file.fileName();                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (!GIT::isIgnored(file.dir().absolutePath(), path))                                                                                                                                        // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (file.isDir())                                                                                                                                                                        // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (fileName != ".git" && fileName != "test")                                                                                                                                        // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        QFileInfoList filesInfo = QDir(path).entryInfoList(QDir::AllEntries | QDir::NoDotAndDotDot);                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                        for (qint64 i = 0; i < filesInfo.size(); ++i)                                                                                                                                    // Colorize: green
                        {                                                                                                                                                                                // Colorize: green
                            files.enqueue(filesInfo.at(i));                                                                                                                                              // Colorize: green
                        }                                                                                                                                                                                // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                else                                                                                                                                                                                     // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (fileName.endsWith(".h"))                                                                                                                                                         // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        TestWorkerThread::pushFile(path);                                                                                                                                                // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TestWorkerThread::noMoreFiles();                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<TestVerifyThread *> verifiers;                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Start verifiers                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < QThread::idealThreadCount(); ++i)                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            TestVerifyThread *verifier = new TestVerifyThread();                                                                                                                                         // Colorize: green
            verifier->start();                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            verifiers.append(verifier);                                                                                                                                                                  // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<TestStructureEntry> testStructureEntries;                                                                                                                                                      // Colorize: green
    QList<TestEntry>          testEntries;                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Wait for workers and push their results to verifiers                                                                                                                                              // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < workers.size(); ++i)                                                                                                                                                      // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            TestWorkerThread *worker = workers.at(i);                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            worker->wait();                                                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            TestVerifyThread::pushTestStructureEntries(worker->getTestStructureEntries());                                                                                                               // Colorize: green
            testStructureEntries.append(worker->getTestStructureEntries());                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            TestVerifyThread::pushTestEntries(worker->getTestEntries());                                                                                                                                 // Colorize: green
            testEntries.append(worker->getTestEntries());                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            delete worker;                                                                                                                                                                               // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TestVerifyThread::noMoreTestStructureEntries();                                                                                                                                                      // Colorize: green
    TestVerifyThread::noMoreTestEntries();                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Print structure entries for testing                                                                                                                                                               // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        std::sort(testStructureEntries.begin(), testStructureEntries.end());                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out("Found structure entries for testing:");                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (qint64 i = 0; i < testStructureEntries.size(); ++i)                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            Console::out(testStructureEntries.at(i).toString());                                                                                                                                         // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out(QString("Structure entries for testing: %1").arg(testStructureEntries.size()));                                                                                                     // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Print entries for testing                                                                                                                                                                         // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        std::sort(testEntries.begin(), testEntries.end());                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out("Found entries for testing:");                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (qint64 i = 0; i < testEntries.size(); ++i)                                                                                                                                                  // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            Console::out(testEntries.at(i).toString());                                                                                                                                                  // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out(QString("Entries for testing: %1").arg(testEntries.size()));                                                                                                                        // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<TestMessageInfo> messages;                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Wait for verifiers and get messages from them                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < verifiers.size(); ++i)                                                                                                                                                    // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            TestVerifyThread *verifier = verifiers.at(i);                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            verifier->wait();                                                                                                                                                                            // Colorize: green
            messages.append(verifier->getMessages());                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            delete verifier;                                                                                                                                                                             // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // If there are some messages from verifiers then print them                                                                                                                                         // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (!messages.isEmpty())                                                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            std::sort(messages.begin(), messages.end());                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            // Print errors                                                                                                                                                                              // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                Console::err("");                                                                                                                                                                        // Colorize: green
                Console::err("Errors:");                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                for (qint64 i = 0; i < messages.size(); ++i)                                                                                                                                             // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err(messages.at(i).toString());                                                                                                                                             // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            qint64 amountOfBitsTests = 0;                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            // Calculate structures with bits                                                                                                                                                            // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                for (qint64 i = 0; i < testStructureEntries.size(); ++i)                                                                                                                                 // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (testStructureEntries.at(i).isBitsDefined())                                                                                                                                      // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        ++amountOfBitsTests;                                                                                                                                                             // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::err("");                                                                                                                                                                            // Colorize: green
            Console::err(QString("Tests covered on %1 %").arg(100.0 - messages.size() * 100.0 / (testStructureEntries.size() + amountOfBitsTests + testEntries.size())));                                // Colorize: green
            Console::err("");                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::out(QString("%1 files verified in %2 ms").arg(TestWorkerThread::getAmountOfFiles()).arg(QDateTime::currentMSecsSinceEpoch() - startTime));                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return 1;                                                                                                                                                                                    // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Everything is OK                                                                                                                                                                                  // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out("Tests covered on 100 %");                                                                                                                                                          // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        Console::out(QString("%1 files verified in %2 ms").arg(TestWorkerThread::getAmountOfFiles()).arg(QDateTime::currentMSecsSinceEpoch() - startTime));                                              // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return 0;                                                                                                                                                                                            // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
