#ifndef COM_NGOS_DEVTOOLS_CODE_GENERATOR_GENERATORS_ASSETS_ASSETSGENERATOR_H                                                                                                                             // Colorize: green
#define COM_NGOS_DEVTOOLS_CODE_GENERATOR_GENERATORS_ASSETS_ASSETSGENERATOR_H                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_generator/generators/generator.h>                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <QList>                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
class AssetsGenerator: public Generator                                                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
public:                                                                                                                                                                                                  // Colorize: green
    AssetsGenerator(); // TEST: NO                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static bool generateAll(const QString &path); // TEST: NO                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
protected:                                                                                                                                                                                               // Colorize: green
    virtual bool generate(const QString &path) = 0; // TEST: NO                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
private:                                                                                                                                                                                                 // Colorize: green
    static QList<AssetsGenerator *> sGenerators;                                                                                                                                                         // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_CODE_GENERATOR_GENERATORS_ASSETS_ASSETSGENERATOR_H                                                                                                                           // Colorize: green
