#ifndef OS_SHARED_COMMON_SRC_BITS64_INFLATE_INFLATEBLOCKTYPE_H
#define OS_SHARED_COMMON_SRC_BITS64_INFLATE_INFLATEBLOCKTYPE_H



#include <ngos/types.h>



enum class InflateBlockType: u8
{
    NO_COMPRESSION,
    COMPRESSED_FIXED_HUFFMAN,
    COMPRESSED_DYNAMIC_HUFFMAN,
    UNKNOWN
};



#endif // OS_SHARED_COMMON_SRC_BITS64_INFLATE_INFLATEBLOCKTYPE_H
