#ifndef COM_NGOS_SHARED_COMMON_UEFI_CONFIG_UEFIHCDPCONFIGURATIONTABLE_H
#define COM_NGOS_SHARED_COMMON_UEFI_CONFIG_UEFIHCDPCONFIGURATIONTABLE_H



#define UEFI_HCDP_CONFIGURATION_TABLE_GUID \
    { 0xF951938D, 0x620B, 0x42EF, { 0x82, 0x79, 0xA8, 0x4B, 0x79, 0x61, 0x78, 0x98 } }



struct UefiHcdpConfigurationTable
{
};



#endif // COM_NGOS_SHARED_COMMON_UEFI_CONFIG_UEFIHCDPCONFIGURATIONTABLE_H
