SOURCES += \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvaddps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvdivps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvmaxps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvminps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvmulps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvrcpps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvrsqrtps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvsqrtps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx/testavxvsubps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx2/testavx2vphaddd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx2/testavx2vphaddw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx2/testavx2vphsubd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx2/testavx2vphsubw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512bw/testavx512bwvpbroadcastb.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512bw/testavx512bwvpbroadcastw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512bw/testavx512bwvpsllvw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512bw/testavx512bwvpsrlvw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512cd/testavx512cdvpbroadcastmb2q.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512cd/testavx512cdvpbroadcastmw2d.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512cd/testavx512cdvplzcntd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512cd/testavx512cdvplzcntq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512dq/testavx512dqvcvtpd2qq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512dq/testavx512dqvcvtps2qq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512dq/testavx512dqvcvtqq2pd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512dq/testavx512dqvcvtqq2ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512dq/testavx512dqvpmullq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvaddps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvdivps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvmaxps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvminps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvmulps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvrcp14ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvrsqrt14ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvsqrtps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512f/testavx512fvsubps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvaddps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvdivps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvmaxps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvminps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvmulps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvrcp14ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvrsqrt14ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvsqrtps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/avx512vl/testavx512vlvsubps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/fma3/testfma3vfmadd213pd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/fma3/testfma3vfmadd213ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/fma3/testfma3vfmsub213pd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/fma3/testfma3vfmsub213ps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testsseaddps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssedivps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssemaxps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testsseminps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssemulps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssercpps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssersqrtps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssesqrtps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse/testssesubps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2addpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2divpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2maxpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2minpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2mulpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2paddb.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2paddd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2paddq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2paddw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2psubb.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2psubd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2psubq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2psubw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2sqrtpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse2/testsse2subpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3addsubpb.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3addsubps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3haddpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3haddps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3hsubpd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3hsubps.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3phaddd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3phaddw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3phsubd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse3/testsse3phsubw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pmaxsb.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pmaxsd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pmaxud.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pmaxuw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pminsb.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pminsd.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pminud.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pminuw.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pmuldq.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse41/testsse41pmulld.S \
    $$PWD/asm/arch/x86_64/bits64/test/sections/section0/__shared/common/bits64/fpu/sse42/testsse42pcmpgtq.S \
    $$PWD/src/bits64/main/setupbootparams.cpp \
    $$PWD/src/bits64/main/setupcr4.cpp \
    $$PWD/src/bits64/main/setupdynamicrelocation.cpp \
    $$PWD/src/bits64/main/setupglobalobjects.cpp \
    $$PWD/src/bits64/main/setupgraphics.cpp \
    $$PWD/src/bits64/uefi/uefi.cpp \
    $$PWD/test/bits64/testresults.cpp

HEADERS += \
    $$PWD/src/bits64/main/setupbootparams.h \
    $$PWD/src/bits64/main/setupcr4.h \
    $$PWD/src/bits64/main/setupdynamicrelocation.h \
    $$PWD/src/bits64/main/setupglobalobjects.h \
    $$PWD/src/bits64/main/setupgraphics.h \
    $$PWD/src/bits64/other/uefibootmemorymap.h \
    $$PWD/src/bits64/uefi/uefi.h \
    $$PWD/src/bits64/uefi/uefiassert.h \
    $$PWD/src/bits64/uefi/uefilog.h \
    $$PWD/test/bits64/sections/section0/__include/asm/bitutils.h \
    $$PWD/test/bits64/sections/section0/__include/asm/instructions.h \
    $$PWD/test/bits64/sections/section0/__include/bootparams/memorymapentry.h \
    $$PWD/test/bits64/sections/section0/__include/elf/symbol.h \
    $$PWD/test/bits64/sections/section0/__include/guid/utils.h \
    $$PWD/test/bits64/sections/section0/__include/ngos/linkage.h \
    $$PWD/test/bits64/sections/section0/__include/ngos/types.h \
    $$PWD/test/bits64/sections/section0/__include/ngos/utils.h \
    $$PWD/test/bits64/sections/section0/__include/pagetable/utils.h \
    $$PWD/test/bits64/sections/section0/__include/types.h \
    $$PWD/test/bits64/sections/section0/__include/uuid/utils.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/checksum/adler.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/checksum/crc.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/containers/lib/listelement.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/containers/list.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/cpu/cpu.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvaddps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvdivps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvmaxps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvminps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvmulps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvrcpps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvrsqrtps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvsqrtps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/asm_testavxvsubps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx/avx.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx2/asm_testavx2vphaddd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx2/asm_testavx2vphaddw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx2/asm_testavx2vphsubd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx2/asm_testavx2vphsubw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx2/avx2.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512bw/asm_testavx512bwvpbroadcastb.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512bw/asm_testavx512bwvpbroadcastw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512bw/asm_testavx512bwvpsllvw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512bw/asm_testavx512bwvpsrlvw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512bw/avx512bw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512cd/asm_testavx512cdvpbroadcastmb2q.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512cd/asm_testavx512cdvpbroadcastmw2d.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512cd/asm_testavx512cdvplzcntd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512cd/asm_testavx512cdvplzcntq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512cd/avx512cd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512dq/asm_testavx512dqvcvtpd2qq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512dq/asm_testavx512dqvcvtps2qq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512dq/asm_testavx512dqvcvtqq2pd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512dq/asm_testavx512dqvcvtqq2ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512dq/asm_testavx512dqvpmullq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512dq/avx512dq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvaddps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvdivps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvmaxps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvminps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvmulps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvrcp14ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvrsqrt14ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvsqrtps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/asm_testavx512fvsubps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512f/avx512f.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvaddps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvdivps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvmaxps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvminps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvmulps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvrcp14ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvrsqrt14ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvsqrtps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/asm_testavx512vlvsubps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/avx512vl/avx512vl.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/fma3/asm_testfma3vfmadd213pd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/fma3/asm_testfma3vfmadd213ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/fma3/asm_testfma3vfmsub213pd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/fma3/asm_testfma3vfmsub213ps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/fma3/fma3.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/fpu.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testsseaddps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssedivps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssemaxps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testsseminps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssemulps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssercpps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssersqrtps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssesqrtps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/asm_testssesubps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse/sse.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2addpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2divpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2maxpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2minpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2mulpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2paddb.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2paddd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2paddq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2paddw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2psubb.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2psubd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2psubq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2psubw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2sqrtpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/asm_testsse2subpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse2/sse2.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3addsubpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3addsubps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3haddpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3haddps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3hsubpd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3hsubps.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3phaddd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3phaddw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3phsubd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/asm_testsse3phsubw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse3/sse3.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pmaxsb.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pmaxsd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pmaxud.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pmaxuw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pminsb.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pminsd.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pminud.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pminuw.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pmuldq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/asm_testsse41pmulld.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse41/sse41.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse42/asm_testsse42pcmpgtq.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/fpu/sse42/sse42.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/graphics/image.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/graphics/ninepatch.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/graphics/png/png.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/graphics/stretchrange.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/gui/widgets/widget.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/memory/memory.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/printf/printf.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/random/random.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/string/string.h \
    $$PWD/test/bits64/sections/section0/__shared/common/bits64/types.h \
    $$PWD/test/bits64/sections/section0/__shared/uefibase/bits64/other/uefibootmemorymap.h \
    $$PWD/test/bits64/sections/section0/__shared/uefibase/bits64/types.h \
    $$PWD/test/bits64/sections/section0/__shared/uefibase/bits64/uefi/uefi.h \
    $$PWD/test/bits64/sections/section0/testcase.h \
    $$PWD/test/bits64/testengine.h \
    $$PWD/test/bits64/testresults.h
