#ifndef CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIGRAPHICSOUTPUTBLTOPERATION_H
#define CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIGRAPHICSOUTPUTBLTOPERATION_H



enum class EfiGraphicsOutputBltOperation
{
    VIDEO_FILL,
    VIDEO_TO_BLT_BUFFER,
    BLT_BUFFER_TO_VIDEO,
    VIDEO_TO_VIDEO,
    MAXIMUM
};



#endif // CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIGRAPHICSOUTPUTBLTOPERATION_H
