#ifndef CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIINTERFACETYPE_H
#define CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIINTERFACETYPE_H



enum class EfiInterfaceType
{
    NATIVE_INTERFACE,
    PCODE_INTERFACE
};



#endif // CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIINTERFACETYPE_H
