#ifndef CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIMEMORYTYPE_H
#define CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIMEMORYTYPE_H



enum class EfiMemoryType
{
    RESERVED_MEMORY,
    LOADER_CODE,
    LOADER_DATA,
    BOOT_SERVICES_CODE,
    BOOT_SERVICES_DATA,
    RUNTIME_SERVICES_CODE,
    RUNTIME_SERVICES_DATA,
    CONVENTIONAL_MEMORY,
    UNUSABLE_MEMORY,
    ACPI_RECLAIM_MEMORY,
    ACPI_MEMORY_NVS,
    MEMORY_MAPPED_IO,
    MEMORY_MAPPED_IO_PORT_SPACE,
    PAL_CODE,
    PERSISTENT_MEMORY,
    MAXIMUM
};



#endif // CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIMEMORYTYPE_H
