#ifndef CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIRESETTYPE_H
#define CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIRESETTYPE_H



enum class EfiResetType
{
    COLD,
    WARM,
    SHUTDOWN
};



#endif // CONFIGURE_SRC_BITS64_A_UEFI_UEFI_LIB_EFIRESETTYPE_H
