#include "specverifythread.h"                                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/specs_verifier/specs/specverifier.h>                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
SpecVerifyThread::SpecVerifyThread(const QString &path)                                                                                                                                              // Colorize: green
    : QThread()                                                                                                                                                                                          // Colorize: green
    , mPath(path)                                                                                                                                                                                        // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void SpecVerifyThread::run()                                                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    do                                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        SpecVerifier *verifier = SpecVerifier::getSpecVerifier();                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (verifier == nullptr)                                                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            break;                                                                                                                                                                                       // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        verifier->verify(mPath);                                                                                                                                                                         // Colorize: green
    } while (true);                                                                                                                                                                                      // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
