#ifndef COM_NGOS_DEVTOOLS_IMAGE_BUILDER_OTHER_PEOPTIONALHEADERDLLCHARACTERISTICSFLAGS_H                                                                                                                  // Colorize: green
#define COM_NGOS_DEVTOOLS_IMAGE_BUILDER_OTHER_PEOPTIONALHEADERDLLCHARACTERISTICSFLAGS_H                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <Qt>                                                                                                                                                                                            // Colorize: green
#include <stdio.h>                                                                                                                                                                                       // Colorize: green
#include <string.h>                                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/bits/flags.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/bits/macros.h>                                                                                                                                                          // Colorize: green
#include <com/ngos/shared/common/ngos/linkage.h>                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/devtools/shared/utils/string.h>                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with PeSpecVerifier [BEGIN] // https://docs.microsoft.com/en-us/windows/win32/debug/pe-format                                                                                                // Colorize: green
typedef quint16 pe_optional_header_dll_characteristics_flags;                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class PeOptionalHeaderDllCharacteristicsFlag: pe_optional_header_dll_characteristics_flags                                                                                                          // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE                  = 0,                                                                                                                                                                           // Colorize: green
    HIGH_ENTROPY_VA       = BIT_5,  // Image can handle a high entropy 64-bit virtual address space.                                                                                               // Colorize: green
    DYNAMIC_BASE          = BIT_6,  // DLL can be relocated at load time.                                                                                                                          // Colorize: green
    FORCE_INTEGRITY       = BIT_7,  // Code Integrity checks are enforced.                                                                                                                         // Colorize: green
    NX_COMPAT             = BIT_8,  // Image is NX compatible.                                                                                                                                     // Colorize: green
    NO_ISOLATION          = BIT_9,  // Isolation aware, but do not isolate the image.                                                                                                              // Colorize: green
    NO_SEH                = BIT_10, // Does not use structured exception (SE) handling. No SE handler may be called in this image.                                                                 // Colorize: green
    NO_BIND               = BIT_11, // Do not bind the image.                                                                                                                                      // Colorize: green
    APPCONTAINER          = BIT_12, // Image must execute in an AppContainer.                                                                                                                      // Colorize: green
    WDM_DRIVER            = BIT_13, // A WDM driver.                                                                                                                                               // Colorize: green
    GUARD_CF              = BIT_14, // Image supports Control Flow Guard.                                                                                                                          // Colorize: green
    TERMINAL_SERVER_AWARE = BIT_15  // Terminal Server aware.                                                                                                                                      // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
DEFINE_FLAGS(PeOptionalHeaderDllCharacteristicsFlags, pe_optional_header_dll_characteristics_flags); // TEST: NO                                                                                         // Colorize: green
// Verified with PeSpecVerifier [END] // https://docs.microsoft.com/en-us/windows/win32/debug/pe-format                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToString(PeOptionalHeaderDllCharacteristicsFlag flag) // TEST: NO                                                                                                                // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (flag)                                                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case PeOptionalHeaderDllCharacteristicsFlag::NONE: return "NONE";                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToFullString(PeOptionalHeaderDllCharacteristicsFlag flag) // TEST: NO                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[24];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%08X (%s)", (pe_optional_header_dll_characteristics_flags)flag, flagToString(flag));                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToString(const PeOptionalHeaderDllCharacteristicsFlags &flags) // TEST: NO                                                                                                      // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[48];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_STRING(res, flags.flags, PeOptionalHeaderDllCharacteristicsFlag);                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToFullString(const PeOptionalHeaderDllCharacteristicsFlags &flags) // TEST: NO                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[61];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_FULL_STRING(res, flags.flags, PeOptionalHeaderDllCharacteristicsFlag, "0x%08X");                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_DEVTOOLS_IMAGE_BUILDER_OTHER_PEOPTIONALHEADERDLLCHARACTERISTICSFLAGS_H                                                                                                                // Colorize: green
