#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_DMI_DMIIDENTITY_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_DMI_DMIIDENTITY_H



#include <ngos/types.h>



enum class DmiIdentity: u8
{
    BIOS_VENDOR,
    BIOS_VERSION,
    BIOS_RELEASE_DATE,
    SYSTEM_MANUFACTURER,
    SYSTEM_PRODUCT_NAME,
    SYSTEM_VERSION,
    SYSTEM_SERIAL_NUMBER,
    SYSTEM_SKU_NUMBER,
    SYSTEM_FAMILY,
    BASEBOARD_MANUFACTURER,
    BASEBOARD_PRODUCT,
    BASEBOARD_VERSION,
    BASEBOARD_SERIAL_NUMBER,
    BASEBOARD_ASSET_TAG,
    MAX
};



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_DMI_DMIIDENTITY_H
