#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_DMI_DMISTOREDUUID_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_DMI_DMISTOREDUUID_H



#include <ngos/types.h>



enum class DmiStoredUuid: u8
{
    SYSTEM_UUID,
    MAX
};



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_DMI_DMISTOREDUUID_H
