#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H



#include <ngos/status.h>



NgosStatus setupUefiMemoryMap(); // TEST: NO



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H
