#ifndef OS_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPSTACKCANARY_H
#define OS_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPSTACKCANARY_H



#include <ngos/status.h>



NgosStatus setupStackCanary(); // TEST: NO



#endif // OS_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPSTACKCANARY_H
