#ifndef COM_NGOS_SHARED_UEFIBASE_SECTIONS_SECTION0_COM_NGOS_SHARED_COMMON_MEMORY_MEMORY_H                                                                                                                // Colorize: green
#define COM_NGOS_SHARED_UEFIBASE_SECTIONS_SECTION0_COM_NGOS_SHARED_COMMON_MEMORY_MEMORY_H                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <buildconfig.h>                                                                                                                                                                                 // Colorize: green
#include <com/ngos/shared/common/memory/memory.h>                                                                                                                                                        // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/uefibase/testengine.h>                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#if NGOS_BUILD_TEST_MODE == OPTION_YES                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
TEST_CASES(section0, com_ngos_shared_common_memory_memory);                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    TEST_CASE("memcpy()");                                                                                                                                                                               // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        good_u8 buffer[34] = { 5, 7, 3, 2, 8, 9, 1, 3, 4, 6, 7, 5, 4, 3, 9, 1, 7, 5, 7, 3, 2, 8, 9, 1, 3, 4, 6, 7, 5, 4, 3, 9, 1, 7 };                                                                        // Colorize: green
        good_u8 temp[34];                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memzero(temp,        34), temp);                                                                                                                                              // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp, buffer, 34), -1);                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcpy(temp, buffer, 34), temp);                                                                                                                                              // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp, buffer, 34), 0);                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        temp[12] = 99;                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcpy(temp, buffer, 12), temp);                                                                                                                                              // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp, buffer, 34), 1);                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcpy(temp, buffer, 13), temp);                                                                                                                                              // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp, buffer, 34), 0);                                                                                                                                                 // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TEST_CASE("memset()");                                                                                                                                                                               // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        good_u8 buffer[197];                                                                                                                                                                                  // Colorize: green
        good_u8 temp[197];                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (good_i64 i = 0; i < 197; ++i)                                                                                                                                                                    // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            buffer[i] = 5;                                                                                                                                                                               // Colorize: green
            temp[i]   = 0;                                                                                                                                                                               // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 197), 1);                                                                                                                                                // Colorize: green
        TEST_ASSERT_EQUALS(memset(buffer, 0,    197), buffer);                                                                                                                                              // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 197), 0);                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (good_i64 i = 0; i < 135; ++i)                                                                                                                                                                    // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            temp[i] = 8;                                                                                                                                                                                 // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 197), -1);                                                                                                                                               // Colorize: green
        TEST_ASSERT_EQUALS(memset(buffer, 8,    135), buffer);                                                                                                                                              // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 197), 0);                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TEST_CASE("memzero()");                                                                                                                                                                              // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        good_u8 buffer[197];                                                                                                                                                                                  // Colorize: green
        good_u8 temp[197];                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (good_i64 i = 0; i < 197; ++i)                                                                                                                                                                    // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            buffer[i] = 5;                                                                                                                                                                               // Colorize: green
            temp[i]   = 0;                                                                                                                                                                               // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 197), 1);                                                                                                                                                // Colorize: green
        TEST_ASSERT_EQUALS(memzero(buffer,      197), buffer);                                                                                                                                           // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 197), 0);                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TEST_CASE("memcmp()");                                                                                                                                                                               // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        good_u8 buffer[5] = { 5, 7, 3, 2, 8 };                                                                                                                                                                // Colorize: green
        good_u8 temp[5]   = { 5, 7, 3, 2, 8 };                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp, 5), 0);                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        temp[4] = 1;                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp,   5), 1);                                                                                                                                                // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp,   buffer, 5), -1);                                                                                                                                                 // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(buffer, temp,   4), 0);                                                                                                                                                  // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TEST_CASE("memempty()");                                                                                                                                                                             // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        good_u8 buffer[197];                                                                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memzero(buffer,  197), buffer);                                                                                                                                               // Colorize: green
        TEST_ASSERT_EQUALS(memempty(buffer, 197), true);                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        buffer[163] = 1;                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memempty(buffer, 197), false);                                                                                                                                                // Colorize: green
        TEST_ASSERT_EQUALS(memempty(buffer, 163), true);                                                                                                                                                 // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    TEST_CASE("memmove()");                                                                                                                                                                              // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        good_u8 buffer[34] = { 5, 7, 3, 2, 8, 9, 1, 3, 4, 6, 7, 5, 4, 3, 9, 1, 7, 5, 7, 3, 2, 8, 9, 1, 3, 4, 6, 7, 5, 4, 3, 9, 1, 7 };                                                                        // Colorize: green
        good_u8 temp[34];                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memzero(temp,         34), temp);                                                                                                                                             // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp, buffer,  34), -1);                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memmove(temp, buffer, 34), temp);                                                                                                                                             // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp, buffer,  34), 0);                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (good_i64 i = 0; i < 33; ++i)                                                                                                                                                                     // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            temp[i] = temp[i + 1];                                                                                                                                                                       // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp,    buffer,     34), 1);                                                                                                                                                 // Colorize: green
        TEST_ASSERT_EQUALS(memmove(buffer, buffer + 1, 33), buffer);                                                                                                                                     // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp,    buffer,     34), 0);                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (good_i64 i = 30; i >= 0; --i)                                                                                                                                                                    // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            temp[i + 3] = temp[i];                                                                                                                                                                       // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp,        buffer, 34), -1);                                                                                                                                                // Colorize: green
        TEST_ASSERT_EQUALS(memmove(buffer + 3, buffer, 31), buffer + 3);                                                                                                                                 // Colorize: green
        TEST_ASSERT_EQUALS(memcmp(temp,        buffer, 34), 0);                                                                                                                                                 // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
TEST_CASES_END();                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_UEFIBASE_SECTIONS_SECTION0_COM_NGOS_SHARED_COMMON_MEMORY_MEMORY_H                                                                                                              // Colorize: green
