#ifndef COM_NGOS_SHARED_COMMON_PCI_CAPABILITY_PCIACCELERATEDGRAPHICSPORT8XCAPABILITY_H
#define COM_NGOS_SHARED_COMMON_PCI_CAPABILITY_PCIACCELERATEDGRAPHICSPORT8XCAPABILITY_H



#include <com/ngos/shared/common/pci/pcicapabilityheader.h>



struct PciAcceleratedGraphicsPort8xCapability
{
    PciCapabilityHeader header;
};



#endif // COM_NGOS_SHARED_COMMON_PCI_CAPABILITY_PCIACCELERATEDGRAPHICSPORT8XCAPABILITY_H
