#ifndef OS_SHARED_UEFIBASE_SRC_COM_NGOS_SHARED_UEFIBASE_MAIN_EARLYINITIALIZATION_H
#define OS_SHARED_UEFIBASE_SRC_COM_NGOS_SHARED_UEFIBASE_MAIN_EARLYINITIALIZATION_H



#include <common/src/com/ngos/shared/common/ngos/status.h>



NgosStatus earlyInitialization(u64 kernelLocation); // TEST: NO



#endif // OS_SHARED_UEFIBASE_SRC_COM_NGOS_SHARED_UEFIBASE_MAIN_EARLYINITIALIZATION_H
