#ifndef OS_SHARED_UEFIBASE_SRC_COM_NGOS_SHARED_UEFIBASE_MAIN_SETUPGLOBALOBJECTS_H
#define OS_SHARED_UEFIBASE_SRC_COM_NGOS_SHARED_UEFIBASE_MAIN_SETUPGLOBALOBJECTS_H



#include <common/src/com/ngos/shared/common/ngos/status.h>



NgosStatus setupGlobalObjects(); // TEST: NO



#endif // OS_SHARED_UEFIBASE_SRC_COM_NGOS_SHARED_UEFIBASE_MAIN_SETUPGLOBALOBJECTS_H
