#ifndef CONFIGURE_TEST_BITS64_A_UEFI_SECTIONS_SECTION0___COMMON_BITS64_FPU_ASM512CD_ASM_TESTAVX512CDVPBROADCASTMW2D_H
#define CONFIGURE_TEST_BITS64_A_UEFI_SECTIONS_SECTION0___COMMON_BITS64_FPU_ASM512CD_ASM_TESTAVX512CDVPBROADCASTMW2D_H



#include <buildconfig.h>
#include <ngos/linkage.h>
#include <ngos/types.h>



#if NGOS_BUILD_TEST_MODE == OPTION_YES



CPP_EXTERN_C
void testAvx512cdVpbroadcastmw2d(u32 *a, u16 mask);



#endif



#endif // CONFIGURE_TEST_BITS64_A_UEFI_SECTIONS_SECTION0___COMMON_BITS64_FPU_ASM512CD_ASM_TESTAVX512CDVPBROADCASTMW2D_H
