#include <QCoreApplication>                                                                                                                                                                              // Colorize: green
#include <QDateTime>                                                                                                                                                                                     // Colorize: green
#include <QString>                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/image_builder/main/imagebuilder.h>                                                                                                                                           // Colorize: green
#include <com/ngos/devtools/shared/console/console.h>                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void usage()                                                                                                                                                                                             // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Ignore CppAlignmentVerifier [BEGIN]                                                                                                                                                               // Colorize: green
    Console::err(                                                                                                                                                                                        // Colorize: green
                "Usage: image_builder -b PATH_TO_BOOT_ELF (-c PATH_TO_CONFIGURE_ELF -k PATH_TO_KERNEL_ELF | -t PATH_TO_TEXT_ELF) -o PATH_TO_RESULT_IMAGE\n"                                              // Colorize: green
                "    * -b PATH_TO_BOOT_ELF      - specify path to boot.elf file\n"                                                                                                                       // Colorize: green
                "    * -c PATH_TO_CONFIGURE_ELF - specify path to configure.elf file\n"                                                                                                                  // Colorize: green
                "    * -k PATH_TO_KERNEL_ELF    - specify path to kernel.elf file\n"                                                                                                                     // Colorize: green
                "    * -t PATH_TO_TEXT_ELF      - specify path to text.elf file\n"                                                                                                                       // Colorize: green
                "    * -o PATH_TO_RESULT_IMAGE  - specify path to result image\n"                                                                                                                        // Colorize: green
                "\n" // Ignore CppSingleCharVerifier                                                                                                                                                     // Colorize: green
                "If you specify argument \"-t PATH_TO_TEXT_ELF\" it will replace existing .configure section and .kernel section in boot.elf file with a single .text section"                           // Colorize: green
                );                                                                                                                                                                                       // Colorize: green
    // Ignore CppAlignmentVerifier [END]                                                                                                                                                                 // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
qint32 main(qint32 argc, char *argv[])                                                                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QCoreApplication app(argc, argv);                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    const QStringList &arguments = app.arguments();                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString bootElfPath;                                                                                                                                                                                 // Colorize: green
    QString configureElfPath;                                                                                                                                                                            // Colorize: green
    QString kernelElfPath;                                                                                                                                                                               // Colorize: green
    QString textElfPath;                                                                                                                                                                                 // Colorize: green
    QString resultImagePath;                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Get arguments                                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 1; i < arguments.size(); ++i)                                                                                                                                                    // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QString arg = arguments.at(i);                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (arg == "-b")                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (i >= arguments.size() - 1)                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    usage();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    Console::err(QString("Additional argument missing for %1")                                                                                                                           // Colorize: green
                                            .arg(arg)                                                                                                                                                    // Colorize: green
                                 );                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (bootElfPath != "")                                                                                                                                                                   // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err("PATH_TO_BOOT_ELF is already specified");                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                ++i;                                                                                                                                                                                     // Colorize: green
                bootElfPath = arguments.at(i);                                                                                                                                                           // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (arg == "-c")                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (i >= arguments.size() - 1)                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    usage();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    Console::err(QString("Additional argument missing for %1")                                                                                                                           // Colorize: green
                                            .arg(arg)                                                                                                                                                    // Colorize: green
                                 );                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (configureElfPath != "")                                                                                                                                                              // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err("PATH_TO_CONFIGURE_ELF is already specified");                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                ++i;                                                                                                                                                                                     // Colorize: green
                configureElfPath = arguments.at(i);                                                                                                                                                      // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (arg == "-k")                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (i >= arguments.size() - 1)                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    usage();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    Console::err(QString("Additional argument missing for %1")                                                                                                                           // Colorize: green
                                            .arg(arg)                                                                                                                                                    // Colorize: green
                                 );                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (kernelElfPath != "")                                                                                                                                                                 // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err("PATH_TO_KERNEL_ELF is already specified");                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                ++i;                                                                                                                                                                                     // Colorize: green
                kernelElfPath = arguments.at(i);                                                                                                                                                         // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (arg == "-t")                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (i >= arguments.size() - 1)                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    usage();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    Console::err(QString("Additional argument missing for %1")                                                                                                                           // Colorize: green
                                            .arg(arg)                                                                                                                                                    // Colorize: green
                                 );                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (textElfPath != "")                                                                                                                                                                   // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err("PATH_TO_TEXT_ELF is already specified");                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                ++i;                                                                                                                                                                                     // Colorize: green
                textElfPath = arguments.at(i);                                                                                                                                                           // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            if (arg == "-o")                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (i >= arguments.size() - 1)                                                                                                                                                           // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    usage();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    Console::err(QString("Additional argument missing for %1")                                                                                                                           // Colorize: green
                                            .arg(arg)                                                                                                                                                    // Colorize: green
                                 );                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                if (resultImagePath != "")                                                                                                                                                               // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    Console::err("PATH_TO_RESULT_IMAGE is already specified");                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                    return 1;                                                                                                                                                                            // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                ++i;                                                                                                                                                                                     // Colorize: green
                resultImagePath = arguments.at(i);                                                                                                                                                       // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            else                                                                                                                                                                                         // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                usage();                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                Console::err(QString("Unknown argument: %1")                                                                                                                                             // Colorize: green
                                        .arg(arg)                                                                                                                                                        // Colorize: green
                             );                                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return 1;                                                                                                                                                                                // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Output application info                                                                                                                                                                           // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        Console::out("Image builder started");                                                                                                                                                           // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out("Parameters:");                                                                                                                                                                     // Colorize: green
        Console::out(QString("PATH_TO_BOOT_ELF      = %1")                                                                                                                                               // Colorize: green
                                .arg(bootElfPath)                                                                                                                                                        // Colorize: green
                     );                                                                                                                                                                                  // Colorize: green
        Console::out(QString("PATH_TO_CONFIGURE_ELF = %1")                                                                                                                                               // Colorize: green
                                .arg(configureElfPath)                                                                                                                                                   // Colorize: green
                     );                                                                                                                                                                                  // Colorize: green
        Console::out(QString("PATH_TO_KERNEL_ELF    = %1")                                                                                                                                               // Colorize: green
                                .arg(kernelElfPath)                                                                                                                                                      // Colorize: green
                     );                                                                                                                                                                                  // Colorize: green
        Console::out(QString("PATH_TO_TEXT_ELF      = %1")                                                                                                                                               // Colorize: green
                                .arg(textElfPath)                                                                                                                                                        // Colorize: green
                     );                                                                                                                                                                                  // Colorize: green
        Console::out(QString("PATH_TO_RESULT_IMAGE  = %1")                                                                                                                                               // Colorize: green
                                .arg(resultImagePath)                                                                                                                                                    // Colorize: green
                     );                                                                                                                                                                                  // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Check arguments                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (bootElfPath == "")                                                                                                                                                                           // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            usage();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::err("PATH_TO_BOOT_ELF is not specified");                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return 1;                                                                                                                                                                                    // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (textElfPath == "")                                                                                                                                                                           // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (configureElfPath == "")                                                                                                                                                                  // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                usage();                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                Console::err("PATH_TO_CONFIGURE_ELF is not specified");                                                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return 1;                                                                                                                                                                                // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (kernelElfPath == "")                                                                                                                                                                     // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                usage();                                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                Console::err("PATH_TO_KERNEL_ELF is not specified");                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return 1;                                                                                                                                                                                // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        else                                                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            if (configureElfPath != "")                                                                                                                                                                  // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                Console::err("PATH_TO_CONFIGURE_ELF ignored");                                                                                                                                           // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (kernelElfPath != "")                                                                                                                                                                     // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                Console::err("PATH_TO_KERNEL_ELF ignored");                                                                                                                                              // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (resultImagePath == "")                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            usage();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::err("PATH_TO_RESULT_IMAGE is not specified");                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return 1;                                                                                                                                                                                    // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    qint64 startTime = QDateTime::currentMSecsSinceEpoch();                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    ImageBuilder imageBuilder(bootElfPath, configureElfPath, kernelElfPath, textElfPath, resultImagePath);                                                                                               // Colorize: green
    qint64 res = imageBuilder.process();                                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Output final messages                                                                                                                                                                             // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        Console::out(QString("Image built in %1 ms")                                                                                                                                                     // Colorize: green
                                .arg(QDateTime::currentMSecsSinceEpoch() - startTime)                                                                                                                    // Colorize: green
                     );                                                                                                                                                                                  // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
