#ifndef OS_SHARED_COMMON_SRC_BITS64_GRAPHICS_JPEG_JPEGQUANTIZATIONTABLE_H
#define OS_SHARED_COMMON_SRC_BITS64_GRAPHICS_JPEG_JPEGQUANTIZATIONTABLE_H



#include <ngos/types.h>



#define JPEG_QUANTIZATION_TABLE_COUNT 4



struct JpegQuantizationTable
{
    u8 id;
    u8 data[8][8];
} __attribute__((packed));



#endif // OS_SHARED_COMMON_SRC_BITS64_GRAPHICS_JPEG_JPEGQUANTIZATIONTABLE_H
