SOURCES += \
    $$PWD/asm/arch/x86_64/bits64/a_early/main/setupidthandlers.S \
    $$PWD/asm/arch/x86_64/main.S \
    $$PWD/src/bits64/a_early/main/disableirq.cpp \
    $$PWD/src/bits64/a_early/main/reservepciromimages.cpp \
    $$PWD/src/bits64/a_early/main/setupbootparams.cpp \
    $$PWD/src/bits64/a_early/main/setupbrk.cpp \
    $$PWD/src/bits64/a_early/main/setupcr4shadow.cpp \
    $$PWD/src/bits64/a_early/main/setupdmi.cpp \
    $$PWD/src/bits64/a_early/main/setupe820tables.cpp \
    $$PWD/src/bits64/a_early/main/setupfirstcpu.cpp \
    $$PWD/src/bits64/a_early/main/setuphypervisor.cpp \
    $$PWD/src/bits64/a_early/main/setupidthandlers.cpp \
    $$PWD/src/bits64/a_early/main/setupinittask.cpp \
    $$PWD/src/bits64/a_early/main/setupioremap.cpp \
    $$PWD/src/bits64/a_early/main/setupmemorymanager.cpp \
    $$PWD/src/bits64/a_early/main/setupstackcanary.cpp \
    $$PWD/src/bits64/a_early/main/setupuefimemorymap.cpp \
    $$PWD/src/bits64/a_early/main/setupuefisystemtable.cpp \
    $$PWD/src/bits64/a_early/other/adaptpagetable.cpp \
    $$PWD/src/bits64/other/bootparams/bootparams.cpp \
    $$PWD/src/bits64/other/brk/brk.cpp \
    $$PWD/src/bits64/other/cpu/cpumask.cpp \
    $$PWD/src/bits64/other/cpu/hotplug/cpuhotplug.cpp \
    $$PWD/src/bits64/other/cpu/percpu.cpp \
    $$PWD/src/bits64/other/e820/e820.cpp \
    $$PWD/src/bits64/other/hypervisor/hypervisor.cpp \
    $$PWD/src/bits64/other/hypervisor/kvm/clock/kvmclock.cpp \
    $$PWD/src/bits64/other/hypervisor/kvm/kvm.cpp \
    $$PWD/src/bits64/other/ioremap/ioremap.cpp \
    $$PWD/src/bits64/other/irq/irqstack.cpp \
    $$PWD/src/bits64/other/memorymanager/memorymanager.cpp \
    $$PWD/src/bits64/other/pagetable/addressconversion.cpp \
    $$PWD/src/bits64/other/pagetable/dynamicpagetable.cpp \
    $$PWD/src/bits64/other/task/task.cpp \
    $$PWD/src/bits64/other/task/utils.cpp \
    $$PWD/src/bits64/other/uefi/uefi.cpp \
    $$PWD/src/main.cpp \
    $$PWD/test/bits64/a_early/testresults.cpp

HEADERS += \
    $$PWD/src/bits64/a_early/main/asm_setupidthandlers.h \
    $$PWD/src/bits64/a_early/main/disableirq.h \
    $$PWD/src/bits64/a_early/main/reservepciromimages.h \
    $$PWD/src/bits64/a_early/main/setupbootparams.h \
    $$PWD/src/bits64/a_early/main/setupbrk.h \
    $$PWD/src/bits64/a_early/main/setupcr4shadow.h \
    $$PWD/src/bits64/a_early/main/setupdmi.h \
    $$PWD/src/bits64/a_early/main/setupe820tables.h \
    $$PWD/src/bits64/a_early/main/setupfirstcpu.h \
    $$PWD/src/bits64/a_early/main/setuphypervisor.h \
    $$PWD/src/bits64/a_early/main/setupidthandlers.h \
    $$PWD/src/bits64/a_early/main/setupinittask.h \
    $$PWD/src/bits64/a_early/main/setupioremap.h \
    $$PWD/src/bits64/a_early/main/setupmemorymanager.h \
    $$PWD/src/bits64/a_early/main/setupstackcanary.h \
    $$PWD/src/bits64/a_early/main/setupuefimemorymap.h \
    $$PWD/src/bits64/a_early/main/setupuefisystemtable.h \
    $$PWD/src/bits64/other/bootparams/bootparams.h \
    $$PWD/src/bits64/other/brk/brk.h \
    $$PWD/src/bits64/other/cpu/cpumask.h \
    $$PWD/src/bits64/other/cpu/hotplug/cpuhotplug.h \
    $$PWD/src/bits64/other/cpu/hotplug/cpuhotplugstate.h \
    $$PWD/src/bits64/other/cpu/hotplug/cpuhotplugstep.h \
    $$PWD/src/bits64/other/cpu/percpu.h \
    $$PWD/src/bits64/other/e820/e820.h \
    $$PWD/src/bits64/other/e820/e820table.h \
    $$PWD/src/bits64/other/hypervisor/hypervisor.h \
    $$PWD/src/bits64/other/hypervisor/hypervisortype.h \
    $$PWD/src/bits64/other/hypervisor/kvm/clock/kvmclock.h \
    $$PWD/src/bits64/other/hypervisor/kvm/kvm.h \
    $$PWD/src/bits64/other/hypervisor/kvm/kvmfeature.h \
    $$PWD/src/bits64/other/hypervisor/kvm/kvmfeaturetypeflags.h \
    $$PWD/src/bits64/other/ioremap/fixmap.h \
    $$PWD/src/bits64/other/ioremap/ioremap.h \
    $$PWD/src/bits64/other/ioremap/macros.h \
    $$PWD/src/bits64/other/ioremap/utils.h \
    $$PWD/src/bits64/other/irq/irqstack.h \
    $$PWD/src/bits64/other/kerneldefines.h \
    $$PWD/src/bits64/other/memorymanager/memoryblock.h \
    $$PWD/src/bits64/other/memorymanager/memoryblockregion.h \
    $$PWD/src/bits64/other/memorymanager/memoryblockregionflags.h \
    $$PWD/src/bits64/other/memorymanager/memoryblockregionnodeid.h \
    $$PWD/src/bits64/other/memorymanager/memoryblocktype.h \
    $$PWD/src/bits64/other/memorymanager/memorymanager.h \
    $$PWD/src/bits64/other/pagetable/addressconversion.h \
    $$PWD/src/bits64/other/pagetable/dynamicpagetable.h \
    $$PWD/src/bits64/other/task/task.h \
    $$PWD/src/bits64/other/task/taskstate.h \
    $$PWD/src/bits64/other/task/threadinfo.h \
    $$PWD/src/bits64/other/task/threadinfoflags.h \
    $$PWD/src/bits64/other/task/utils.h \
    $$PWD/src/bits64/other/uefi/uefi.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/brk/brk.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/cpu/cpumask.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/e820/e820.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/hypervisor/kvm/kvm.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/ioremap/ioremap.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/ioremap/utils.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/memorymanager/memoryblockregion.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/memorymanager/memorymanager.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/pagetable/addressconversion.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/pagetable/dynamicpagetable.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/other/task/utils.h \
    $$PWD/test/bits64/a_early/sections/section2/bits64/types.h \
    $$PWD/test/bits64/a_early/sections/section2/testcase.h \
    $$PWD/test/bits64/a_early/testengine.h \
    $$PWD/test/bits64/a_early/testresults.h
