#ifndef COM_NGOS_SHARED_COMMON_CPU_CPUIDSUBLEAF_H                                                                                                                                                           // Colorize: green
#define COM_NGOS_SHARED_COMMON_CPU_CPUIDSUBLEAF_H                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/cpu/lib/cpuidleaf.h>                                                                                                                                                    // Colorize: green
#include <com/ngos/shared/common/log/assert.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class CpuidSubLeaf: good_U32 // Ignore CppEnumVerifier // TODO: Validate with spec_verifier                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE = 0,                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
    // CpuidLeaf::DETERMINISTIC_CACHE_PARAMETERS                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    DETERMINISTIC_CACHE_PARAMETERS_LEVEL_0 = 0,                                                                                                                                                          // Colorize: green
    DETERMINISTIC_CACHE_PARAMETERS_LEVEL_1 = 1,                                                                                                                                                          // Colorize: green
    DETERMINISTIC_CACHE_PARAMETERS_LEVEL_2 = 2,                                                                                                                                                          // Colorize: green
    DETERMINISTIC_CACHE_PARAMETERS_LEVEL_3 = 3,                                                                                                                                                          // Colorize: green
    DETERMINISTIC_CACHE_PARAMETERS_LEVEL_4 = 4,                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
    // CpuidLeaf::X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY                                                                                                                                                 // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY_THREADS_PER_CORE = 0,                                                                                                                                                   // Colorize: green
    X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY_THREADS          = 1,                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
    // CpuidLeaf::XSAVE_FEATURES                                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    XSAVE_FEATURES_PROCESSOR_EXTENDED_STATE_ENUMERATION_0 = 0,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_PROCESSOR_EXTENDED_STATE_ENUMERATION_1 = 1, // TODO: Need to check the name                                                                                                                                          // Colorize: green
    XSAVE_FEATURES_AVX                                    = 2,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_MPX_BOUND_REGISTERS                    = 3,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_MPX_BOUND_CONFIG_AND_STATUS_REGISTERS  = 4,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_AVX512_OPMASK                          = 5,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_AVX512_ZMM_FROM_0_TO_15                = 6,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_AVX512_ZMM_FROM_16_TO_31               = 7,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_PT                                     = 8,                                                                                                                                           // Colorize: green
    XSAVE_FEATURES_PKRU                                   = 9,                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
    // CpuidLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING                                                                                                                                              // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING            = 0,                                                                                                                                              // Colorize: green
    RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING_L3_CACHE   = 1,                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
    // CpuidLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION                                                                                                                                             // Colorize: green
    //                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION                  = 0,                                                                                                                                                     // Colorize: green
    RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_L3_CACHE         = 1,                                                                                                                                                    // Colorize: green
    RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_L2_CACHE         = 2,                                                                                                                                                    // Colorize: green
    RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_MEMORY_BANDWIDTH = 3                                                                                                                                                     // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToString(CpuidLeaf leaf, CpuidSubLeaf subLeaf) // TEST: NO                                                                                                                         // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | leaf = %u, subLeaf = %u", leaf, subLeaf)); // Commented to avoid bad looking logs                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (leaf)                                                                                                                                                                                      // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case CpuidLeaf::DETERMINISTIC_CACHE_PARAMETERS:                                                                                                                                                  // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            switch (subLeaf)                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                case CpuidSubLeaf::DETERMINISTIC_CACHE_PARAMETERS_LEVEL_0: return "DETERMINISTIC_CACHE_PARAMETERS_LEVEL_0";                                                                              // Colorize: green
                case CpuidSubLeaf::DETERMINISTIC_CACHE_PARAMETERS_LEVEL_1: return "DETERMINISTIC_CACHE_PARAMETERS_LEVEL_1";                                                                              // Colorize: green
                case CpuidSubLeaf::DETERMINISTIC_CACHE_PARAMETERS_LEVEL_2: return "DETERMINISTIC_CACHE_PARAMETERS_LEVEL_2";                                                                              // Colorize: green
                case CpuidSubLeaf::DETERMINISTIC_CACHE_PARAMETERS_LEVEL_3: return "DETERMINISTIC_CACHE_PARAMETERS_LEVEL_3";                                                                              // Colorize: green
                case CpuidSubLeaf::DETERMINISTIC_CACHE_PARAMETERS_LEVEL_4: return "DETERMINISTIC_CACHE_PARAMETERS_LEVEL_4";                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                default: return "UNKNOWN";                                                                                                                                                               // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        break;                                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        case CpuidLeaf::X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY:                                                                                                                                          // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            switch (subLeaf)                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                case CpuidSubLeaf::X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY_THREADS_PER_CORE: return "X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY_THREADS_PER_CORE";                                            // Colorize: green
                case CpuidSubLeaf::X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY_THREADS:          return "X2APIC_FEATURES_AND_PROCESSOR_TOPOLOGY_THREADS";                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                default: return "UNKNOWN";                                                                                                                                                               // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        break;                                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        case CpuidLeaf::XSAVE_FEATURES:                                                                                                                                                                  // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            switch (subLeaf)                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_PROCESSOR_EXTENDED_STATE_ENUMERATION_0: return "XSAVE_FEATURES_PROCESSOR_EXTENDED_STATE_ENUMERATION_0";                                                // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_PROCESSOR_EXTENDED_STATE_ENUMERATION_1: return "XSAVE_FEATURES_PROCESSOR_EXTENDED_STATE_ENUMERATION_1";                                                // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_AVX:                                    return "XSAVE_FEATURES_AVX";                                                                                   // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_MPX_BOUND_REGISTERS:                    return "XSAVE_FEATURES_MPX_BOUND_REGISTERS";                                                                   // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_MPX_BOUND_CONFIG_AND_STATUS_REGISTERS:  return "XSAVE_FEATURES_MPX_BOUND_CONFIG_AND_STATUS_REGISTERS";                                                 // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_AVX512_OPMASK:                          return "XSAVE_FEATURES_AVX512_OPMASK";                                                                         // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_AVX512_ZMM_FROM_0_TO_15:                return "XSAVE_FEATURES_AVX512_ZMM_FROM_0_TO_15";                                                               // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_AVX512_ZMM_FROM_16_TO_31:               return "XSAVE_FEATURES_AVX512_ZMM_FROM_16_TO_31";                                                              // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_PT:                                     return "XSAVE_FEATURES_PT";                                                                                    // Colorize: green
                case CpuidSubLeaf::XSAVE_FEATURES_PKRU:                                   return "XSAVE_FEATURES_PKRU";                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                default: return "UNKNOWN";                                                                                                                                                               // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        break;                                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        case CpuidLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING:                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            switch (subLeaf)                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                case CpuidSubLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING:          return "RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING";                                                                            // Colorize: green
                case CpuidSubLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING_L3_CACHE: return "RESOURCE_DIRECTOR_TECHNOLOGY_MONITORING_L3_CACHE";                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                default: return "UNKNOWN";                                                                                                                                                               // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        break;                                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        case CpuidLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION:                                                                                                                                                                      // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            switch (subLeaf)                                                                                                                                                                             // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                case CpuidSubLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION:                  return "RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION";                                                           // Colorize: green
                case CpuidSubLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_L3_CACHE:         return "RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_L3_CACHE";                                                  // Colorize: green
                case CpuidSubLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_L2_CACHE:         return "RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_L2_CACHE";                                                  // Colorize: green
                case CpuidSubLeaf::RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_MEMORY_BANDWIDTH: return "RESOURCE_DIRECTOR_TECHNOLOGY_ALLOCATION_MEMORY_BANDWIDTH";                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                default: return "UNKNOWN";                                                                                                                                                               // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        break;                                                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default:                                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            switch (subLeaf)                                                                                                                                                                              // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                case CpuidSubLeaf::NONE: return "NONE";                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                default: return "UNKNOWN";                                                                                                                                                               // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        break;                                                                                                                                                                                           // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToFullString(CpuidLeaf leaf, CpuidSubLeaf subLeaf) // TEST: NO                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | leaf = %u, subLeaf = %u", leaf, subLeaf)); // Commented to avoid bad looking logs                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[50];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%08X (%s)", static_cast<good_U32>(subLeaf), enumToString(leaf, subLeaf));                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_CPU_CPUIDSUBLEAF_H                                                                                                                                                         // Colorize: green
