#ifndef COM_NGOS_SHARED_COMMON_CPU_X86FEATUREWORD_H                                                                                                                                                      // Colorize: green
#define COM_NGOS_SHARED_COMMON_CPU_X86FEATUREWORD_H                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/log/assert.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class X86FeatureWord: good_U8                                                                                                                                                                       // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    CPUID_00000001_ECX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000001_EDX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000006_EAX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000006_ECX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000007_0_EBX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000007_0_ECX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000007_0_EDX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000007_1_EAX,                                                                                                                                                                                  // Colorize: green
    CPUID_00000007_1_EBX,                                                                                                                                                                                  // Colorize: green
    CPUID_0000000D_1_EAX,                                                                                                                                                                                // Colorize: green
    CPUID_0000000F_0_EDX,                                                                                                                                                                                // Colorize: green
    CPUID_0000000F_1_EDX,                                                                                                                                                                                // Colorize: green
    CPUID_00000010_0_EBX,                                                                                                                                                                                // Colorize: green
    CPUID_00000010_1_ECX,                                                                                                                                                                                // Colorize: green
    CPUID_80000001_ECX,                                                                                                                                                                                  // Colorize: green
    CPUID_80000001_EDX,                                                                                                                                                                                  // Colorize: green
    CPUID_80000007_EBX,                                                                                                                                                                                  // Colorize: green
    CPUID_80000007_EDX,                                                                                                                                                                                  // Colorize: green
    CPUID_80000008_EBX,                                                                                                                                                                                  // Colorize: green
    CPUID_8000000A_EDX,                                                                                                                                                                                  // Colorize: green
    CPUID_8000001F_EAX,                                                                                                                                                                                  // Colorize: green
    NGOS_OTHER_FEATURES,                                                                                                                                                                                    // Colorize: green
    MAXIMUM                                                                                                                                                                                              // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToString(X86FeatureWord word) // TEST: NO                                                                                                                                        // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | word = %u", word)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (word)                                                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case X86FeatureWord::CPUID_00000001_ECX:   return "CPUID_00000001_ECX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000001_EDX:   return "CPUID_00000001_EDX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000006_EAX:   return "CPUID_00000006_EAX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000006_ECX:   return "CPUID_00000006_ECX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000007_0_EBX: return "CPUID_00000007_0_EBX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000007_0_ECX: return "CPUID_00000007_0_ECX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000007_0_EDX: return "CPUID_00000007_0_EDX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000007_1_EAX: return "CPUID_00000007_1_EAX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_00000007_1_EBX: return "CPUID_00000007_1_EBX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_0000000D_1_EAX: return "CPUID_0000000D_1_EAX";                                                                                                                        // Colorize: green
        case X86FeatureWord::CPUID_0000000F_0_EDX: return "CPUID_0000000F_0_EDX";                                                                                                                        // Colorize: green
        case X86FeatureWord::CPUID_0000000F_1_EDX: return "CPUID_0000000F_1_EDX";                                                                                                                        // Colorize: green
        case X86FeatureWord::CPUID_00000010_0_EBX: return "CPUID_00000010_0_EBX";                                                                                                                        // Colorize: green
        case X86FeatureWord::CPUID_00000010_1_ECX: return "CPUID_00000010_1_ECX";                                                                                                                        // Colorize: green
        case X86FeatureWord::CPUID_80000001_ECX:   return "CPUID_80000001_ECX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_80000001_EDX:   return "CPUID_80000001_EDX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_80000007_EBX:   return "CPUID_80000007_EBX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_80000007_EDX:   return "CPUID_80000007_EDX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_80000008_EBX:   return "CPUID_80000008_EBX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_8000000A_EDX:   return "CPUID_8000000A_EDX";                                                                                                                          // Colorize: green
        case X86FeatureWord::CPUID_8000001F_EAX:   return "CPUID_8000001F_EAX";                                                                                                                          // Colorize: green
        case X86FeatureWord::NGOS_OTHER_FEATURES:  return "NGOS_OTHER_FEATURES";                                                                                                                            // Colorize: green
        case X86FeatureWord::MAXIMUM:              return "MAXIMUM";                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToFullString(X86FeatureWord word) // TEST: NO                                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | word = %u", word)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[28];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%02X (%s)", static_cast<good_U8>(word), enumToString(word));                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_CPU_X86FEATUREWORD_H                                                                                                                                                    // Colorize: green
