#ifndef COM_NGOS_SHARED_COMMON_CPU_LIB_CPUID_CPUID80000008ECX_H                                                                                                                                          // Colorize: green
#define COM_NGOS_SHARED_COMMON_CPU_LIB_CPUID_CPUID80000008ECX_H                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct Cpuid80000008Ecx // TODO: Validate with spec_verifier                                                                                                                                             // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    union                                                                                                                                                                                                // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        struct                                                                                                                                                                                           // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            good_U32 physicalCores:                    8;                                                                                                                                                // Colorize: green
            good_U32 _reserved:                        4;                                                                                                                                                // Colorize: green
            good_U32 apicIdBits:                       4;                                                                                                                                                // Colorize: green
            good_U32 performanceTimestampCounterSize:  2;                                                                                                                                                // Colorize: green
            good_U32 _reserved2:                       14;                                                                                                                                               // Colorize: green
        };                                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        good_U32 value32;                                                                                                                                                                                // Colorize: green
    };                                                                                                                                                                                                   // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_CPU_LIB_CPUID_CPUID80000008ECX_H                                                                                                                                        // Colorize: green
