#ifndef COM_NGOS_SHARED_UEFIBASE_SECTIONS_SECTION0_COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMICHASSISENTRY_H                                                                                                    // Colorize: green
#define COM_NGOS_SHARED_UEFIBASE_SECTIONS_SECTION0_COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMICHASSISENTRY_H                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <buildconfig.h>                                                                                                                                                                                 // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/dmichassisentry.h>                                                                                                                                        // Colorize: green
#include <com/ngos/shared/uefibase/testengine.h>                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#if NGOS_BUILD_TEST_MODE == OPTION_YES                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
TEST_CASES(section0, com_ngos_shared_common_dmi_lib_entry_dmichassisentry);                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    TEST_CASE("DMI_CHASSIS_CONTAINED_ELEMENT()");                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        DmiChassisEntryV23 entry;                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        good_U8 *buf = reinterpret_cast<good_U8 *>(&entry);                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        entry.containedElementRecordLength = 2;                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(DMI_CHASSIS_CONTAINED_ELEMENT(&entry, 0), (DmiChassisContainedElement *)&buf[21]);                                                                                            // Colorize: green
        TEST_ASSERT_EQUALS(DMI_CHASSIS_CONTAINED_ELEMENT(&entry, 2), (DmiChassisContainedElement *)&buf[25]);                                                                                            // Colorize: green
        TEST_ASSERT_EQUALS(DMI_CHASSIS_CONTAINED_ELEMENT(&entry, 7), (DmiChassisContainedElement *)&buf[35]);                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        entry.containedElementRecordLength = 5;                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        TEST_ASSERT_EQUALS(DMI_CHASSIS_CONTAINED_ELEMENT(&entry, 0), (DmiChassisContainedElement *)&buf[21]);                                                                                            // Colorize: green
        TEST_ASSERT_EQUALS(DMI_CHASSIS_CONTAINED_ELEMENT(&entry, 2), (DmiChassisContainedElement *)&buf[31]);                                                                                            // Colorize: green
        TEST_ASSERT_EQUALS(DMI_CHASSIS_CONTAINED_ELEMENT(&entry, 7), (DmiChassisContainedElement *)&buf[56]);                                                                                            // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
    TEST_CASE_END();                                                                                                                                                                                     // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
TEST_CASES_END();                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif                                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_UEFIBASE_SECTIONS_SECTION0_COM_NGOS_SHARED_COMMON_DMI_ENTRY_DMICHASSISENTRY_H                                                                                                  // Colorize: green
