#ifndef OS_SHARED_COMMON_SRC_COM_NGOS_SHARED_COMMON_UEFI_UEFIMACADDRESS_H
#define OS_SHARED_COMMON_SRC_COM_NGOS_SHARED_COMMON_UEFI_UEFIMACADDRESS_H



#include <com/ngos/shared/common/ngos/types.h>



struct UefiMacAddress
{
    u8 address[32];
};



#endif // OS_SHARED_COMMON_SRC_COM_NGOS_SHARED_COMMON_UEFI_UEFIMACADDRESS_H
