#ifndef OS_SHARED_COMMON_SRC_COM_NGOS_SHARED_COMMON_UEFI_UEFICPUPHYSICALLOCATION_H
#define OS_SHARED_COMMON_SRC_COM_NGOS_SHARED_COMMON_UEFI_UEFICPUPHYSICALLOCATION_H



#include <com/ngos/shared/common/ngos/types.h>



struct UefiCpuPhysicalLocation
{
    u32 package;
    u32 core;
    u32 thread;
};



#endif // OS_SHARED_COMMON_SRC_COM_NGOS_SHARED_COMMON_UEFI_UEFICPUPHYSICALLOCATION_H
