#ifndef OS_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H
#define OS_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H



#include <ngos/status.h>



NgosStatus setupUefiMemoryMap(); // TEST: NO



#endif // OS_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H
