#ifndef COM_NGOS_SHARED_COMMON_CPU_LIB_REGISTERS_X86CR4FLAGS_H                                                                                                                                           // Colorize: green
#define COM_NGOS_SHARED_COMMON_CPU_LIB_REGISTERS_X86CR4FLAGS_H                                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/flags.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/ngos/linkage.h>                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
#include <com/ngos/shared/common/string/string.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
typedef good_U64 x86_cr4_flags;                                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class X86Cr4Flag: x86_cr4_flags // TODO: Validate with spec_verifier                                                                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE                                             = 0,                                                                                                                                                           // Colorize: green
    VIRTUAL_8086_MODE_EXTENSIONS                     = (1ULL << 0),  // If set, enables support for the virtual interrupt flag (VIF) in virtual-8086 mode.                                                          // Colorize: green
    PROTECTED_MODE_VIRTUAL_INTERRUPTS                = (1ULL << 1),  // If set, enables support for the virtual interrupt flag (VIF) in protected mode.                                                             // Colorize: green
    TIME_STAMP_DISABLE                               = (1ULL << 2),  // If set, RDTSC instruction can only be executed when in ring 0, otherwise RDTSC can be used at any privilege level.                          // Colorize: green
    DEBUGGING_EXTENSIONS                             = (1ULL << 3),  // If set, enables debug register based breaks on I/O space access.                                                                            // Colorize: green
    PAGE_SIZE_EXTENSION                              = (1ULL << 4),  // If unset, page size is 4 KiB, else page size is increased to 4 MiB. If PAE is enabled or the processor is in x86-64 long mode this bit is ignored. // Colorize: green
    PHYSICAL_ADDRESS_EXTENSION                       = (1ULL << 5),  // If set, changes page table layout to translate 32-bit virtual addresses into extended 36-bit physical addresses.                            // Colorize: green
    MACHINE_CHECK_EXCEPTION                          = (1ULL << 6),  // If set, enables machine check interrupts to occur.                                                                                          // Colorize: green
    PAGE_GLOBAL_ENABLED                              = (1ULL << 7),  // If set, address translations (PDE or PTE records) may be shared between address spaces.                                                     // Colorize: green
    PERFORMANCE_MONITORING_COUNTER_ENABLE            = (1ULL << 8),  // If set, RDPMC can be executed at any privilege level, else RDPMC can only be used in ring 0.                                                // Colorize: green
    SUPPORT_FXSAVE                                   = (1ULL << 9),  // If set, enables Streaming SIMD Extensions (SSE) instructions and fast FPU save & restore.                                                   // Colorize: green
    SUPPORT_UNMASKED_SSE_EXCEPTIONS                  = (1ULL << 10), // If set, enables unmasked SSE exceptions.                                                                                                    // Colorize: green
    USER_MODE_INSTRUCTION_PREVENTION                 = (1ULL << 11), // If set, the SGDT, SIDT, SLDT, SMSW and STR instructions cannot be executed if CPL > 0.                                                      // Colorize: green
    _57_BIT_LINEAR_ADDRESSES                         = (1ULL << 12), // If set, enables 5-Level Paging.                                                                                                             // Colorize: green
    VIRTUAL_MACHINE_EXTENSIONS_ENABLE                = (1ULL << 13), // see Intel VT-x x86 virtualization.                                                                                                          // Colorize: green
    SAFER_MODE_EXTENSIONS_ENABLE                     = (1ULL << 14), // see Trusted Execution Technology (TXT)                                                                                                      // Colorize: green
    FSGSBASE                                         = (1ULL << 16), // Enables the instructions RDFSBASE, RDGSBASE, WRFSBASE, and WRGSBASE.                                                                        // Colorize: green
    PROCESS_CONTEXT_ID_ENABLE                        = (1ULL << 17), // If set, enables process-context identifiers (PCIDs).                                                                                        // Colorize: green
    SUPPORT_XSAVE                                    = (1ULL << 18), // XSAVE and Processor Extended States Enable                                                                                       // Colorize: green
    SUPERVISOR_MODE_EXECUTION_PROTECTION_ENABLE      = (1ULL << 20), // If set, execution of code in a higher ring generates a fault.                                                                    // Colorize: green
    SUPERVISOR_MODE_ACCESS_PROTECTION_ENABLE         = (1ULL << 21), // If set, access of data in a higher ring generates a fault.                                                                       // Colorize: green
    PROTECTION_KEY_ENABLE                            = (1ULL << 22), // See Intel 64 and IA-32 Architectures Software Developer’s Manual.                                                                // Colorize: green
    CONTROL_FLOW_ENFORCEMENT_TECHNOLOGY              = (1ULL << 23), // If set, enables control-flow enforcement technology.                                                                             // Colorize: green
    ENABLE_PROTECTION_KEYS_FOR_SUPERVISOR_MODE_PAGES = (1ULL << 24)  // If set, each supervisor-mode linear address is associated with a protection key when 4-level or 5-level paging is in use.        // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
DEFINE_FLAGS(X86Cr4Flags, x86_cr4_flags); // TEST: NO                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToString(X86Cr4Flag flag) // TEST: NO                                                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (flag)                                                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case X86Cr4Flag::NONE: return "NONE";                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToFullString(X86Cr4Flag flag) // TEST: NO                                                                                                                                        // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[43];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%08X (%s)", static_cast<x86_cr4_flags>(flag), flagToString(flag));                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToString(const X86Cr4Flags &flags) // TEST: NO                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[184];                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_STRING(res, flags.flags, X86Cr4Flag);                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToFullString(const X86Cr4Flags &flags) // TEST: NO                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[191];                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_FULL_STRING(res, flags.flags, X86Cr4Flag, "0x%016llX");                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_CPU_LIB_REGISTERS_X86CR4FLAGS_H                                                                                                                                         // Colorize: green
