#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_TASK_TASKSTATE_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_TASK_TASKSTATE_H



#include <ngos/types.h>



enum class TaskState: u8
{
    UNRUNNABLE,
    RUNNABLE,
    STOPPED
};



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_TASK_TASKSTATE_H
