#ifndef COM_NGOS_SHARED_COMMON_PCI_LIB_PCIEXPRESSROOTCOMPLEXLINKDECLARATIONLINKADDRESSLINKMEMORYMAPPEDSPACE_H
#define COM_NGOS_SHARED_COMMON_PCI_LIB_PCIEXPRESSROOTCOMPLEXLINKDECLARATIONLINKADDRESSLINKMEMORYMAPPEDSPACE_H



#include <com/ngos/shared/common/ngos/types.h>



struct PciExpressRootComplexLinkDeclarationLinkAndressMemoryMappedSpace
{
    u32 lower32;
    u32 upper32;
};



#endif // COM_NGOS_SHARED_COMMON_PCI_LIB_PCIEXPRESSROOTCOMPLEXLINKDECLARATIONLINKADDRESSLINKMEMORYMAPPEDSPACE_H
