#ifndef COM_NGOS_SHARED_COMMON_PCI_LIB_PCIEXPRESSROOTCOMPLEXLINKDECLARATIONLINKADDRESSLINKMEMORYMAPPEDSPACE_H
#define COM_NGOS_SHARED_COMMON_PCI_LIB_PCIEXPRESSROOTCOMPLEXLINKDECLARATIONLINKADDRESSLINKMEMORYMAPPEDSPACE_H



#include <com/ngos/shared/common/ngos/types.h>



struct PciExpressRootComplexLinkDeclarationLinkAndressMemoryMappedSpace
{
    bad_uint32 lower32;
    bad_uint32 upper32;
};



#endif // COM_NGOS_SHARED_COMMON_PCI_LIB_PCIEXPRESSROOTCOMPLEXLINKDECLARATIONLINKADDRESSLINKMEMORYMAPPEDSPACE_H
