#include <QCoreApplication>                                                                                                                                                                              // Colorize: green
#include <QDateTime>                                                                                                                                                                                     // Colorize: green
#include <QDir>                                                                                                                                                                                          // Colorize: green
#include <QFileInfo>                                                                                                                                                                                     // Colorize: green
#include <QList>                                                                                                                                                                                         // Colorize: green
#include <QProcess>                                                                                                                                                                                      // Colorize: green
#include <QQueue>                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_verifier/other/codeverificationfiletype.h>                                                                                                                              // Colorize: green
#include <com/ngos/devtools/code_verifier/threads/codeworkerthread.h>                                                                                                                                    // Colorize: green
#include <com/ngos/devtools/code_verifier/verifiers/basecodeverifier.h>                                                                                                                                  // Colorize: green
#include <com/ngos/devtools/shared/console/console.h>                                                                                                                                                    // Colorize: green
#include <com/ngos/devtools/shared/utils/git.h>                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void usage()                                                                                                                                                                                             // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Ignore CppAlignmentVerifier [BEGIN]                                                                                                                                                               // Colorize: green
    Console::err(                                                                                                                                                                                        // Colorize: green
                "Usage: code_verifier PATH\n"                                                                                                                                                            // Colorize: green
                "    * PATH - path to file or folder"                                                                                                                                                    // Colorize: green
                );                                                                                                                                                                                       // Colorize: green
    // Ignore CppAlignmentVerifier [END]                                                                                                                                                                 // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
qint32 main(qint32 argc, char *argv[])                                                                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QCoreApplication app(argc, argv);                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    const QStringList &arguments = app.arguments();                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Check arguments                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (arguments.size() != 2)                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            usage();                                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return 1;                                                                                                                                                                                    // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QString targetPath = arguments.at(1);                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Output application info                                                                                                                                                                           // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        Console::out("Code verifier started");                                                                                                                                                           // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out("Parameters:");                                                                                                                                                                     // Colorize: green
        Console::out(QString("PATH = %1").arg(targetPath));                                                                                                                                              // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    qint64 startTime = QDateTime::currentMSecsSinceEpoch();                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<CodeWorkerThread *> workers;                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Start workers                                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < QThread::idealThreadCount(); ++i)                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            CodeWorkerThread *worker = new CodeWorkerThread();                                                                                                                                           // Colorize: green
            worker->start();                                                                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            workers.append(worker);                                                                                                                                                                      // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Iterate over files in targetPath and push them to workers                                                                                                                                         // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QQueue<QFileInfo> files;                                                                                                                                                                         // Colorize: green
        files.enqueue(QFileInfo(targetPath));                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        while (!files.isEmpty())                                                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QFileInfo file = files.dequeue();                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            QString path     = file.absoluteFilePath();                                                                                                                                                  // Colorize: green
            QString fileName = file.fileName();                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (!GIT::isIgnored(file.dir().absolutePath(), path))                                                                                                                                        // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (file.isDir())                                                                                                                                                                        // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (                                                                                                                                                                                 // Colorize: green
                        fileName != ".git"                                                                                                                                                               // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !path.contains("tools/tracers/assets")                                                                                                                                           // Colorize: green
                       )                                                                                                                                                                                 // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        QFileInfoList filesInfo = QDir(path).entryInfoList(QDir::AllEntries | QDir::NoDotAndDotDot);                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                        for (qint64 i = 0; i < filesInfo.size(); ++i)                                                                                                                                    // Colorize: green
                        {                                                                                                                                                                                // Colorize: green
                            files.enqueue(filesInfo.at(i));                                                                                                                                              // Colorize: green
                        }                                                                                                                                                                                // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                else                                                                                                                                                                                     // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (fileName.endsWith(".cpp"))                                                                                                                                                       // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::CPP);                                                                                                                 // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".h"))                                                                                                                                                         // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::H);                                                                                                                   // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".S"))                                                                                                                                                         // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::S);                                                                                                                   // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".php"))                                                                                                                                                       // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::PHP);                                                                                                                 // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName == "Makefile")                                                                                                                                                          // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::MAKEFILE);                                                                                                            // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".pro"))                                                                                                                                                       // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::PRO);                                                                                                                 // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".pri"))                                                                                                                                                       // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::PRI);                                                                                                                 // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".ld"))                                                                                                                                                        // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::LD);                                                                                                                  // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".sh"))                                                                                                                                                        // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::SH);                                                                                                                  // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".includes"))                                                                                                                                                  // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::INCLUDES);                                                                                                            // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (                                                                                                                                                                                 // Colorize: green
                        fileName.endsWith(".xml")                                                                                                                                                        // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".ts")                                                                                                                                                         // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".vbox")                                                                                                                                                       // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".manifest")                                                                                                                                                   // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".creator.shared")                                                                                                                                             // Colorize: green
                       )                                                                                                                                                                                 // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::XML);                                                                                                                 // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".ui"))                                                                                                                                                        // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::UI);                                                                                                                  // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (fileName.endsWith(".qrc"))                                                                                                                                                       // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::QRC);                                                                                                                 // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (                                                                                                                                                                                 // Colorize: green
                        fileName.endsWith(".txt")                                                                                                                                                        // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".md")                                                                                                                                                         // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".sql")                                                                                                                                                        // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".rc")                                                                                                                                                         // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".config")                                                                                                                                                     // Colorize: green
                        ||                                                                                                                                                                               // Colorize: green
                        fileName.endsWith(".files")                                                                                                                                                      // Colorize: green
                       )                                                                                                                                                                                 // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        CodeWorkerThread::pushFile(path, CodeVerificationFileType::TEXT);                                                                                                                // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                    else                                                                                                                                                                                 // Colorize: green
                    if (                                                                                                                                                                                 // Colorize: green
                        !fileName.endsWith(".creator")                                                                                                                                                   // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".creator.user")                                                                                                                                              // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".cflags")                                                                                                                                                    // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".cxxflags")                                                                                                                                                  // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".patch")                                                                                                                                                     // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".qm")                                                                                                                                                        // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".bin")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".dll")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".exe")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".hex")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".gpg")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".pem")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".auth")                                                                                                                                                      // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".ttf")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".ico")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".png")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".jpg")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".gif")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !fileName.endsWith(".svg")                                                                                                                                                       // Colorize: green
                        &&                                                                                                                                                                               // Colorize: green
                        !file.isExecutable()                                                                                                                                                             // Colorize: green
                       )                                                                                                                                                                                 // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        Console::err(QString("Unexpected file extension: %1")                                                                                                                            // Colorize: green
                                                .arg(path)                                                                                                                                               // Colorize: green
                        );                                                                                                                                                                               // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    CodeWorkerThread::noMoreFiles();                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    QList<CodeMessageInfo> warnings;                                                                                                                                                                     // Colorize: green
    QList<CodeMessageInfo> errors;                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Wait for workers and get warnings and errors                                                                                                                                                      // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        for (qint64 i = 0; i < workers.size(); ++i)                                                                                                                                                      // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            CodeWorkerThread *worker = workers.at(i);                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            worker->wait();                                                                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            warnings.append(worker->getWarnings());                                                                                                                                                      // Colorize: green
            errors.append(worker->getErrors());                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            delete worker;                                                                                                                                                                               // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    Console::out(QString("%1 files verified with %2 checks in %3 ms")                                                                                                                                    // Colorize: green
                         .arg(CodeWorkerThread::getAmountOfFiles())                                                                                                                                      // Colorize: green
                         .arg(BaseCodeVerifier::getAmountOfChecks())                                                                                                                                     // Colorize: green
                         .arg(QDateTime::currentMSecsSinceEpoch() - startTime));                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Print warnings                                                                                                                                                                                    // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (!warnings.isEmpty())                                                                                                                                                                         // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            std::sort(warnings.begin(), warnings.end());                                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            for (qint64 i = warnings.size() - 2; i >= 0; --i)                                                                                                                                            // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (warnings.at(i) == warnings.at(i + 1))                                                                                                                                                // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    warnings.removeAt(i);                                                                                                                                                                // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::out("");                                                                                                                                                                            // Colorize: green
            Console::out("Warnings:");                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            for (qint64 i = 0; i < warnings.size(); ++i)                                                                                                                                                 // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                Console::out(warnings.at(i).toString());                                                                                                                                                 // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Print errors                                                                                                                                                                                      // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (!errors.isEmpty())                                                                                                                                                                           // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            std::sort(errors.begin(), errors.end());                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            for (qint64 i = errors.size() - 2; i >= 0; --i)                                                                                                                                              // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (errors.at(i) == errors.at(i + 1))                                                                                                                                                    // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    errors.removeAt(i);                                                                                                                                                                  // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::err("");                                                                                                                                                                            // Colorize: green
            Console::err("Errors:");                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            for (qint64 i = 0; i < errors.size(); ++i)                                                                                                                                                   // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                Console::err(errors.at(i).toString());                                                                                                                                                   // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            Console::err("");                                                                                                                                                                            // Colorize: green
            Console::err(QString("%1 warnings. %2 errors")                                                                                                                                               // Colorize: green
                                    .arg(warnings.size())                                                                                                                                                // Colorize: green
                                    .arg(errors.size())                                                                                                                                                  // Colorize: green
            );                                                                                                                                                                                           // Colorize: green
            Console::err("");                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            return 1;                                                                                                                                                                                    // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Everything is OK                                                                                                                                                                                  // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
        Console::out(QString("%1 warnings. %2 errors")                                                                                                                                                   // Colorize: green
                                .arg(warnings.size())                                                                                                                                                    // Colorize: green
                                .arg(errors.size())                                                                                                                                                      // Colorize: green
        );                                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (warnings.isEmpty())                                                                                                                                                                          // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            Console::out("");                                                                                                                                                                            // Colorize: green
            Console::out("Everything is OK");                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        Console::out("");                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return 0;                                                                                                                                                                                            // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
