#include "codefileinfo.h"                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
CodeFileInfo::CodeFileInfo(const QString &path, CodeVerificationFileType verificationFileType)                                                                                                           // Colorize: green
    : mPath(path)                                                                                                                                                                                        // Colorize: green
    , mVerificationFileType(verificationFileType)                                                                                                                                                        // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
const QString& CodeFileInfo::getPath() const                                                                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return mPath;                                                                                                                                                                                        // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
CodeVerificationFileType CodeFileInfo::getVerificationFileType() const                                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return mVerificationFileType;                                                                                                                                                                        // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
