#ifndef KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPHYPERVISOR_H
#define KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPHYPERVISOR_H



#include <com/ngos/shared/common/ngos/status.h>



NgosStatus setupHypervisor(); // TEST: NO



#endif // KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPHYPERVISOR_H
