#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPE820TABLES_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPE820TABLES_H



#include <ngos/status.h>



NgosStatus setupE820Tables(); // TEST: NO



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_A_EARLY_MAIN_SETUPE820TABLES_H
