#ifndef KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPMEMORYMANAGER_H
#define KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPMEMORYMANAGER_H



#include <common/src/com/ngos/shared/common/ngos/status.h>



NgosStatus setupMemoryManager(); // TEST: NO



#endif // KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPMEMORYMANAGER_H
