#ifndef KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H
#define KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H



#include <ngos/status.h>



NgosStatus setupUefiMemoryMap(); // TEST: NO



#endif // KERNEL_SRC_COM_NGOS_KERNEL_A_EARLY_MAIN_SETUPUEFIMEMORYMAP_H
