#ifndef OS_SHARED_UEFIBASE_SRC_BITS64_MAIN_EARLYINITIALIZATION_H
#define OS_SHARED_UEFIBASE_SRC_BITS64_MAIN_EARLYINITIALIZATION_H



#include <ngos/status.h>



NgosStatus earlyInitialization(u64 kernelLocation); // TEST: NO



#endif // OS_SHARED_UEFIBASE_SRC_BITS64_MAIN_EARLYINITIALIZATION_H
