#ifndef OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_CPU_HOTPLUG_CPUHOTPLUGSTATE_H
#define OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_CPU_HOTPLUG_CPUHOTPLUGSTATE_H



#include <ngos/types.h>



enum class CpuHotplugState: u8
{
    OFFLINE,
    BP_PREPARE_DYNAMIC,
    BP_PREPARE_DYNAMIC_END = BP_PREPARE_DYNAMIC + 10,
    AP_ONLINE_DYNAMIC,
    AP_ONLINE_DYNAMIC_END  = AP_ONLINE_DYNAMIC + 10,
    ONLINE,
    MAX
};



#endif // OS_SHARED_KERNELBASE_SRC_BITS64_OTHER_CPU_HOTPLUG_CPUHOTPLUGSTATE_H
