#include "teststructureentry.h"                                                                                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
TestStructureEntry::TestStructureEntry(const QString &path, qint64 line, const QString &name, bool bitsDefined)                                                                                          // Colorize: green
    : mPath(path)                                                                                                                                                                                        // Colorize: green
    , mLine(line)                                                                                                                                                                                        // Colorize: green
    , mName(name)                                                                                                                                                                                        // Colorize: green
    , mBitsDefined(bitsDefined)                                                                                                                                                                          // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
bool TestStructureEntry::operator<(const TestStructureEntry &another) const                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Compare mPath                                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (mPath < another.mPath)                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            return true;                                                                                                                                                                                 // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        if (mPath > another.mPath)                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            return false;                                                                                                                                                                                // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    // Compare mLine                                                                                                                                                                                     // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        if (mLine < another.mLine)                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            return true;                                                                                                                                                                                 // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
        else                                                                                                                                                                                             // Colorize: green
        if (mLine > another.mLine)                                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            return false;                                                                                                                                                                                // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return mName < another.mName;                                                                                                                                                                        // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
QString TestStructureEntry::getPath() const                                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return mPath;                                                                                                                                                                                        // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
QString TestStructureEntry::getName() const                                                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return mName;                                                                                                                                                                                        // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
bool TestStructureEntry::isBitsDefined() const                                                                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return mBitsDefined;                                                                                                                                                                                 // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
QString TestStructureEntry::toString() const                                                                                                                                                             // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    return QString("%1 | %2")                                                                                                                                                                            // Colorize: green
            .arg(mPath + ':' + QString::number(mLine + 1), -130, QChar(' '))                                                                                                                             // Colorize: green
            .arg(mName, 50, QChar(' '));                                                                                                                                                                 // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
