#ifndef NETWORKTEST_SRC_COM_NGOS_BOOTLOADER_TOOLS_NETWORKTEST_MAIN_NETWORKTEST_H
#define NETWORKTEST_SRC_COM_NGOS_BOOTLOADER_TOOLS_NETWORKTEST_MAIN_NETWORKTEST_H



#include <ngos/status.h>



class NetworkTest
{
public:
    static NgosStatus init(); // TEST: NO
};



#endif // NETWORKTEST_SRC_COM_NGOS_BOOTLOADER_TOOLS_NETWORKTEST_MAIN_NETWORKTEST_H
