#ifndef COM_NGOS_SHARED_COMMON_PAGE_MACROS_H
#define COM_NGOS_SHARED_COMMON_PAGE_MACROS_H



#define PAGE_SHIFT 12
#define PAGE_SIZE  (1ULL << PAGE_SHIFT)
#define PAGE_MASK  (~(PAGE_SIZE - 1))



#endif // COM_NGOS_SHARED_COMMON_PAGE_MACROS_H
