#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIBIOSCHARACTERISTICSSYSTEMRESERVEDFLAGS_H                                                                                                                 // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIBIOSCHARACTERISTICSSYSTEMRESERVEDFLAGS_H                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/flags.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/ngos/linkage.h>                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
#include <com/ngos/shared/common/string/string.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
typedef u8 dmi_bios_characteristics_system_reserved_flags;                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class DmiBiosCharacteristicsSystemReservedFlag: dmi_bios_characteristics_system_reserved_flags                                                                                                      // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE                                = 0,                                                                                                                                                             // Colorize: green
    BIOS_BOOT_SPECIFICATION_SUPPORTED   = (1ULL << 0),                                                                                                                                                   // Colorize: green
    FUNCTION_KEY_NETWORK_BOOT_SUPPORTED = (1ULL << 1),                                                                                                                                                   // Colorize: green
    TARGET_CONTENT_DISTRIBUTION_ENABLED = (1ULL << 2),                                                                                                                                                   // Colorize: green
    UEFI_SPECIFICATION_SUPPORTED        = (1ULL << 3),                                                                                                                                                   // Colorize: green
    VIRTUAL_MACHINE_SUPPORTED           = (1ULL << 4)                                                                                                                                                    // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
DEFINE_FLAGS(DmiBiosCharacteristicsSystemReservedFlags, dmi_bios_characteristics_system_reserved_flags); // TEST: NO                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToString(DmiBiosCharacteristicsSystemReservedFlag flag) // TEST: NO                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (flag)                                                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case DmiBiosCharacteristicsSystemReservedFlag::NONE:                                return "NONE";                                                                                               // Colorize: green
        case DmiBiosCharacteristicsSystemReservedFlag::BIOS_BOOT_SPECIFICATION_SUPPORTED:   return "BIOS_BOOT_SPECIFICATION_SUPPORTED";                                                                  // Colorize: green
        case DmiBiosCharacteristicsSystemReservedFlag::FUNCTION_KEY_NETWORK_BOOT_SUPPORTED: return "FUNCTION_KEY_NETWORK_BOOT_SUPPORTED";                                                                // Colorize: green
        case DmiBiosCharacteristicsSystemReservedFlag::TARGET_CONTENT_DISTRIBUTION_ENABLED: return "TARGET_CONTENT_DISTRIBUTION_ENABLED";                                                                // Colorize: green
        case DmiBiosCharacteristicsSystemReservedFlag::UEFI_SPECIFICATION_SUPPORTED:        return "UEFI_SPECIFICATION_SUPPORTED";                                                                       // Colorize: green
        case DmiBiosCharacteristicsSystemReservedFlag::VIRTUAL_MACHINE_SUPPORTED:           return "VIRTUAL_MACHINE_SUPPORTED";                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToFullString(DmiBiosCharacteristicsSystemReservedFlag flag) // TEST: NO                                                                                                          // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[43];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%02X (%s)", (dmi_bios_characteristics_system_reserved_flags)flag, flagToString(flag));                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToString(const DmiBiosCharacteristicsSystemReservedFlags &flags) // TEST: NO                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[184];                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_STRING(res, flags.flags, DmiBiosCharacteristicsSystemReservedFlag);                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToFullString(const DmiBiosCharacteristicsSystemReservedFlags &flags) // TEST: NO                                                                                                // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[191];                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_FULL_STRING(res, flags.flags, DmiBiosCharacteristicsSystemReservedFlag, "0x%02X");                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIBIOSCHARACTERISTICSSYSTEMRESERVEDFLAGS_H                                                                                                               // Colorize: green
