#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIMEMORYDEVICETYPEDETAILFLAGS_H                                                                                                                            // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIMEMORYDEVICETYPEDETAILFLAGS_H                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/bits/flags.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/bits/macros.h>                                                                                                                                                          // Colorize: green
#include <com/ngos/shared/common/ngos/linkage.h>                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
#include <com/ngos/shared/common/string/string.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
typedef u16 dmi_memory_device_type_detail_flags;                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class DmiMemoryDeviceTypeDetailFlag: dmi_memory_device_type_detail_flags                                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE          = 0,                                                                                                                                                                                   // Colorize: green
    OTHER         = BIT_1,                                                                                                                                                                         // Colorize: green
    UNKNOWN       = BIT_2,                                                                                                                                                                         // Colorize: green
    FAST_PAGED    = BIT_3,                                                                                                                                                                         // Colorize: green
    STATIC_COLUMN = BIT_4,                                                                                                                                                                         // Colorize: green
    PSEUDO_STATIC = BIT_5,                                                                                                                                                                         // Colorize: green
    RAMBUS        = BIT_6,                                                                                                                                                                         // Colorize: green
    SYNCHRONOUS   = BIT_7,                                                                                                                                                                         // Colorize: green
    CMOS          = BIT_8,                                                                                                                                                                         // Colorize: green
    EDO           = BIT_9,                                                                                                                                                                         // Colorize: green
    WINDOW_DRAM   = BIT_10,                                                                                                                                                                        // Colorize: green
    CACHE_DRAM    = BIT_11,                                                                                                                                                                        // Colorize: green
    NON_VOLATILE  = BIT_12,                                                                                                                                                                        // Colorize: green
    REGISTERED    = BIT_13,                                                                                                                                                                        // Colorize: green
    UNBUFFERED    = BIT_14,                                                                                                                                                                        // Colorize: green
    LRDIMM        = BIT_15                                                                                                                                                                         // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
DEFINE_FLAGS(DmiMemoryDeviceTypeDetailFlags, dmi_memory_device_type_detail_flags); // TEST: NO                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToString(DmiMemoryDeviceTypeDetailFlag flag) // TEST: NO                                                                                                                         // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (flag)                                                                                                                                                                                        // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::NONE:          return "NONE";                                                                                                                                // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::OTHER:         return "OTHER";                                                                                                                               // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::UNKNOWN:       return "UNKNOWN";                                                                                                                             // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::FAST_PAGED:    return "FAST_PAGED";                                                                                                                          // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::STATIC_COLUMN: return "STATIC_COLUMN";                                                                                                                       // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::PSEUDO_STATIC: return "PSEUDO_STATIC";                                                                                                                       // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::RAMBUS:        return "RAMBUS";                                                                                                                              // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::SYNCHRONOUS:   return "SYNCHRONOUS";                                                                                                                         // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::CMOS:          return "CMOS";                                                                                                                                // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::EDO:           return "EDO";                                                                                                                                 // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::WINDOW_DRAM:   return "WINDOW_DRAM";                                                                                                                         // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::CACHE_DRAM:    return "CACHE_DRAM";                                                                                                                          // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::NON_VOLATILE:  return "NON_VOLATILE";                                                                                                                        // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::REGISTERED:    return "REGISTERED";                                                                                                                          // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::UNBUFFERED:    return "UNBUFFERED";                                                                                                                          // Colorize: green
        case DmiMemoryDeviceTypeDetailFlag::LRDIMM:        return "LRDIMM";                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagToFullString(DmiMemoryDeviceTypeDetailFlag flag) // TEST: NO                                                                                                                     // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flag = %u", flag)); // Commented to avoid bad looking logs                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[23];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%04X (%s)", (dmi_memory_device_type_detail_flags)flag, flagToString(flag));                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToString(const DmiMemoryDeviceTypeDetailFlags &flags) // TEST: NO                                                                                                               // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[189];                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_STRING(res, flags.flags, DmiMemoryDeviceTypeDetailFlag);                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* flagsToFullString(const DmiMemoryDeviceTypeDetailFlags &flags) // TEST: NO                                                                                                           // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | flags = ...")); // Commented to avoid bad looking logs                                                                                                                             // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[198];                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    FLAGS_TO_FULL_STRING(res, flags.flags, DmiMemoryDeviceTypeDetailFlag, "0x%04X");                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIMEMORYDEVICETYPEDETAILFLAGS_H                                                                                                                          // Colorize: green
