#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIMEMORYDEVICESIZE_H                                                                                                                                       // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIMEMORYDEVICESIZE_H                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmimemorydevicesizegranularity.h>                                                                                                                     // Colorize: green
#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
#include <com/ngos/shared/common/macro/constants.h>                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
struct DmiMemoryDeviceSize                                                                                                                                                                               // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    inline good_U64 size() const                                                                                                                                                                                      // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        // COMMON_LT(("")); // Commented to avoid too frequent logs                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        switch (granularity)                                                                                                                                                                             // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            case DmiMemoryDeviceSizeGranularity::_1_MEGABYTE: return static_cast<good_U64>(value) * MB;                                                                                                  // Colorize: green
            case DmiMemoryDeviceSizeGranularity::_1_KILOBYTE: return static_cast<good_U64>(value) * KB;                                                                                                  // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            default:                                                                                                                                                                                     // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                COMMON_LF(("Unknown memory device size granularity %s, %s:%u", enumToFullString(granularity), __FILE__, __LINE__));                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                return 0;                                                                                                                                                                                // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
            break;                                                                                                                                                                                       // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        return value;                                                                                                                                                                                    // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    union                                                                                                                                                                                                // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        struct                                                                                                                                                                                           // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            good_U16                       value:       15;                                                                                                                                              // Colorize: green
            DmiMemoryDeviceSizeGranularity granularity: 1;                                                                                                                                               // Colorize: green
        };                                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        good_U16 value16;                                                                                                                                                                                // Colorize: green
    };                                                                                                                                                                                                   // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIMEMORYDEVICESIZE_H                                                                                                                                     // Colorize: green
