#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPROCESSORID_H                                                                                                                                            // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPROCESSORID_H                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <buildconfig.h>                                                                                                                                                                                 // Colorize: green
#include <com/ngos/shared/common/cpu/lib/cpuid/cpuid00000001eax.h>                                                                                                                                       // Colorize: green
#include <com/ngos/shared/common/dmi/lib/entry/lib/dmiprocessorfeatureflags.h>                                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with DmiSpecVerifier [BEGIN] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
#if NGOS_BUILD_ARCH == OPTION_ARCH_X86_64                                                                                                                                                                // Colorize: green
struct DmiProcessorId                                                                                                                                                                                    // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    Cpuid00000001Eax         signature;                                                                                                                                                                  // Colorize: green
    DmiProcessorFeatureFlags featureFlags;                                                                                                                                                               // Colorize: green
} __attribute__((packed));                                                                                                                                                                               // Colorize: green
#else                                                                                                                                                                                                    // Colorize: green
#error DmiProcessorId unsupported for this processor                                                                                                                                                     // Colorize: green
#endif                                                                                                                                                                                                   // Colorize: green
// Verified with DmiSpecVerifier [END] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPROCESSORID_H                                                                                                                                          // Colorize: green
