#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPORTABLEBATTERYDEVICECHEMISTRY_H                                                                                                                         // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPORTABLEBATTERYDEVICECHEMISTRY_H                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/log/assert.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class DmiPortableBatteryDeviceChemistry: u8                                                                                                                                                         // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE                 = 0,                                                                                                                                                                            // Colorize: green
    OTHER                = 1,                                                                                                                                                                            // Colorize: green
    UNKNOWN              = 2,                                                                                                                                                                            // Colorize: green
    LEAD_ACID            = 3,                                                                                                                                                                            // Colorize: green
    NICKEL_CADMIUM       = 4,                                                                                                                                                                            // Colorize: green
    NICKEL_METAL_HYDRIDE = 5,                                                                                                                                                                            // Colorize: green
    LITHIUM_ION          = 6,                                                                                                                                                                            // Colorize: green
    ZINC_AIR             = 7,                                                                                                                                                                            // Colorize: green
    LITHIUM_POLYMER      = 8                                                                                                                                                                             // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToString(DmiPortableBatteryDeviceChemistry chemistry) // TEST: NO                                                                                                                // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | chemistry = %u", chemistry)); // Commented to avoid bad looking logs                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (chemistry)                                                                                                                                                                                   // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case DmiPortableBatteryDeviceChemistry::NONE:                 return "NONE";                                                                                                                     // Colorize: green
        case DmiPortableBatteryDeviceChemistry::OTHER:                return "OTHER";                                                                                                                    // Colorize: green
        case DmiPortableBatteryDeviceChemistry::UNKNOWN:              return "UNKNOWN";                                                                                                                  // Colorize: green
        case DmiPortableBatteryDeviceChemistry::LEAD_ACID:            return "LEAD_ACID";                                                                                                                // Colorize: green
        case DmiPortableBatteryDeviceChemistry::NICKEL_CADMIUM:       return "NICKEL_CADMIUM";                                                                                                           // Colorize: green
        case DmiPortableBatteryDeviceChemistry::NICKEL_METAL_HYDRIDE: return "NICKEL_METAL_HYDRIDE";                                                                                                     // Colorize: green
        case DmiPortableBatteryDeviceChemistry::LITHIUM_ION:          return "LITHIUM_ION";                                                                                                              // Colorize: green
        case DmiPortableBatteryDeviceChemistry::ZINC_AIR:             return "ZINC_AIR";                                                                                                                 // Colorize: green
        case DmiPortableBatteryDeviceChemistry::LITHIUM_POLYMER:      return "LITHIUM_POLYMER";                                                                                                          // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToFullString(DmiPortableBatteryDeviceChemistry chemistry) // TEST: NO                                                                                                            // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | chemistry = %u", chemistry)); // Commented to avoid bad looking logs                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[28];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%02X (%s)", (u8)chemistry, enumToString(chemistry));                                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPORTABLEBATTERYDEVICECHEMISTRY_H                                                                                                                       // Colorize: green
