#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPROCESSORFAMILY_H                                                                                                                                        // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPROCESSORFAMILY_H                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/log/assert.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
// Verified with DmiSpecVerifier [BEGIN] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                               // Colorize: green
enum class DmiProcessorFamily: good_U8                                                                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE                                   = 0,                                                                                                                                                          // Colorize: green
    OTHER                                  = 0x01, // Other                                                                                                                                              // Colorize: green
    UNKNOWN                                = 0x02, // Unknown                                                                                                                                            // Colorize: green
    _8086                                  = 0x03, // 8086                                                                                                                                               // Colorize: green
    _80286                                 = 0x04, // 80286                                                                                                                                              // Colorize: green
    INTEL_386                              = 0x05, // Intel386(TM) processor                                                                                                                             // Colorize: green
    INTEL_486                              = 0x06, // Intel486(TM) processor                                                                                                                             // Colorize: green
    _8087                                  = 0x07, // 8087                                                                                                                                               // Colorize: green
    _80287                                 = 0x08, // 80287                                                                                                                                              // Colorize: green
    _80387                                 = 0x09, // 80387                                                                                                                                              // Colorize: green
    _80487                                 = 0x0A, // 80487                                                                                                                                              // Colorize: green
    PENTIUM                                = 0x0B, // Intel(R) Pentium(R) processor                                                                                                                      // Colorize: green
    PENTIUM_PRO                            = 0x0C, // Pentium(R) Pro processor                                                                                                                           // Colorize: green
    PENTIUM_II                             = 0x0D, // Pentium(R) II processor                                                                                                                            // Colorize: green
    PENTIUM_MMX                            = 0x0E, // Pentium(R) processor with MMX(TM) technology                                                                                                       // Colorize: green
    CELERON                                = 0x0F, // Intel(R) Celeron(R) processor                                                                                                                      // Colorize: green
    PENTIUM_II_XEON                        = 0x10, // Pentium(R) II Xeon(TM) processor                                                                                                                   // Colorize: green
    PENTIUM_III                            = 0x11, // Pentium(R) III processor                                                                                                                           // Colorize: green
    M1                                     = 0x12, // M1 Family                                                                                                                                          // Colorize: green
    M2                                     = 0x13, // M2 Family                                                                                                                                          // Colorize: green
    INTEL_CELERON_M                        = 0x14, // Intel(R) Celeron(R) M processor                                                                                                                    // Colorize: green
    INTEL_PENTIUM_4_HT                     = 0x15, // Intel(R) Pentium(R) 4 HT processor                                                                                                                 // Colorize: green
    AMD_DURON                              = 0x18, // AMD Duron(TM) Processor Family [1]                                                                                                                 // Colorize: green
    K5                                     = 0x19, // K5 Family [1]                                                                                                                                      // Colorize: green
    K6                                     = 0x1A, // K6 Family [1]                                                                                                                                      // Colorize: green
    K6_2                                   = 0x1B, // K6-2 [1]                                                                                                                                           // Colorize: green
    K6_3                                   = 0x1C, // K6-3 [1]                                                                                                                                           // Colorize: green
    AMD_ATHLON                             = 0x1D, // AMD Athlon(TM) Processor Family [1]                                                                                                                // Colorize: green
    AMD_29000                              = 0x1E, // AMD29000 Family                                                                                                                                    // Colorize: green
    K6_2_PLUS                              = 0x1F, // K6-2+                                                                                                                                              // Colorize: green
    POWER_PC                               = 0x20, // Power PC Family                                                                                                                                    // Colorize: green
    POWER_PC_601                           = 0x21, // Power PC 601                                                                                                                                       // Colorize: green
    POWER_PC_603                           = 0x22, // Power PC 603                                                                                                                                       // Colorize: green
    POWER_PC_603_PLUS                      = 0x23, // Power PC 603+                                                                                                                                      // Colorize: green
    POWER_PC_604                           = 0x24, // Power PC 604                                                                                                                                       // Colorize: green
    POWER_PC_620                           = 0x25, // Power PC 620                                                                                                                                       // Colorize: green
    POWER_PC_X704                          = 0x26, // Power PC x704                                                                                                                                      // Colorize: green
    POWER_PC_750                           = 0x27, // Power PC 750                                                                                                                                       // Colorize: green
    INTEL_CORE_DUO                         = 0x28, // Intel(R) Core(TM) Duo processor                                                                                                                    // Colorize: green
    INTEL_CORE_DUO_MOBILE                  = 0x29, // Intel(R) Core(TM) Duo mobile processor                                                                                                             // Colorize: green
    INTEL_CORE_SOLO_MOBILE                 = 0x2A, // Intel(R) Core(TM) Solo mobile processor                                                                                                            // Colorize: green
    INTEL_ATOM                             = 0x2B, // Intel(R) Atom(TM) processor                                                                                                                        // Colorize: green
    INTEL_CORE_M                           = 0x2C, // Intel(R) Core(TM) M processor                                                                                                                      // Colorize: green
    INTEL_CORE_M3                          = 0x2D, // Intel(R) Core(TM) m3 processor                                                                                                                     // Colorize: green
    INTEL_CORE_M5                          = 0x2E, // Intel(R) Core(TM) m5 processor                                                                                                                     // Colorize: green
    INTEL_CORE_M7                          = 0x2F, // Intel(R) Core(TM) m7 processor                                                                                                                     // Colorize: green
    ALPHA                                  = 0x30, // Alpha Family [2]                                                                                                                                   // Colorize: green
    ALPHA_21064                            = 0x31, // Alpha 21064                                                                                                                                        // Colorize: green
    ALPHA_21066                            = 0x32, // Alpha 21066                                                                                                                                        // Colorize: green
    ALPHA_21164                            = 0x33, // Alpha 21164                                                                                                                                        // Colorize: green
    ALPHA_21164_PC                         = 0x34, // Alpha 21164PC                                                                                                                                      // Colorize: green
    ALPHA_21164A                           = 0x35, // Alpha 21164a                                                                                                                                       // Colorize: green
    ALPHA_21264                            = 0x36, // Alpha 21264                                                                                                                                        // Colorize: green
    ALPHA_21364                            = 0x37, // Alpha 21364                                                                                                                                        // Colorize: green
    AMD_TURION_II_ULTRA_DUAL_CORE_MOBILE_M = 0x38, // AMD Turion(TM) II Ultra Dual-Core Mobile M Processor Family                                                                                        // Colorize: green
    AMD_TURION_II_DUAL_CORE_MOBILE_M       = 0x39, // AMD Turion(TM) II Dual-Core Mobile M Processor Family                                                                                              // Colorize: green
    AMD_ATHLON_II_DUAL_CORE_M              = 0x3A, // AMD Athlon(TM) II Dual-Core M Processor Family                                                                                                     // Colorize: green
    AMD_OPTERON_6100_SERIES                = 0x3B, // AMD Opteron(TM) 6100 Series Processor                                                                                                              // Colorize: green
    AMD_OPTERON_4100_SERIES                = 0x3C, // AMD Opteron(TM) 4100 Series Processor                                                                                                              // Colorize: green
    AMD_OPTERON_6200_SERIES                = 0x3D, // AMD Opteron(TM) 6200 Series Processor                                                                                                              // Colorize: green
    AMD_OPTERON_4200_SERIES                = 0x3E, // AMD Opteron(TM) 4200 Series Processor                                                                                                              // Colorize: green
    AMD_FX_SERIES                          = 0x3F, // AMD FX(TM) Series Processor                                                                                                                        // Colorize: green
    MIPS                                   = 0x40, // MIPS Family                                                                                                                                        // Colorize: green
    MIPS_R4000                             = 0x41, // MIPS R4000                                                                                                                                         // Colorize: green
    MIPS_R4200                             = 0x42, // MIPS R4200                                                                                                                                         // Colorize: green
    MIPS_R4400                             = 0x43, // MIPS R4400                                                                                                                                         // Colorize: green
    MIPS_R4600                             = 0x44, // MIPS R4600                                                                                                                                         // Colorize: green
    MIPS_R10000                            = 0x45, // MIPS R10000                                                                                                                                        // Colorize: green
    AMD_C_SERIES                           = 0x46, // AMD C-Series Processor                                                                                                                             // Colorize: green
    AMD_E_SERIES                           = 0x47, // AMD E-Series Processor                                                                                                                             // Colorize: green
    AMD_A_SERIES                           = 0x48, // AMD A-Series Processor                                                                                                                             // Colorize: green
    AMD_G_SERIES                           = 0x49, // AMD G-Series Processor                                                                                                                             // Colorize: green
    AMD_Z_SERIES                           = 0x4A, // AMD Z-Series Processor                                                                                                                             // Colorize: green
    AMD_R_SERIES                           = 0x4B, // AMD R-Series Processor                                                                                                                             // Colorize: green
    AMD_OPTERON_4300_SERIES                = 0x4C, // AMD Opteron(TM) 4300 Series Processor                                                                                                              // Colorize: green
    AMD_OPTERON_6300_SERIES                = 0x4D, // AMD Opteron(TM) 6300 Series Processor                                                                                                              // Colorize: green
    AMD_OPTERON_3300_SERIES                = 0x4E, // AMD Opteron(TM) 3300 Series Processor                                                                                                              // Colorize: green
    AMD_FIRE_PRO_SERIES                    = 0x4F, // AMD FirePro(TM) Series Processor                                                                                                                   // Colorize: green
    SPARC                                  = 0x50, // SPARC Family                                                                                                                                       // Colorize: green
    SUPER_SPARC                            = 0x51, // SuperSPARC                                                                                                                                         // Colorize: green
    MICRO_SPARC_II                         = 0x52, // microSPARC II                                                                                                                                      // Colorize: green
    MICRO_SPARC_IIEP                       = 0x53, // microSPARC IIep                                                                                                                                    // Colorize: green
    ULTRA_SPARC                            = 0x54, // UltraSPARC                                                                                                                                         // Colorize: green
    ULTRA_SPARC_II                         = 0x55, // UltraSPARC II                                                                                                                                      // Colorize: green
    ULTRA_SPARC_III                        = 0x56, // UltraSPARC Iii                                                                                                                                     // Colorize: green
    ULTRA_SPARC_III_2                      = 0x57, // UltraSPARC III                                                                                                                                     // Colorize: green
    ULTRA_SPARC_IIII                       = 0x58, // UltraSPARC IIIi                                                                                                                                    // Colorize: green
    _68040                                 = 0x60, // 68040 Family                                                                                                                                       // Colorize: green
    _68XXX                                 = 0x61, // 68xxx                                                                                                                                              // Colorize: green
    _68000                                 = 0x62, // 68000                                                                                                                                              // Colorize: green
    _68010                                 = 0x63, // 68010                                                                                                                                              // Colorize: green
    _68020                                 = 0x64, // 68020                                                                                                                                              // Colorize: green
    _68030                                 = 0x65, // 68030                                                                                                                                              // Colorize: green
    AMD_ATHLON_X4_QUAD_CORE                = 0x66, // AMD Athlon(TM) X4 Quad-Core Processor Family                                                                                                       // Colorize: green
    AMD_OPTERON_X1000_SERIES               = 0x67, // AMD Opteron(TM) X1000 Series Processor                                                                                                             // Colorize: green
    AMD_OPTERON_X2000_SERIES               = 0x68, // AMD Opteron(TM) X2000 Series APU                                                                                                                   // Colorize: green
    AMD_OPTERON_A_SERIES                   = 0x69, // AMD Opteron(TM) A-Series Processor                                                                                                                 // Colorize: green
    AMD_OPTERON_X3000_SERIES               = 0x6A, // AMD Opteron(TM) X3000 Series APU                                                                                                                   // Colorize: green
    AMD_ZEN                                = 0x6B, // AMD Zen Processor Family                                                                                                                           // Colorize: green
    HOBBIT                                 = 0x70, // Hobbit Family                                                                                                                                      // Colorize: green
    CRUSOE_TM5000                          = 0x78, // Crusoe(TM) TM5000 Family                                                                                                                           // Colorize: green
    CRUSOE_TM3000                          = 0x79, // Crusoe(TM) TM3000 Family                                                                                                                           // Colorize: green
    EFFICEON_TM8000                        = 0x7A, // Efficeon(TM) TM8000 Family                                                                                                                         // Colorize: green
    WEITEK                                 = 0x80, // Weitek                                                                                                                                             // Colorize: green
    ITANIUM                                = 0x82, // Itanium(TM) processor                                                                                                                              // Colorize: green
    AMD_ATHLON_64                          = 0x83, // AMD Athlon(TM) 64 Processor Family                                                                                                                 // Colorize: green
    AMD_OPTERON                            = 0x84, // AMD Opteron(TM) Processor Family                                                                                                                   // Colorize: green
    AMD_SEMPRON                            = 0x85, // AMD Sempron(TM) Processor Family                                                                                                                   // Colorize: green
    AMD_TURION_64_MOBILE                   = 0x86, // AMD Turion(TM) 64 Mobile Technology                                                                                                                // Colorize: green
    DUAL_CORE_AMD_OPTERON                  = 0x87, // Dual-Core AMD Opteron(TM) Processor Family                                                                                                         // Colorize: green
    AMD_ATHLON_64_X2_DUAL_CORE             = 0x88, // AMD Athlon(TM) 64 X2 Dual-Core Processor Family                                                                                                    // Colorize: green
    AMD_TURION_64_X2_MOBILE                = 0x89, // AMD Turion(TM) 64 X2 Mobile Technology                                                                                                             // Colorize: green
    QUAD_CORE_AMD_OPTERON                  = 0x8A, // Quad-Core AMD Opteron(TM) Processor Family                                                                                                         // Colorize: green
    THIRD_GENERATION_AMD_OPTERON           = 0x8B, // Third-Generation AMD Opteron(TM) Processor Family                                                                                                  // Colorize: green
    AMD_PHENOM_FX_QUAD_CORE                = 0x8C, // AMD Phenom(TM) FX Quad-Core Processor Family                                                                                                       // Colorize: green
    AMD_PHENOM_X4_QUAD_CORE                = 0x8D, // AMD Phenom(TM) X4 Quad-Core Processor Family                                                                                                       // Colorize: green
    AMD_PHENOM_X2_DUAL_CORE                = 0x8E, // AMD Phenom(TM) X2 Dual-Core Processor Family                                                                                                       // Colorize: green
    AMD_ATHLON_X2_DUAL_CORE                = 0x8F, // AMD Athlon(TM) X2 Dual-Core Processor Family                                                                                                       // Colorize: green
    PA_RISC                                = 0x90, // PA-RISC Family                                                                                                                                     // Colorize: green
    PA_RISC_8500                           = 0x91, // PA-RISC 8500                                                                                                                                       // Colorize: green
    PA_RISC_8000                           = 0x92, // PA-RISC 8000                                                                                                                                       // Colorize: green
    PA_RISC_7300_LC                        = 0x93, // PA-RISC 7300LC                                                                                                                                     // Colorize: green
    PA_RISC_7200                           = 0x94, // PA-RISC 7200                                                                                                                                       // Colorize: green
    PA_RISC_7100_LC                        = 0x95, // PA-RISC 7100LC                                                                                                                                     // Colorize: green
    PA_RISC_7100                           = 0x96, // PA-RISC 7100                                                                                                                                       // Colorize: green
    V30                                    = 0xA0, // V30 Family                                                                                                                                         // Colorize: green
    QUAD_CORE_INTEL_XEON_3200_SERIES       = 0xA1, // Quad-Core Intel(R) Xeon(R) processor 3200 Series                                                                                                   // Colorize: green
    DUAL_CORE_INTEL_XEON_3000_SERIES       = 0xA2, // Dual-Core Intel(R) Xeon(R) processor 3000 Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_5300_SERIES       = 0xA3, // Quad-Core Intel(R) Xeon(R) processor 5300 Series                                                                                                   // Colorize: green
    DUAL_CORE_INTEL_XEON_5100_SERIES       = 0xA4, // Dual-Core Intel(R) Xeon(R) processor 5100 Series                                                                                                   // Colorize: green
    DUAL_CORE_INTEL_XEON_5000_SERIES       = 0xA5, // Dual-Core Intel(R) Xeon(R) processor 5000 Series                                                                                                   // Colorize: green
    DUAL_CORE_INTEL_XEON_LV                = 0xA6, // Dual-Core Intel(R) Xeon(R) processor LV                                                                                                            // Colorize: green
    DUAL_CORE_INTEL_XEON_ULV               = 0xA7, // Dual-Core Intel(R) Xeon(R) processor ULV                                                                                                           // Colorize: green
    DUAL_CORE_INTEL_XEON_7100_SERIES       = 0xA8, // Dual-Core Intel(R) Xeon(R) processor 7100 Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_5400_SERIES       = 0xA9, // Quad-Core Intel(R) Xeon(R) processor 5400 Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON                   = 0xAA, // Quad-Core Intel(R) Xeon(R) processor                                                                                                               // Colorize: green
    DUAL_CORE_INTEL_XEON_5200_SERIES       = 0xAB, // Dual-Core Intel(R) Xeon(R) processor 5200 Series                                                                                                   // Colorize: green
    DUAL_CORE_INTEL_XEON_7200_SERIES       = 0xAC, // Dual-Core Intel(R) Xeon(R) processor 7200 Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_7300_SERIES       = 0xAD, // Quad-Core Intel(R) Xeon(R) processor 7300 Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_7400_SERIES       = 0xAE, // Quad-Core Intel(R) Xeon(R) processor 7400 Series                                                                                                   // Colorize: green
    MULTI_CORE_INTEL_XEON_7400_SERIES      = 0xAF, // Multi-Core Intel(R) Xeon(R) processor 7400 Series                                                                                                  // Colorize: green
    PENTIUM_III_XEON                       = 0xB0, // Pentium(R) III Xeon(TM) processor                                                                                                                  // Colorize: green
    PENTIUM_III_SPEED_STEP                 = 0xB1, // Pentium(R) III Processor with Intel(R) SpeedStep(TM) Technology                                                                                    // Colorize: green
    PENTIUM_4                              = 0xB2, // Pentium(R) 4 Processor                                                                                                                             // Colorize: green
    INTEL_XEON                             = 0xB3, // Intel(R) Xeon(R) processor                                                                                                                         // Colorize: green
    AS400                                  = 0xB4, // AS400 Family                                                                                                                                       // Colorize: green
    INTEL_XEON_MP                          = 0xB5, // Intel(R) Xeon(TM) processor MP                                                                                                                     // Colorize: green
    AMD_ATHLON_XP                          = 0xB6, // AMD Athlon(TM) XP Processor Family                                                                                                                 // Colorize: green
    AMD_ATHLON_MP                          = 0xB7, // AMD Athlon(TM) MP Processor Family                                                                                                                 // Colorize: green
    INTEL_ITANIUM_2                        = 0xB8, // Intel(R) Itanium(R) 2 processor                                                                                                                    // Colorize: green
    INTEL_PENTIUM_M                        = 0xB9, // Intel(R) Pentium(R) M processor                                                                                                                    // Colorize: green
    INTEL_CELERON_D                        = 0xBA, // Intel(R) Celeron(R) D processor                                                                                                                    // Colorize: green
    INTEL_PENTIUM_D                        = 0xBB, // Intel(R) Pentium(R) D processor                                                                                                                    // Colorize: green
    INTEL_PENTIUM_EXTREME                  = 0xBC, // Intel(R) Pentium(R) Processor Extreme Edition                                                                                                      // Colorize: green
    INTEL_CORE_SOLO                        = 0xBD, // Intel(R) Core(TM) Solo Processor                                                                                                                   // Colorize: green
    INTEL_CORE_2_DUO                       = 0xBF, // Intel(R) Core(TM) 2 Duo Processor                                                                                                                  // Colorize: green
    INTEL_CORE_2_SOLO                      = 0xC0, // Intel(R) Core(TM) 2 Solo processor                                                                                                                 // Colorize: green
    INTEL_CORE_2_EXTREME                   = 0xC1, // Intel(R) Core(TM) 2 Extreme processor                                                                                                              // Colorize: green
    INTEL_CORE_2_QUAD                      = 0xC2, // Intel(R) Core(TM) 2 Quad processor                                                                                                                 // Colorize: green
    INTEL_CORE_2_EXTREME_MOBILE            = 0xC3, // Intel(R) Core(TM) 2 Extreme mobile processor                                                                                                       // Colorize: green
    INTEL_CORE_2_DUO_MOBILE                = 0xC4, // Intel(R) Core(TM) 2 Duo mobile processor                                                                                                           // Colorize: green
    INTEL_CORE_2_SOLO_MOBILE               = 0xC5, // Intel(R) Core(TM) 2 Solo mobile processor                                                                                                          // Colorize: green
    INTEL_CORE_I7                          = 0xC6, // Intel(R) Core(TM) i7 processor                                                                                                                     // Colorize: green
    DUAL_CORE_INTEL_CELERON                = 0xC7, // Dual-Core Intel(R) Celeron(R) processor                                                                                                            // Colorize: green
    IBM390                                 = 0xC8, // IBM390 Family                                                                                                                                      // Colorize: green
    G4                                     = 0xC9, // G4                                                                                                                                                 // Colorize: green
    G5                                     = 0xCA, // G5                                                                                                                                                 // Colorize: green
    G6                                     = 0xCB, // ESA/390 G6                                                                                                                                         // Colorize: green
    Z_ARCHITECTURE                         = 0xCC, // z/Architecture base                                                                                                                                // Colorize: green
    INTEL_CORE_I5                          = 0xCD, // Intel(R) Core(TM) i5 processor                                                                                                                     // Colorize: green
    INTEL_CORE_I3                          = 0xCE, // Intel(R) Core(TM) i3 processor                                                                                                                     // Colorize: green
    INTEL_CORE_I9                          = 0xCF, // Intel(R) Core(TM) i9 processor                                                                                                                     // Colorize: green
    VIA_C7_M                               = 0xD2, // VIA C7(TM)-M Processor Family                                                                                                                      // Colorize: green
    VIA_C7_D                               = 0xD3, // VIA C7(TM)-D Processor Family                                                                                                                      // Colorize: green
    VIA_C7                                 = 0xD4, // VIA C7(TM) Processor Family                                                                                                                        // Colorize: green
    VIA_EDEN                               = 0xD5, // VIA Eden(TM) Processor Family                                                                                                                      // Colorize: green
    MULTI_CORE_INTEL_XEON                  = 0xD6, // Multi-Core Intel(R) Xeon(R) processor                                                                                                              // Colorize: green
    DUAL_CORE_INTEL_XEON_3XXX_SERIES       = 0xD7, // Dual-Core Intel(R) Xeon(R) processor 3xxx Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_3XXX_SERIES       = 0xD8, // Quad-Core Intel(R) Xeon(R) processor 3xxx Series                                                                                                   // Colorize: green
    VIA_NANO                               = 0xD9, // VIA Nano(TM) Processor Family                                                                                                                      // Colorize: green
    DUAL_CORE_INTEL_XEON_5XXX_SERIES       = 0xDA, // Dual-Core Intel(R) Xeon(R) processor 5xxx Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_5XXX_SERIES       = 0xDB, // Quad-Core Intel(R) Xeon(R) processor 5xxx Series                                                                                                   // Colorize: green
    DUAL_CORE_INTEL_XEON_7XXX_SERIES       = 0xDD, // Dual-Core Intel(R) Xeon(R) processor 7xxx Series                                                                                                   // Colorize: green
    QUAD_CORE_INTEL_XEON_7XXX_SERIES       = 0xDE, // Quad-Core Intel(R) Xeon(R) processor 7xxx Series                                                                                                   // Colorize: green
    MULTI_CORE_INTEL_XEON_7XXX_SERIES      = 0xDF, // Multi-Core Intel(R) Xeon(R) processor 7xxx Series                                                                                                  // Colorize: green
    MULTI_CORE_INTEL_XEON_3400_SERIES      = 0xE0, // Multi-Core Intel(R) Xeon(R) processor 3400 Series                                                                                                  // Colorize: green
    AMD_OPTERON_3000_SERIES                = 0xE4, // AMD Opteron(TM) 3000 Series Processor                                                                                                              // Colorize: green
    AMD_SEMPRON_II                         = 0xE5, // AMD Sempron(TM) II Processor                                                                                                                       // Colorize: green
    EMBEDDED_AMD_OPTERON_QUAD_CORE         = 0xE6, // Embedded AMD Opteron(TM) Quad-Core Processor Family                                                                                                // Colorize: green
    AMD_PHENOM_TRIPLE_CORE                 = 0xE7, // AMD Phenom(TM) Triple-Core Processor Family                                                                                                        // Colorize: green
    AMD_TURION_ULTRA_DUAL_CORE_MOBILE      = 0xE8, // AMD Turion(TM) Ultra Dual-Core Mobile Processor Family                                                                                             // Colorize: green
    AMD_TURION_DUAL_CORE_MOBILE            = 0xE9, // AMD Turion(TM) Dual-Core Mobile Processor Family                                                                                                   // Colorize: green
    AMD_ATHLON_DUAL_CORE                   = 0xEA, // AMD Athlon(TM) Dual-Core Processor Family                                                                                                          // Colorize: green
    AMD_SEMPRON_SI                         = 0xEB, // AMD Sempron(TM) SI Processor Family                                                                                                                // Colorize: green
    AMD_PHENOM_II                          = 0xEC, // AMD Phenom(TM) II Processor Family                                                                                                                 // Colorize: green
    AMD_ATHLON_II                          = 0xED, // AMD Athlon(TM) II Processor Family                                                                                                                 // Colorize: green
    SIX_CORE_AMD_OPTERON                   = 0xEE, // Six-Core AMD Opteron(TM) Processor Family                                                                                                          // Colorize: green
    AMD_SEMPRON_M                          = 0xEF, // AMD Sempron(TM) M Processor Family                                                                                                                 // Colorize: green
    I860                                   = 0xFA, // i860                                                                                                                                               // Colorize: green
    I960                                   = 0xFB, // i960                                                                                                                                               // Colorize: green
    INDICATOR_FAMILY_2                     = 0xFE  // Indicator to obtain the processor family from the Processor Family 2 field                                                                         // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
// Verified with DmiSpecVerifier [END] // https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToString(DmiProcessorFamily family) // TEST: NO                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | family = %u", family)); // Commented to avoid bad looking logs                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (family)                                                                                                                                                                                      // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case DmiProcessorFamily::NONE:                                   return "NONE";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::OTHER:                                  return "OTHER";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::UNKNOWN:                                return "UNKNOWN";                                                                                                               // Colorize: green
        case DmiProcessorFamily::_8086:                                  return "8086";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::_80286:                                 return "80286";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::INTEL_386:                              return "INTEL_386";                                                                                                             // Colorize: green
        case DmiProcessorFamily::INTEL_486:                              return "INTEL_486";                                                                                                             // Colorize: green
        case DmiProcessorFamily::_8087:                                  return "8087";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::_80287:                                 return "80287";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_80387:                                 return "80387";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_80487:                                 return "80487";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::PENTIUM:                                return "PENTIUM";                                                                                                               // Colorize: green
        case DmiProcessorFamily::PENTIUM_PRO:                            return "PENTIUM_PRO";                                                                                                           // Colorize: green
        case DmiProcessorFamily::PENTIUM_II:                             return "PENTIUM_II";                                                                                                            // Colorize: green
        case DmiProcessorFamily::PENTIUM_MMX:                            return "PENTIUM_MMX";                                                                                                           // Colorize: green
        case DmiProcessorFamily::CELERON:                                return "CELERON";                                                                                                               // Colorize: green
        case DmiProcessorFamily::PENTIUM_II_XEON:                        return "PENTIUM_II_XEON";                                                                                                       // Colorize: green
        case DmiProcessorFamily::PENTIUM_III:                            return "PENTIUM_III";                                                                                                           // Colorize: green
        case DmiProcessorFamily::M1:                                     return "M1";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::M2:                                     return "M2";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::INTEL_CELERON_M:                        return "INTEL_CELERON_M";                                                                                                       // Colorize: green
        case DmiProcessorFamily::INTEL_PENTIUM_4_HT:                     return "INTEL_PENTIUM_4_HT";                                                                                                    // Colorize: green
        case DmiProcessorFamily::AMD_DURON:                              return "AMD_DURON";                                                                                                             // Colorize: green
        case DmiProcessorFamily::K5:                                     return "K5";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::K6:                                     return "K6";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::K6_2:                                   return "K6_2";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::K6_3:                                   return "K6_3";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON:                             return "AMD_ATHLON";                                                                                                            // Colorize: green
        case DmiProcessorFamily::AMD_29000:                              return "AMD_29000";                                                                                                             // Colorize: green
        case DmiProcessorFamily::K6_2_PLUS:                              return "K6_2_PLUS";                                                                                                             // Colorize: green
        case DmiProcessorFamily::POWER_PC:                               return "POWER_PC";                                                                                                              // Colorize: green
        case DmiProcessorFamily::POWER_PC_601:                           return "POWER_PC_601";                                                                                                          // Colorize: green
        case DmiProcessorFamily::POWER_PC_603:                           return "POWER_PC_603";                                                                                                          // Colorize: green
        case DmiProcessorFamily::POWER_PC_603_PLUS:                      return "POWER_PC_603_PLUS";                                                                                                     // Colorize: green
        case DmiProcessorFamily::POWER_PC_604:                           return "POWER_PC_604";                                                                                                          // Colorize: green
        case DmiProcessorFamily::POWER_PC_620:                           return "POWER_PC_620";                                                                                                          // Colorize: green
        case DmiProcessorFamily::POWER_PC_X704:                          return "POWER_PC_X704";                                                                                                         // Colorize: green
        case DmiProcessorFamily::POWER_PC_750:                           return "POWER_PC_750";                                                                                                          // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_DUO:                         return "INTEL_CORE_DUO";                                                                                                        // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_DUO_MOBILE:                  return "INTEL_CORE_DUO_MOBILE";                                                                                                 // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_SOLO_MOBILE:                 return "INTEL_CORE_SOLO_MOBILE";                                                                                                // Colorize: green
        case DmiProcessorFamily::INTEL_ATOM:                             return "INTEL_ATOM";                                                                                                            // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_M:                           return "INTEL_CORE_M";                                                                                                          // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_M3:                          return "INTEL_CORE_M3";                                                                                                         // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_M5:                          return "INTEL_CORE_M5";                                                                                                         // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_M7:                          return "INTEL_CORE_M7";                                                                                                         // Colorize: green
        case DmiProcessorFamily::ALPHA:                                  return "ALPHA";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::ALPHA_21064:                            return "ALPHA_21064";                                                                                                           // Colorize: green
        case DmiProcessorFamily::ALPHA_21066:                            return "ALPHA_21066";                                                                                                           // Colorize: green
        case DmiProcessorFamily::ALPHA_21164:                            return "ALPHA_21164";                                                                                                           // Colorize: green
        case DmiProcessorFamily::ALPHA_21164_PC:                         return "ALPHA_21164_PC";                                                                                                        // Colorize: green
        case DmiProcessorFamily::ALPHA_21164A:                           return "ALPHA_21164A";                                                                                                          // Colorize: green
        case DmiProcessorFamily::ALPHA_21264:                            return "ALPHA_21264";                                                                                                           // Colorize: green
        case DmiProcessorFamily::ALPHA_21364:                            return "ALPHA_21364";                                                                                                           // Colorize: green
        case DmiProcessorFamily::AMD_TURION_II_ULTRA_DUAL_CORE_MOBILE_M: return "AMD_TURION_II_ULTRA_DUAL_CORE_MOBILE_M";                                                                                // Colorize: green
        case DmiProcessorFamily::AMD_TURION_II_DUAL_CORE_MOBILE_M:       return "AMD_TURION_II_DUAL_CORE_MOBILE_M";                                                                                      // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_II_DUAL_CORE_M:              return "AMD_ATHLON_II_DUAL_CORE_M";                                                                                             // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_6100_SERIES:                return "AMD_OPTERON_6100_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_4100_SERIES:                return "AMD_OPTERON_4100_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_6200_SERIES:                return "AMD_OPTERON_6200_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_4200_SERIES:                return "AMD_OPTERON_4200_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_FX_SERIES:                          return "AMD_FX_SERIES";                                                                                                         // Colorize: green
        case DmiProcessorFamily::MIPS:                                   return "MIPS";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::MIPS_R4000:                             return "MIPS_R4000";                                                                                                            // Colorize: green
        case DmiProcessorFamily::MIPS_R4200:                             return "MIPS_R4200";                                                                                                            // Colorize: green
        case DmiProcessorFamily::MIPS_R4400:                             return "MIPS_R4400";                                                                                                            // Colorize: green
        case DmiProcessorFamily::MIPS_R4600:                             return "MIPS_R4600";                                                                                                            // Colorize: green
        case DmiProcessorFamily::MIPS_R10000:                            return "MIPS_R10000";                                                                                                           // Colorize: green
        case DmiProcessorFamily::AMD_C_SERIES:                           return "AMD_C_SERIES";                                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_E_SERIES:                           return "AMD_E_SERIES";                                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_A_SERIES:                           return "AMD_A_SERIES";                                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_G_SERIES:                           return "AMD_G_SERIES";                                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_Z_SERIES:                           return "AMD_Z_SERIES";                                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_R_SERIES:                           return "AMD_R_SERIES";                                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_4300_SERIES:                return "AMD_OPTERON_4300_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_6300_SERIES:                return "AMD_OPTERON_6300_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_3300_SERIES:                return "AMD_OPTERON_3300_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_FIRE_PRO_SERIES:                    return "AMD_FIRE_PRO_SERIES";                                                                                                   // Colorize: green
        case DmiProcessorFamily::SPARC:                                  return "SPARC";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::SUPER_SPARC:                            return "SUPER_SPARC";                                                                                                           // Colorize: green
        case DmiProcessorFamily::MICRO_SPARC_II:                         return "MICRO_SPARC_II";                                                                                                        // Colorize: green
        case DmiProcessorFamily::MICRO_SPARC_IIEP:                       return "MICRO_SPARC_IIEP";                                                                                                      // Colorize: green
        case DmiProcessorFamily::ULTRA_SPARC:                            return "ULTRA_SPARC";                                                                                                           // Colorize: green
        case DmiProcessorFamily::ULTRA_SPARC_II:                         return "ULTRA_SPARC_II";                                                                                                        // Colorize: green
        case DmiProcessorFamily::ULTRA_SPARC_III:                        return "ULTRA_SPARC_III";                                                                                                       // Colorize: green
        case DmiProcessorFamily::ULTRA_SPARC_III_2:                      return "ULTRA_SPARC_III_2";                                                                                                     // Colorize: green
        case DmiProcessorFamily::ULTRA_SPARC_IIII:                       return "ULTRA_SPARC_IIII";                                                                                                      // Colorize: green
        case DmiProcessorFamily::_68040:                                 return "68040";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_68XXX:                                 return "68XXX";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_68000:                                 return "68000";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_68010:                                 return "68010";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_68020:                                 return "68020";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::_68030:                                 return "68030";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_X4_QUAD_CORE:                return "AMD_ATHLON_X4_QUAD_CORE";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_X1000_SERIES:               return "AMD_OPTERON_X1000_SERIES";                                                                                              // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_X2000_SERIES:               return "AMD_OPTERON_X2000_SERIES";                                                                                              // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_A_SERIES:                   return "AMD_OPTERON_A_SERIES";                                                                                                  // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_X3000_SERIES:               return "AMD_OPTERON_X3000_SERIES";                                                                                              // Colorize: green
        case DmiProcessorFamily::AMD_ZEN:                                return "AMD_ZEN";                                                                                                               // Colorize: green
        case DmiProcessorFamily::HOBBIT:                                 return "HOBBIT";                                                                                                                // Colorize: green
        case DmiProcessorFamily::CRUSOE_TM5000:                          return "CRUSOE_TM5000";                                                                                                         // Colorize: green
        case DmiProcessorFamily::CRUSOE_TM3000:                          return "CRUSOE_TM3000";                                                                                                         // Colorize: green
        case DmiProcessorFamily::EFFICEON_TM8000:                        return "EFFICEON_TM8000";                                                                                                       // Colorize: green
        case DmiProcessorFamily::WEITEK:                                 return "WEITEK";                                                                                                                // Colorize: green
        case DmiProcessorFamily::ITANIUM:                                return "ITANIUM";                                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_64:                          return "AMD_ATHLON_64";                                                                                                         // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON:                            return "AMD_OPTERON";                                                                                                           // Colorize: green
        case DmiProcessorFamily::AMD_SEMPRON:                            return "AMD_SEMPRON";                                                                                                           // Colorize: green
        case DmiProcessorFamily::AMD_TURION_64_MOBILE:                   return "AMD_TURION_64_MOBILE";                                                                                                  // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_AMD_OPTERON:                  return "DUAL_CORE_AMD_OPTERON";                                                                                                 // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_64_X2_DUAL_CORE:             return "AMD_ATHLON_64_X2_DUAL_CORE";                                                                                            // Colorize: green
        case DmiProcessorFamily::AMD_TURION_64_X2_MOBILE:                return "AMD_TURION_64_X2_MOBILE";                                                                                               // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_AMD_OPTERON:                  return "QUAD_CORE_AMD_OPTERON";                                                                                                 // Colorize: green
        case DmiProcessorFamily::THIRD_GENERATION_AMD_OPTERON:           return "THIRD_GENERATION_AMD_OPTERON";                                                                                          // Colorize: green
        case DmiProcessorFamily::AMD_PHENOM_FX_QUAD_CORE:                return "AMD_PHENOM_FX_QUAD_CORE";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_PHENOM_X4_QUAD_CORE:                return "AMD_PHENOM_X4_QUAD_CORE";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_PHENOM_X2_DUAL_CORE:                return "AMD_PHENOM_X2_DUAL_CORE";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_X2_DUAL_CORE:                return "AMD_ATHLON_X2_DUAL_CORE";                                                                                               // Colorize: green
        case DmiProcessorFamily::PA_RISC:                                return "PA_RISC";                                                                                                               // Colorize: green
        case DmiProcessorFamily::PA_RISC_8500:                           return "PA_RISC_8500";                                                                                                          // Colorize: green
        case DmiProcessorFamily::PA_RISC_8000:                           return "PA_RISC_8000";                                                                                                          // Colorize: green
        case DmiProcessorFamily::PA_RISC_7300_LC:                        return "PA_RISC_7300_LC";                                                                                                       // Colorize: green
        case DmiProcessorFamily::PA_RISC_7200:                           return "PA_RISC_7200";                                                                                                          // Colorize: green
        case DmiProcessorFamily::PA_RISC_7100_LC:                        return "PA_RISC_7100_LC";                                                                                                       // Colorize: green
        case DmiProcessorFamily::PA_RISC_7100:                           return "PA_RISC_7100";                                                                                                          // Colorize: green
        case DmiProcessorFamily::V30:                                    return "V30";                                                                                                                   // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_3200_SERIES:       return "QUAD_CORE_INTEL_XEON_3200_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_3000_SERIES:       return "DUAL_CORE_INTEL_XEON_3000_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_5300_SERIES:       return "QUAD_CORE_INTEL_XEON_5300_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_5100_SERIES:       return "DUAL_CORE_INTEL_XEON_5100_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_5000_SERIES:       return "DUAL_CORE_INTEL_XEON_5000_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_LV:                return "DUAL_CORE_INTEL_XEON_LV";                                                                                               // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_ULV:               return "DUAL_CORE_INTEL_XEON_ULV";                                                                                              // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_7100_SERIES:       return "DUAL_CORE_INTEL_XEON_7100_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_5400_SERIES:       return "QUAD_CORE_INTEL_XEON_5400_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON:                   return "QUAD_CORE_INTEL_XEON";                                                                                                  // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_5200_SERIES:       return "DUAL_CORE_INTEL_XEON_5200_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_7200_SERIES:       return "DUAL_CORE_INTEL_XEON_7200_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_7300_SERIES:       return "QUAD_CORE_INTEL_XEON_7300_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_7400_SERIES:       return "QUAD_CORE_INTEL_XEON_7400_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::MULTI_CORE_INTEL_XEON_7400_SERIES:      return "MULTI_CORE_INTEL_XEON_7400_SERIES";                                                                                     // Colorize: green
        case DmiProcessorFamily::PENTIUM_III_XEON:                       return "PENTIUM_III_XEON";                                                                                                      // Colorize: green
        case DmiProcessorFamily::PENTIUM_III_SPEED_STEP:                 return "PENTIUM_III_SPEED_STEP";                                                                                                // Colorize: green
        case DmiProcessorFamily::PENTIUM_4:                              return "PENTIUM_4";                                                                                                             // Colorize: green
        case DmiProcessorFamily::INTEL_XEON:                             return "INTEL_XEON";                                                                                                            // Colorize: green
        case DmiProcessorFamily::AS400:                                  return "AS400";                                                                                                                 // Colorize: green
        case DmiProcessorFamily::INTEL_XEON_MP:                          return "INTEL_XEON_MP";                                                                                                         // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_XP:                          return "AMD_ATHLON_XP";                                                                                                         // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_MP:                          return "AMD_ATHLON_MP";                                                                                                         // Colorize: green
        case DmiProcessorFamily::INTEL_ITANIUM_2:                        return "INTEL_ITANIUM_2";                                                                                                       // Colorize: green
        case DmiProcessorFamily::INTEL_PENTIUM_M:                        return "INTEL_PENTIUM_M";                                                                                                       // Colorize: green
        case DmiProcessorFamily::INTEL_CELERON_D:                        return "INTEL_CELERON_D";                                                                                                       // Colorize: green
        case DmiProcessorFamily::INTEL_PENTIUM_D:                        return "INTEL_PENTIUM_D";                                                                                                       // Colorize: green
        case DmiProcessorFamily::INTEL_PENTIUM_EXTREME:                  return "INTEL_PENTIUM_EXTREME";                                                                                                 // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_SOLO:                        return "INTEL_CORE_SOLO";                                                                                                       // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_DUO:                       return "INTEL_CORE_2_DUO";                                                                                                      // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_SOLO:                      return "INTEL_CORE_2_SOLO";                                                                                                     // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_EXTREME:                   return "INTEL_CORE_2_EXTREME";                                                                                                  // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_QUAD:                      return "INTEL_CORE_2_QUAD";                                                                                                     // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_EXTREME_MOBILE:            return "INTEL_CORE_2_EXTREME_MOBILE";                                                                                           // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_DUO_MOBILE:                return "INTEL_CORE_2_DUO_MOBILE";                                                                                               // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_2_SOLO_MOBILE:               return "INTEL_CORE_2_SOLO_MOBILE";                                                                                              // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_I7:                          return "INTEL_CORE_I7";                                                                                                         // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_CELERON:                return "DUAL_CORE_INTEL_CELERON";                                                                                               // Colorize: green
        case DmiProcessorFamily::IBM390:                                 return "IBM390";                                                                                                                // Colorize: green
        case DmiProcessorFamily::G4:                                     return "G4";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::G5:                                     return "G5";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::G6:                                     return "G6";                                                                                                                    // Colorize: green
        case DmiProcessorFamily::Z_ARCHITECTURE:                         return "Z_ARCHITECTURE";                                                                                                        // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_I5:                          return "INTEL_CORE_I5";                                                                                                         // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_I3:                          return "INTEL_CORE_I3";                                                                                                         // Colorize: green
        case DmiProcessorFamily::INTEL_CORE_I9:                          return "INTEL_CORE_I9";                                                                                                         // Colorize: green
        case DmiProcessorFamily::VIA_C7_M:                               return "VIA_C7_M";                                                                                                              // Colorize: green
        case DmiProcessorFamily::VIA_C7_D:                               return "VIA_C7_D";                                                                                                              // Colorize: green
        case DmiProcessorFamily::VIA_C7:                                 return "VIA_C7";                                                                                                                // Colorize: green
        case DmiProcessorFamily::VIA_EDEN:                               return "VIA_EDEN";                                                                                                              // Colorize: green
        case DmiProcessorFamily::MULTI_CORE_INTEL_XEON:                  return "MULTI_CORE_INTEL_XEON";                                                                                                 // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_3XXX_SERIES:       return "DUAL_CORE_INTEL_XEON_3XXX_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_3XXX_SERIES:       return "QUAD_CORE_INTEL_XEON_3XXX_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::VIA_NANO:                               return "VIA_NANO";                                                                                                              // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_5XXX_SERIES:       return "DUAL_CORE_INTEL_XEON_5XXX_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_5XXX_SERIES:       return "QUAD_CORE_INTEL_XEON_5XXX_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::DUAL_CORE_INTEL_XEON_7XXX_SERIES:       return "DUAL_CORE_INTEL_XEON_7XXX_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::QUAD_CORE_INTEL_XEON_7XXX_SERIES:       return "QUAD_CORE_INTEL_XEON_7XXX_SERIES";                                                                                      // Colorize: green
        case DmiProcessorFamily::MULTI_CORE_INTEL_XEON_7XXX_SERIES:      return "MULTI_CORE_INTEL_XEON_7XXX_SERIES";                                                                                     // Colorize: green
        case DmiProcessorFamily::MULTI_CORE_INTEL_XEON_3400_SERIES:      return "MULTI_CORE_INTEL_XEON_3400_SERIES";                                                                                     // Colorize: green
        case DmiProcessorFamily::AMD_OPTERON_3000_SERIES:                return "AMD_OPTERON_3000_SERIES";                                                                                               // Colorize: green
        case DmiProcessorFamily::AMD_SEMPRON_II:                         return "AMD_SEMPRON_II";                                                                                                        // Colorize: green
        case DmiProcessorFamily::EMBEDDED_AMD_OPTERON_QUAD_CORE:         return "EMBEDDED_AMD_OPTERON_QUAD_CORE";                                                                                        // Colorize: green
        case DmiProcessorFamily::AMD_PHENOM_TRIPLE_CORE:                 return "AMD_PHENOM_TRIPLE_CORE";                                                                                                // Colorize: green
        case DmiProcessorFamily::AMD_TURION_ULTRA_DUAL_CORE_MOBILE:      return "AMD_TURION_ULTRA_DUAL_CORE_MOBILE";                                                                                     // Colorize: green
        case DmiProcessorFamily::AMD_TURION_DUAL_CORE_MOBILE:            return "AMD_TURION_DUAL_CORE_MOBILE";                                                                                           // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_DUAL_CORE:                   return "AMD_ATHLON_DUAL_CORE";                                                                                                  // Colorize: green
        case DmiProcessorFamily::AMD_SEMPRON_SI:                         return "AMD_SEMPRON_SI";                                                                                                        // Colorize: green
        case DmiProcessorFamily::AMD_PHENOM_II:                          return "AMD_PHENOM_II";                                                                                                         // Colorize: green
        case DmiProcessorFamily::AMD_ATHLON_II:                          return "AMD_ATHLON_II";                                                                                                         // Colorize: green
        case DmiProcessorFamily::SIX_CORE_AMD_OPTERON:                   return "SIX_CORE_AMD_OPTERON";                                                                                                  // Colorize: green
        case DmiProcessorFamily::AMD_SEMPRON_M:                          return "AMD_SEMPRON_M";                                                                                                         // Colorize: green
        case DmiProcessorFamily::I860:                                   return "I860";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::I960:                                   return "I960";                                                                                                                  // Colorize: green
        case DmiProcessorFamily::INDICATOR_FAMILY_2:                     return "INDICATOR_FAMILY_2";                                                                                                    // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToFullString(DmiProcessorFamily family) // TEST: NO                                                                                                                              // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | family = %u", family)); // Commented to avoid bad looking logs                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[46];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%02X (%s)", (u8)family, enumToString(family));                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMIPROCESSORFAMILY_H                                                                                                                                      // Colorize: green
