#ifndef COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMITEMPERATUREPROBELOCATION_H                                                                                                                               // Colorize: green
#define COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMITEMPERATUREPROBELOCATION_H                                                                                                                               // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/shared/common/log/assert.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/log/log.h>                                                                                                                                                              // Colorize: green
#include <com/ngos/shared/common/ngos/types.h>                                                                                                                                                           // Colorize: green
#include <com/ngos/shared/common/printf/printf.h>                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
enum class DmiTemperatureProbeLocation: u8                                                                                                                                                               // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    NONE                     = 0,                                                                                                                                                                        // Colorize: green
    OTHER                    = 1,                                                                                                                                                                        // Colorize: green
    UNKNOWN                  = 2,                                                                                                                                                                        // Colorize: green
    PROCESSOR                = 3,                                                                                                                                                                        // Colorize: green
    DISK                     = 4,                                                                                                                                                                        // Colorize: green
    PERIPHERAL_BAY           = 5,                                                                                                                                                                        // Colorize: green
    SYSTEM_MANAGEMENT_MODULE = 6,                                                                                                                                                                        // Colorize: green
    MOTHERBOARD              = 7,                                                                                                                                                                        // Colorize: green
    MEMORY_MODULE            = 8,                                                                                                                                                                        // Colorize: green
    PROCESSOR_MODULE         = 9,                                                                                                                                                                        // Colorize: green
    POWER_UNIT               = 10,                                                                                                                                                                       // Colorize: green
    ADD_IN_CARD              = 11,                                                                                                                                                                       // Colorize: green
    FRONT_PANEL_BOARD        = 12,                                                                                                                                                                       // Colorize: green
    BACK_PANEL_BOARD         = 13,                                                                                                                                                                       // Colorize: green
    POWER_SYSTEM_BOARD       = 14,                                                                                                                                                                       // Colorize: green
    DRIVE_BACK_PLANE         = 15                                                                                                                                                                        // Colorize: green
};                                                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToString(DmiTemperatureProbeLocation location) // TEST: NO                                                                                                                       // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | location = %u", location)); // Commented to avoid bad looking logs                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    switch (location)                                                                                                                                                                                    // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        case DmiTemperatureProbeLocation::NONE:                     return "NONE";                                                                                                                       // Colorize: green
        case DmiTemperatureProbeLocation::OTHER:                    return "OTHER";                                                                                                                      // Colorize: green
        case DmiTemperatureProbeLocation::UNKNOWN:                  return "UNKNOWN";                                                                                                                    // Colorize: green
        case DmiTemperatureProbeLocation::PROCESSOR:                return "PROCESSOR";                                                                                                                  // Colorize: green
        case DmiTemperatureProbeLocation::DISK:                     return "DISK";                                                                                                                       // Colorize: green
        case DmiTemperatureProbeLocation::PERIPHERAL_BAY:           return "PERIPHERAL_BAY";                                                                                                             // Colorize: green
        case DmiTemperatureProbeLocation::SYSTEM_MANAGEMENT_MODULE: return "SYSTEM_MANAGEMENT_MODULE";                                                                                                   // Colorize: green
        case DmiTemperatureProbeLocation::MOTHERBOARD:              return "MOTHERBOARD";                                                                                                                // Colorize: green
        case DmiTemperatureProbeLocation::MEMORY_MODULE:            return "MEMORY_MODULE";                                                                                                              // Colorize: green
        case DmiTemperatureProbeLocation::PROCESSOR_MODULE:         return "PROCESSOR_MODULE";                                                                                                           // Colorize: green
        case DmiTemperatureProbeLocation::POWER_UNIT:               return "POWER_UNIT";                                                                                                                 // Colorize: green
        case DmiTemperatureProbeLocation::ADD_IN_CARD:              return "ADD_IN_CARD";                                                                                                                // Colorize: green
        case DmiTemperatureProbeLocation::FRONT_PANEL_BOARD:        return "FRONT_PANEL_BOARD";                                                                                                          // Colorize: green
        case DmiTemperatureProbeLocation::BACK_PANEL_BOARD:         return "BACK_PANEL_BOARD";                                                                                                           // Colorize: green
        case DmiTemperatureProbeLocation::POWER_SYSTEM_BOARD:       return "POWER_SYSTEM_BOARD";                                                                                                         // Colorize: green
        case DmiTemperatureProbeLocation::DRIVE_BACK_PLANE:         return "DRIVE_BACK_PLANE";                                                                                                           // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        default: return "UNKNOWN";                                                                                                                                                                       // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
inline const char8* enumToFullString(DmiTemperatureProbeLocation location) // TEST: NO                                                                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // COMMON_LT((" | location = %u", location)); // Commented to avoid bad looking logs                                                                                                                 // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    static char8 res[32];                                                                                                                                                                                // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    sprintf(res, "0x%02X (%s)", (u8)location, enumToString(location));                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    return res;                                                                                                                                                                                          // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#endif // COM_NGOS_SHARED_COMMON_DMI_ENTRY_LIB_DMITEMPERATUREPROBELOCATION_H                                                                                                                             // Colorize: green
