#include "indentspacesverifier.h"                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#include <com/ngos/devtools/code_verifier/other/codeverificationfiletype.h>                                                                                                                              // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
#define SPACE_INDENT 4                                                                                                                                                                                   // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
IndentSpacesVerifier::IndentSpacesVerifier()                                                                                                                                                             // Colorize: green
    : BaseCodeVerifier(VERIFICATION_INDENT_SPACES)                                                                                                                                                       // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    // Nothing                                                                                                                                                                                           // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void IndentSpacesVerifier::verify(CodeWorkerThread *worker, const QString &path, const QString &/*content*/, const QStringList &lines)                                                                   // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    for (qint64 i = 0; i < lines.size(); ++i)                                                                                                                                                            // Colorize: green
    {                                                                                                                                                                                                    // Colorize: green
        QString line = lines.at(i);                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
        for (qint64 j = 0; j < line.length(); ++j)                                                                                                                                                       // Colorize: green
        {                                                                                                                                                                                                // Colorize: green
            QChar ch = line.at(j);                                                                                                                                                                       // Colorize: green
                                                                                                                                                                                                         // Colorize: green
            if (ch != ' ')                                                                                                                                                                               // Colorize: green
            {                                                                                                                                                                                            // Colorize: green
                if (ch == '\t')                                                                                                                                                                          // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    worker->addError(path, i, "Combination of tabs and spaces in indent");                                                                                                               // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                else                                                                                                                                                                                     // Colorize: green
                {                                                                                                                                                                                        // Colorize: green
                    if (j % SPACE_INDENT != 0)                                                                                                                                                           // Colorize: green
                    {                                                                                                                                                                                    // Colorize: green
                        worker->addError(path, i, "Invalid indentation");                                                                                                                                // Colorize: green
                    }                                                                                                                                                                                    // Colorize: green
                }                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                break;                                                                                                                                                                                   // Colorize: green
            }                                                                                                                                                                                            // Colorize: green
        }                                                                                                                                                                                                // Colorize: green
    }                                                                                                                                                                                                    // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
IndentSpacesVerifier indentSpacesVerifierInstance;                                                                                                                                                       // Colorize: green
