#include "trackinglineedit.h"                                                                                                                                                                            // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
                                                                                                                                                                                                         // Colorize: green
TrackingLineEdit::TrackingLineEdit(const QString &contents, QWidget *parent)                                                                                                                             // Colorize: green
    : QLineEdit(contents, parent)                                                                                                                                                                        // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    setMouseTracking(true);                                                                                                                                                                              // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void TrackingLineEdit::focusInEvent(QFocusEvent *event)                                                                                                                                                  // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QLineEdit::focusInEvent(event);                                                                                                                                                                      // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    emit entered();                                                                                                                                                                                      // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
                                                                                                                                                                                                         // Colorize: green
void TrackingLineEdit::focusOutEvent(QFocusEvent *event)                                                                                                                                                 // Colorize: green
{                                                                                                                                                                                                        // Colorize: green
    QLineEdit::focusOutEvent(event);                                                                                                                                                                     // Colorize: green
                                                                                                                                                                                                         // Colorize: green
    emit leaved();                                                                                                                                                                                       // Colorize: green
}                                                                                                                                                                                                        // Colorize: green
