#ifndef OS_SHARED_COMMON_SRC_BITS64_RANDOM_RANDOM_H
#define OS_SHARED_COMMON_SRC_BITS64_RANDOM_RANDOM_H



#include <ngos/types.h>



u64 simpleRandom(u64 seed = 0);



#endif // OS_SHARED_COMMON_SRC_BITS64_RANDOM_RANDOM_H
